= Funerální symbolika květin

[quote, O. F. Babler]
Květina je krása zakletá do snů a ticha.

[quote, K. Biebl]
Až umřem, staneme se květinami. Ve dne budem lidem pro radost a v noci budem sami.

*KVĚTINY* jsou důležitou součástí našeho života pro svou krásu, něžnost, vůni, léčivé schopnosti. Doprovází nás od narození, přes náš život (např. narozeninové, svatební kytice) až po smrt (např. kytice na rakev, hrob). Krášlí naše domovy, pomáhají nám relaxovat, vyjadřovat emoce, které nedokážeme vyslovit slovy.

Staří řečtí filosofové mluví o duši rostlin a básník H. Heine říká, že vůně je citem květin. Nelze se tedy divit, že představa ráje je vždy spojená se záplavou kvetoucích květin.

Svým významem pro nás jsou i nositelem různé symboliky. A také důvodem, proč si lidé vždy vymýšleli legendy, pohádky o tom, jak která květina vznikla. Vždy jde o příběh, který popisuje, jak se v květinu proměnil člověk, jak z jeho slz či krve květina vyrostla, jak vyrostla z jeho mrtvého těla.

[quote]
.Pro ilustraci poslouží pověst o kvítku *čekance:*
____
Jedna dívka s překrásnýma modrýma očima měla milého, kterého ji odvedli
na vojnu. Slíbila mu, že na něho bude čekat. Každý den stávala u cesty a
vyhlížela ho, zda se nevrací.

Plynula léta, ona zešedivěla, zestárla, jen její očí stále zářily
nebeskou modří. Milý se nevracel. Dívka se nakonec proměnila v květinu
čekanku. Roste u cest a její kvítka jsou modré jako její oči a to proto,
aby jí její milý poznal, až se vrátí.
____

Čekanka se tak stala symbolem věrné, čekající lásky.

== Paznehtník (Akant)

Akant je druh bodláku. Má růžice ostrých listů. Tvar rostliny je využíván jako dekorace hlavic tzv. Korintských sloupů.

K tomu se váže následující legenda: _Krásná dívka z Korintu onemocněla a zemřela. Během pohřbu její ošetřovatelka uložila všechny dívčiny šperky do košíku a položila na hrob. Košík přikryla dlaždicí._

_Na hrobě rostly akanty. Na jaře se snažily překonat překážku (dlaždici) a tak se ohýbaly podle jejich hran. Hrob navštívil sochař a architekt Kallimachos. Vzhled zkroucených akantů se mu tak zalíbil, že jej použil na hlavici sloupu._

Ve Středomoří akant symbolizoval život a nesmrtelnost a proto byl vysazován na hřbitovech a kladen na hroby. Dle křesťanství symbolizuje nesmrtelnost a jeho trny hřích a utrpení.

== Asfodel (Asphodelus)

Asdofel byl spjat s podsvětím. Z děl antických autorů víme, že existovalo několik představ o tom, co se dělo s duší po smrti. Nejznámější byla představa tří úrovňového podsvětí. Nejhlouběji ležela temná propast Tartaru, kde si svůj trest odpykávaly duše zlých a špatných lidí. Duše padlých hrdinů odcházely po smrti na Elysejská pole, která představovala jakýsi ráj, kde měli duchové i možnost inkarnace. Zbytek podsvětní říše tvořily tiché a pochmurné louky porostlé asfodelem, kde se zdržovali duchové lidí, jež nebyli za života ani zlí ani výjimečně dobří.

Asfodel byl spjat se smrtí a smutkem nad odchodem blízkého člověka. Proto se tato rostlina sázela na hroby a v podobě girland se používala k ozdobě pohřebních prostor i samotných zemřelých. Jejich hlíza byla vnímána jako pokrm mrtvých.

Byl symbolem podsvětní říše a proto se jim zdobila bohyně Persefona (manželka vládce podsvětí Hada). Byl také součástí zahrady magických rostlin bohyně Hekaté (měsíční bohyně, královna podsvětí, vládkyně křižovatek). Proto se sázel blízko domovních dveří, aby chránil před černou magií a současně aby zabránil sebevražedným pokusům těch, kteří v domě žijí.

== Bob (Faba vulgaris)

Bob byl starými Kelty uctíván jako hlavní pokrm mrtvých a mrtví jsou ti, kdo dávají zemi plodnost a hojnost. Semeno bobu symbolizuje embryo a znovuzrození mrtvých předků.

== Chryzantéma (Chrysanthemum)

Chryzantéma je u nás často spojována se svátkem Dušiček a je také známa pod názvem listopadka či dušička. Díky tomuto získala smutné označení jako pohřební květina. Takto je vnímána i v mnoha jiných zemích, protože krásně rozkvétá na podzim v době svátku Všech svatých a Dušiček, a její květy vydrží dlouho svěží.

Bílé se nosily na hroby dětí a mladých dívek, tmavší mužům, žluté a tmavě červené maminkám a ženám.

Ve východní Asii je to velice oceňována květina. Je znakem japonských císařů a pro Japonce je chryzantéma symbolem slunce, síly a zdraví. Japonci každoročně slaví slavnost chryzantém (kiku macuri), která souvisí s tradicí kultu či obdivování květů.

V předminulém století zařadil japonský císař mezi nejvyšší státní vyznamenání Chryzantémový řád.

Japonci věří, že když se umyjete rosou z této květiny, zaručí vám to zdraví a dlouhověkost. Dlouhý život a zdraví ale prý zaručí i jeden lístek z chryzantémy ve sklenici s vínem.

Japonská legenda _hovoří o zamilované dívce, která chtěl zjistit, jak dlouho ji bude její milý mít rád. Zjevilo se ji božstvo, které ji řeklo, že láska jejího snoubence potrvá tolik roků, kolik lístků bude mít květina, kterou si vybere._

_Dívka se rozhodla pro kopretinu. Vytáhla z vlasů jehlici a tou roztřepila každý květinový plátek na množství uzoučkých pásků. Tak se zrodila chryzantéma._

Podle staré čínské legendy se _jeden císař doslechl o květině věčného mládí a rozhodl se ji získat. Měla růst na Dračím ostrově a utrhnout ji mohlo pouze dítě. Když dětská výprava s císařem dorazila na Dračí ostrov, nalezli tu krásnou zlatou chryzantému._

V Číně je chryzantéma symbolem dlouhého života a podzimu. Zejména bílé *kopretinové chryzantémy* jsou považovány za symbol věčného života.

V Číně je velice oblíbený čaj dlouhověkosti a krásy z výtažků chryzantém.

Chryzantéma je často považována za smuteční květinu. Proto není zvykem ji darovat jako kytici. Avšak díky dlouhé trvanlivosti, množství barev a své dostupnosti po celý rok, nachází v moderní floristice široké využití a její vnímání jen jako pohřební květiny pozvolna ustupuje.

== Jahoda (Fragaria)

Jahoda byla ve středověku považována za rajský pokrm předčasně zemřelých, spasených dětí.

V Čechách panoval zvyk, že _matky, kterým zemřelo dítě až do sv. Jana nejedly ani třešně ani jahody, neboť tou dobou v ráji chodí Panna Marie a rozdává malým dětem rajské ovoce. A dítě, jehož matka ovoce jedla, nic nedostane._

Na Šumavě _první tři jahody, které děti nasbíraly, ukládaly na pařez pro ubohé duše v očistci. Také jahody, které někomu z ruky vypadly, se nezvedaly, ale nechaly ležet pro nevinné dušičky._

== Kala (Calla)

Kala je symbolem nových začátků a proto je spojena jak se svatbami, tak s pohřby.

Bílá barva ve spojení se zářivě žlutým středem květu vyvolává pocit nových začátků a proto je oblíbená jako svatební květina, kdy spolu dva lidé začínají žít nový život.

Kaly ale vidíme i ve smutečních vazbách - nový začátek je vnímán jako znovuzrození.

== Kamélie (Camellia)

Kamélie jsou pokládány za květinu nepřinášející štěstí. V Japonsku jsou to květiny určené pro smuteční příležitosti.

== Karafiát (Dianthus)

Karafiát, zejména bílý a červený, se v malířském umění stal symbolem předčasné smrti Ježíše. Svým květem připomínají hřeby, kterými byl ukřižován. Vyrostly ze slz Panny Marie, které kanuly na kapky Ježíšovy krve, které zanechával na zemi při cestě na Kalvárii.

== Konvalinka (Convallaria majalis)

Konvalinka vonná je symbolem mládí, čisté lásky i svatosti. Patří mezi mariánské květy (zasvěcené Panně Marii). Jejich sklopené kvítka mají symbolizovat pokoru. Je jednou z květin lidově nazývaných „slzy Panny Marie“, protože údajně vyrostla na místě, kde Panna Marie plakala.

== Kopřiva (Urtica)

Kopřiva je rostlina vyznačující se silnou magií (léčení bylo dříve považované za druh magie). Často ji najdeme na opuštěných hrobech, v příkopech.

Protože roste na místech, které vyzařují energii, byla považována za rostlinu, nacházející se „na pomezí světů“. Věřilo se, že roste tam, kde lze vstoupit do podsvětí a proto spojuje oba světy. Používala se pro „cesty“ do podsvětí a pro kontakt s dušemi zemřelých.

Keltové pili kopřivové pivo či víno při iniciaci, oslavách narození, při smrti. Kopřiva sloužila pro ochranu před démony a duchy. Má totiž schopnost zachytit veškerou negativní energii. Proto ji naši předkové usušenou rozhazovali kolem domu, zahrady a polí.

Olej z ní se používal k vysvěcení některých magických pomůcek pro rituály. Roucho napuštěné olejem z kopřivy údajně vyvolávalo vize.

Bývala zasvěcená Bohům hromu (Thor, Perun). Její pálivost/žahavost vysvětluje několik legend. Jedna z nich praví, že _když při bouřce blesky prostupují kopřivou, dávají ji svou energií_. Jiná legenda říká, že _její kořen uštknul podsvětní had a tak ji předal trochu svého jedu._

Když někdo trpěl strachem ze zdánlivé smrti, doporučovalo se takového člověka, když zemřel, pořádně vyšlehat kopřivami, aby se zjistilo, zda je skutečně mrtev.

Semena kopřivy bývala součástí nápojů lásky.

Kopřiva patří mezi textilní rostliny. Je tedy zasvěcena i Bohyni. Košile utkaná z jejího vlákna byla mocnou ochranou proti klamům a iluzím a proto se kopřivě přisuzovala schopnost vracet vědomí do přirozeného stavu.

S touto magickou vlastností kopřivy se setkáváme i v pohádkách (B. Němcová -Sedmero krkavců, P. Dobšinský - Traja zhavranělí bratia, H. CH. Andersen - Divoké labutě). _Košile z kopřiv, které utká sestra zakletých bratrů a to bez pronesení jediného slova, je v těchto pohádkách prostředkem ke zlomení kletby._

_Její bratři jsou totiž proměněni v ptáky a jsou nuceni žít na pomezí světů (ve dne jako ptáci, v noci jako lidé)._

Zlomení kletby znamená, že jsou navráceni do světa lidí (tedy jejich vědomí se nachází v přirozeném stavu).

== Kosatec (Iris)

Kosatec je někdy nazýván „lilie mečů“. Vyjadřuje zármutek Marie nad smrtí syna.

Iris byla v Řecké mytologii bohyni sloužící Diovi a Héře. Kde se její nohy dotkly země, vyrostl kosatec. Jedním z jejich úkolů bylo doprovázet duše zemřelých žen na Elysejské pole. Iris byl přisuzován kosatec, a proto se tyto květiny pokládaly na hrob zemřelých žen.

U nás se s oblibou vysazoval na venkovských hřbitovech.

== Lilie bělostná (Lilium candidum)

Lilie bělostná bývá znamením nevinnosti, čistého ušlechtilého myšlení, panenské čistoty, ale i znamením smrti a jako pohřební květina symbolizuje věrnou, i po smrti trvající lásku. Je symbolem nesmrtelnosti a vzkříšení a proto bývala tesána na náhrobní kameny a je častým atributem svatých.

V legendách ohlašuje smrt klášterního bratra.

Podle helenistické pověsti vznikla v okamžiku, kdy na zem dopadlo mléko
bohyně Juno, když krmila malého Herkula.

Řecká pověst hovoří o tom, že _Illiona zasadila na hrob svého zavražděného bratra Polydora jeho přelomené kopí. To se ujalo a vyrostlo v sněhobílou květinu omamné vůně, jejíž vnitřek byl ale plný krvavého prášku, který při nejmenším dotyku nechával na všem znamení krve._

Sofokles ve své tragedii Antigona uvádí, že _Antigona, odsouzena k smrti , dala své sestře pouzdro, jež dostala od snoubence Homeona. Ten se nechal s Antigonou za živa pohřbít do společného hrobu._

_Isméne vložila dotyčné pouzdro do jejich hrobu. Brzy na něm vypučela vonící bílá rostlina. Když se ji ptali, jak se květina jmenuje, odpovídala: „Je to pouhé pouzdro – lilie.“_

Vergilius nechává svého hrdinu Aenea putovat do podsvětí, aby navštívil svého otce. Ten mu ukáže i duše mrtvých, které čekají na nový život. Lilie je zde darem pro duši, kterou čeká vzkříšení a nový osud.

Křesťanstvo připisuje lilii jako mariánské květině cudnost a čistou. Je spjata s pokáním. Traduje se, že vyrostla ze slz, které prolila Eva při odchodu z ráje.

== Mák (Papaver)

Mák byl spojován se spánkem a sny. S makovicemi či makovými květy bývá zobrazován Hypnos (Spánek), Thanatos (Smrt) a Nyx (Noc). Souvisí to s účinky opia, který je získáván z nezralých makovic.

Morfeus (bůh snů v řecké mytologii, syn boha spánku Hypna) se mákem dotýkal smrtelníka, když chtěl, aby upadl v líbezný spánek. Zobrazovali ho s makovým věncem na hlavě.

Mák byl také spjat s mýtem o Persefoně. Persefona právě trhala vlčí máky, když ji vládce podsvětí Hádes unesl. Bůh Zeus dal její matce okusit máku, aby zmírnil zotavujícím spánkem její žal nad únosem dcery.

Brána snů (ilustrace ze 16. století Homérovy Odyssey) je plná symbolů: Uprostřed stojí bohyně spánku s kyticí máků. Napravo od ní je Brána rohu (je nad ní hlava rohatého dobytčete) – z této brány přicházejí pravé sny. Nalevo je Slonovinová brána (nad ní je hlava slona) – z této brány přicházejí falešné sny. Nahoře je bohyně měsíce Diana a Noc s nemluvňaty Spánkem a Smrtí.

V Číně je mák nazýván „bylinou vzpomínání“. Legenda praví, že _jeden muž byl tak sklíčený smrtí své ženy, že chodil denně na její hrob. Jednoho dne vyrostla na hrobě bylina, která mu pomohla zapomenout na jeho zármutek._ _Byl to mák, z jehož makovic se vyrábí opium._

Na Ukrajině bylo zvykem posypat zemřelého v rakvi mákem a pytlíček s mákem mu položit k nohám. Věřili, že nebožtík nebude chodit strašit lidi, protože musí nejdříve ten mák přepočítat.

Porodní bábě dávali na rakev hůl a šátek s mákem, aby se mohla bránit na onom světě dušičkám dětí. Ty se na ni oboří, že jim pomohla k těžkému pozemskému životu. Když se jim bába neubrání holí, rozsype mák. Dušičky se dají do sbírání a ona mezitím uteče.

Od první světové války se vlčí máky používají jako připomínka padlých vojáků, neboť vlčí máky vyrostly v obrovském množství na bitevním poli ve Flandrech.

== Narcis (Narcissus)

Narcis je znakem příbuznosti smrti a spánku, představou smrti jako spánku, vítězstvím nad smrtí i zmrtvýchvstání, symbolem zrození, symbol víry v posmrtný život duše.

Řekové ho považovali za květ pohřební. Narcisové věnce pokládali zemřelému na hlavu. Narcis je spojen s pomíjivosti a je to květ bohyně podsvětí Persefony. Své věnce z nich vily Furie, bohyně odplaty.

Na hrobech se pěstoval jako symbol znovuzrození ve smyslu, že smrt je jen období spánku.

_Podle starověké řecké báje byl Narkissos/Narcis nejkrásnější muž na světě. Pohrdl láskou nymfy a bohyně Afrodité ho za to potrestala. Narckissos se zamiloval do svého obrazu, který spatřil ve vodě, a umřelh touto nenaplnitelnou láskou. Proměnil se v květinu, která je po něm pojmenovaná._

Jiná verze hovoří o tom, že _Narkissos měl sestru, dvojče, kterou velice miloval. Aby utlumil svou bolest z její smrti, šel ke studánce, aby tím, že se podívá na svůj obraz ve vodě, měl i nadále sestřin obraz před sebou. Tím více však pocítil lítost nad její ztrátou, a raději se vrhl do vody a utopil se. Na místě, kde stál, vyrostla květina, která je po něm pojmenována._

== Routa (Ruta)

Routa je v německém prostředí zvaná „býlí mrtvých“, protože se zemřelým dával na prsa nebo kolem krku věnec z routy. Podle lidové pověry ji má sázet jen starý člověk, který stejně zemře.

Patří mezi magické byliny, protože chrání před čarodějnicemi.

== Růže (Rosa)

Růže nese mnoho symbolů v závislosti na kulturách. Je považována za královnu květin. Byla vždy oblíbená. Už v egyptských hrobech byly nalezeny věnce z růží. Tento zvyk byl také pěstován u Řeků a Římanů. Považovali ji za dar bohů. Křesťanství na ni nahlíželo jako na rostlinu Ráje. Podle perské pověsti byla darem samotného Alláha.

Existuje několik pověstí o vzniku růže spjatých se smrtí. Podle starožidovské pověsti povstala z krve Abelovy. Podle řecké z krve Adonidovy, když ho bůh války Ares zabil v podobě kance.

Zejména červená růže je symbolem mučedníků (připomíná barvu krve), minulosti a Kristovy smrti. Plané růže s pěti okvětními lístky znamenají pět ran Kristových.

U nás se vypráví pověst o „Růžovém paloučku“, který je poset červenými růžičkami. Nachází se nedalo Morašic. _Vypráví se, že čeští bratři museli pro svou víru opustit zemi, na tom paloučku se s ní loučili. Z jejich slz vyrostly červené růže. Tyto růže se prý nedají přesadit._

V jedné slovinské písní se zpívá, že na hrobě jinocha vyrůstá červená růže. Bílá růže značí nevinnost, mládí, čistotu a úmrtí.

Známá je povídka O. Wilda Slavík a růže. _Studen pláče, že nemá rudou růži pro tu, co miluje. Slyšel to slavík a ptal se růžového keře, jak může získat červenou růži pro zoufalého studenta. Ten mu prozradil, že ji může vytvořit za měsíčního světla z hudby a zbarvit krví ze svého srdce. Musí zpívat s hrudí nabodnutou na trn. Jeho krev se tak stane krví růže. Slavíkovi bylo smutno, protože považoval smrt za jedinou růži za vysokou cenu. Ale slitoval se nad studentem a ten k ránu našel ve své zahradě nádhernou červenou růži. Pod ní ležel mrtvý slavík se srdcem probodnutým trnem._

Studen s radostí odnesl růži své obdivované, ta ji však odmítla. Dávala přednost šperkům. Student se urazil a růži zahodil do kaluže na cestě.

V pražské pověsti O šípkové růži z Bílé hory _se vypráví o mladém Švédovi Torovi, který byl tak chudý, že mu nezbývalo nic jiného, než se stát vojákem v panských službách. Dostal se s vojskem do Nizozemí, kde se zamiloval do dívky Josefiny. Protože Tor se nemohl z vojny vykoupit, musel dál sloužit. Josefina_ _ho milovala a tak táhla s ostatními za vojskem, aby byla Torovi nablízku._

Za nějaký čas se oba s vojskem dostali do Čech. Vojsko pochodovalo na Prahu. U letohrádku se odehrála velká bitva, ve které Tor padl. Tora pochovali u zdi letohrádku a Josefina zůstala u jeho hrobu několik dní. Nejedla, nepila. Pak vstala a odešla neznámo kam.

Na hrobě Tora se objevil příštím rokem výhonek šípkové růže. Rostl velice rychle. Každé jaro rozkvétá velkým množstvím květů. Každého, kdo ho chtěl zničit, potkalo neštěstí (smrt někoho blízkého, zlá nemoc, zranění, které se nikdy nezahojilo).

Zlomená růže je symbolem zlomeného, předčasně zmařeného života.

V antice růže symbolizovala pomíjivost života, neboť rychle uvadá.

U Germánů byla také spojována se smrtí, a byla proto vysazována na obětních místech a na hrobech. Do hrobu zemřelému nebyla však vkládána, protože se věřilo, že pak keř, z něhož byla utržena, uschne.

Pro pomíjivost své krásy značila růže na náhrobcích předčasnou smrt, a tak se dostala mezi květy pohřební. Poselkyní smrti je růže bílá. Pro hřbitov byl používán i výraz „Růžová zahrada“.

Růže hraje významnou úlohu v jedné z pověstí o slavném židovském, rabínovi._ Rabín Löw se velice trápil tím, že Prahu navštívil mor a nejhůře řádil v Židovském městě. Proti moru nebylo léku._

_Jednou v noci došel na hřbitov. Za svitu pochodní tu hloubili nové hroby. Rabín zahlédl zahalenou postavu, která stála ve vratech hřbitova. Byla to Smrt. Držela v kostlivých prstech list. Na něm byla napsána jména těch, kdo měli druhý den zemřít._

_Rabín vyškubl Smrti list z prstů a doma zjistil, že je na tom seznamu i on. Spálil ho. Té noci morová rána ustoupila z města._

Smrt se chtěla rabína zmocnit. Číhala na něj, ale rabín ji poznával z dálky a vyhýbal se ji. Když měl 97 let, seděl obklopen svými milými a přijímal přání. Tu k němu přistoupila nejmladší vnučka a podala mu čerstvou růži Rabín k ní přivoněl a hlava mu klesla. V růži se skrývala Smrt.

Ve starém Římě hrála velkou úlohu v kultu zemřelých, když se slavil svátek zemřelých tzv. Rosaria. Římané růže pokládali na hroby jako projev smutku. Nesymbolizovala jen krátkost života, ale i naději na pokračování života v jiném světe.

Rozkvetlá růže v umění často symbolizovala pomíjivost světských radostí. Jímavý text o růžích napsal Petr Novák v písni Náhrobní kámen. _Zpívá v ní o víle, která chodila po světě s kyticí růží a rozdávala lidem štěstí a svůj smích. Svou lásku lidem rozdala, a sama už pak nemohla žít. Když ji uviděl na zvadlých květech věčně snít, postavil ji náhrobní kámen, na který ji položil čerstvé růže._

== Tulipán (Tulipa)

Tulipán má protichůdné významy (pýcha, rozmařilost, vyznání lásky atd.). O jednom z jeho symbolů vypráví turecká legenda:

_Princ Farhad se zamiloval do dívky jménem Shirin. Když byla zavražděna, vzal si život také. Z kapek jejich krve pak vyrostly dva šarlatové tulipány. Tak se tulipány staly symbolem „lásky až za hrob.“_

== Obilí

Zasetí zrna do nitra země bylo ve starověku asociováno s pohřbem zemřelého a vzrůstem nového obilí – vzkříšení. Obilná zrna se také vkládala do hrobů zemřelých. Pokud vzklíčila, znamenalo to, že se nebožtík dočká po smrti nového života. Symbolizovala nový život.

Obilné pole zralé ke sklizni je koncentrovaným symbolem dvojího tajemství života - jak vzdálená a současně jak blízká je v životě smrt.

Obilí bylo v Řecku a Římě také spojeno s _mýtem o únosu Kóré (Prosperiny) Hádem do podsvětí (zde pak nazývána Persefona). Její matka Demétér prohlásila, že na zemi nevzejde jediná plodina, dokud se její dcera k ní nevrátí._

_Když nastal hladomor, bohové přistoupili na její podmínku s tím, že Persefona může natrvalo opustit Hádovu říši jen tehdy, pokud tam ještě nic nepojedla. Ale ukázalo se, že Persefona snědla několik zrnek z granátového jablka, které ji Hádes nabídl._

_Nakonec bylo rozhodnuto, že bude část roku trávit se svou matkou a část v podsvětí se svým manželem. Když se Persefona setkává se svou matkou, příroda ožívá._

V mysterijích vztahujících se k Demétér hlavní úlohu hraje obilní klas.

Pšeniční klas symbolizuje zmrtvýchvstalého Krista.

Slované a Germáni dlouho zachovávaly obyčej ponechat na poli stát několik nepožatých stébel, aby bohové, kteří svůj život sdílejí s obilím, nebyli zmařeni.

Slované mají také svůj mýtus o obilí. _První lidé soupeřili o jídlo se zvířaty. Od zvířat se učili, co je jedlé a co ne. Často trpěli hlady. Po večerech si vyprávěli o zázračné vysoké bylině s velkými zlatými zrny, která umí zahnat hlad i v zimě. Patří bohům. A velice po ní toužili._

_V té době jména lidé dostávali velmi pozdě, někteří až po smrti, nebo za života podle vykonaného velkého skutku. Jeden bezejmenný chlapec se zamiloval do dívky a toužil pro ni vykonat velký čin a získat tak jméno. Rozhodl se tu bylinu najít. Tak se vydal na cestu._

_Bohové jeho pouť sledovali a bůh Veles se velice zlobil, protože ta bylina (bylo to obilí) patřila jemu a jen on znal její tajemství. Rostla přímo před vchodem do jeho podzemního království. Proto si stěžoval u ostatních bohů a Bůh času mu vyhověl a chlapec rázem_ _zestárnul. Chlapec netušil, jakou má cenu zaplatit za svou opovážlivost. Byl znetvořený přímo k nepoznání, byl změněný ve starce._

_Konečně dorazil na lán vlnících se zlatých bylin. Utrhl jeden klas a ochutnal. Bylo to sladké. Čím více jedl, tím více zapomínal na cestu domů. Sudička Štěstěna se nad ním slitovala a seslala mu sen, ve kterém spatřil svou milovanou dívku, jak hladoví. Vstal, natrhal tři tucty klasů a vydal se na zpáteční cestu přes hory a doly, lesy a louky._

_Putoval už rok, když uviděl v dáli svou vesničku. Rozhodl se, že si naposledy odpočine. Sedl si vedle studánky, naklonil se nad ní a nepoznal se. Hořce zaplakal nad svým vzhledem. Štěstěna ho však neopustila. Přemluvila Kikimoru, která ráda ubližovala mužům a ještě raději_ _ženám, že když toho starce promění v chlapce, učiní nešťastnými najednou dvě ženy: ženu starce, jehož podobu na sebe chlapec vzal, i dívčinu, která si ho s milým splete. Kikimora nadšeně omámila chlapce svým dechem, a když se probral, všechno stáří bylo pryč._

_S radostí se vrátil mezi své drahé a ti začali zrna zasévat, pečovat o ně, mleli z nich mouku a pekli chléb. A chlapec dostal jméno Sláv._
