== Svátky

Svátky jsou v podstatě spojeny s přírodními jevy a s vírou, jak si je lidé vysvětlovali. Např. staří Římané v květnu slavívali Lemurie – svátek usmíření škodlivých démonů a duchy mrtvých.

**Staří seveřané** věřili, že v předvečer 1. listopadu duše zemřelých přicházejí z podsvětí (helheim) na zem, aby škodili lidem, zvířatům a polím. Aby je živí usmířili, kladli na hroby světla a jídlo.

*Keltové* slavili _*Samain*_ (Samhain) v noci z 31. října na 1.listopad, který značil počátek zimy a keltský nový rok. Byl časem rituálního truchlení za smrt léta a nebezpečným obdobím, kdy se dočasně zastavil čas i prostor a přestaly platit přírodní zákonitosti. Prolomily se bariéry, duchové z Onoho světa mohli chodit po zemském povrchu a lidé mohli navštívit podsvětí. Černý bůh Samain nastupuje svou vládu. Je to lovec a bojovník. Zabil slunečního jelena, aby mu uloupil jeho ženu, zavlekl ji do podzemí a tam vládne jako bohyně smrti Morrigan. Stará se o duše zemřelých, o spící semena a o zvířata. Zimní král Samain se zdobí věčně zelenou jedlí, jmelím a cesmínou.

O Samainu bylo zvykem prostírat u večeře i pro zesnulé příbuzné, u kterých se předpokládalo, že přijdou rodinu navštívit. Dalším zvykem bylo vystavovat za oknem zapálenou svíčku, často ve vyřezané řepě, která měla bloudícím duším mrtvých posvítit na jejich cestu. Lidé se také převlékali do starých cárů a malovali si obličeje, aby se uchránili před zlými duchy.

V *Anglii a USA* se tradice Samainu přežila do současnosti a to díky irským přistěhovalcům. Slaví se jako _*Halloween*_, kdy v noci přilétají v tělesné podobě duchové zemřelých a čarodějnice a chrlí na zem jedovaté sliny. Proto lidé dělají velký hluk, aby je zahnali a maskují se, aby nebyli jimi poznáni.

Tento svátek se tedy spíše spojuje s nadpřirozenými silami a je považován za nejstrašidelnější den v roce. Jeho typickou ozdobou jsou prořezávané dýně se svíčkou uvnitř. Tento zvyk má původ v irské legendě o opilci, šprýmaři a darebákovi Jackovi. _Jack za svého života velice hřešil a podvedl i samotného ďábla. Tomu slíbil za skleničku alkoholu svou duši. Žádal, aby ďábel vylezl na jabloň a potom rychle do jejího kmene vyřezal kříž. A ďábel nemohl slézt ze stromu. Jack mu řekl, že ho ze stromu dostane, když mu slíbí, že ho nikdy neodnese do pekla._

Když zemřel, odmítli ho v nebi i v pekle. Proto bloudí po světě a temnotu si ozařuje jediným žhavým uhlíkem, který mu ďábel ponechal. Aby mu uhlík co nejdéle vydržel, vložil si ho do vydlabané dýně (dříve řepy).

**Křesťanská** církev později zavedla svátek Všech svatých (1.listopad) a _*Dušiček*_ (2. listopad). Hroby se zdobí květinami, v některých zemích vyzvánějí zvony, u nás se zapalují svíce na hrobech i v domácnostech a to vše proto, abychom si připomněli své zemřelé.

Dříve se věřilo, že v tento den mohly duše vystupovat z očistce. Živým buď pomáhaly, nebo se jím mstily a to podle toho, jak se k nim chovali za jejich života. Lidé věřili, že nádoby se studeným mlékem a máslo, které pro ně nachystali, mohou ochladit a ošetřit spáleniny od ohně způsobené v očistci. U nás se také věřilo, že o půlnoci mají duchové zemřelých na hřbitově, kde jsou kaple, mši. Živý člověk se tam nesměl objevit, v tom případě ho duchové roztrhali na kousky.

Na **Islandu** věřili, že o novoroční noci navštěvují mrtví živé a proto byli slavnostně vítání (jídlo, postel). Příštího rána byla březovým proutím vymetena všechna zákoutí domu, aby duchové odešli.

**Staří Slované** obětovávali 1. listopadu bohu Kaščejovi (jeden z projevu Černoboga, dalšími jsou Dij a Nij), pána zla, chaosu a podzemního království Nav. Smrti (syna Morany a Kaščeje) je zasvěcený 2. listopad, kdy se zapalovaly ohně na hrobech předků. Smrti je totiž zasvěcen plamen svíčky nebo lampy, který symbolizuje duši, ducha a vědomí.

Slované udržovali vzpomínky na zesnulé zvláštními rituály. V určitých dnech přinášeli na hroby potravu a před důležitými rozhodnutími s mrtvými hovořili.

Motiv mít v úctě mrtvé a zejména jejich poslední přání nacházíme často ve slovanských pohádkách. Základním schématem je umírající otec, který žádá své tři syny, aby každý jednu noc hlídal na jeho hrobě. Synové mu to slíbí, ale nakonec přemluví nejmladšího, který je považovaný za hlupáčka, aby místo nich hlídal. Nejmladší si tak vyslouží od ducha mrtvého otce každou noc jednoho skvělého koně (burka, tátoš), pomocí kterých pak získá princeznu.
