== Představy o posmrtném životě

Významnou roli v historii lidstva hrál kult uctívání předků. Dříve pozůstalí dávali mrtvému dary, které mu posloužily v posmrtné existenci. Mrtví byli a jsou pohřbívání často s vírou v posmrtný život, vzkříšení. Mrtví byli a jsou spalováni na hranicích nebo byli ponecháni napospas dravcům např. ve věži mlčení. To mimo jiné znemožňovalo nebožtíkův návrat na tento svět - zejména jako duch.

*Pohřební obřad* je ceremoniál posledního rozloučení se zemřelým. Vyjadřoval formu *PŘEDSTAVY O POSMRTNÉM ŽIVOTĚ.*

Lidé zpočátku žili v přírodě, byli její součástí a byli na ni závislí. Proto se snažili ji porozumět, pochopit a předvídat a tím ovládnout. Protože byli její součástí, vše v přírodě vnímali jako živé bytosti. Sice odlišné, ale živé (stromy, řeky, hory atd.).

To, co se kolem nich dělo (vítr, bouře, sucho, déšť, záplavy atd.) se snažili vysvětlit jako činnost nadpřirozených bytostí (bohové, dryády, permoníci, vodníci, bludičky apod.). Protože byli na přírodě závislí, snažili se tyto nadpřirozené bytosti získat na svou stranu a odvrátit od sebe jejich případný hněv či mstu (magické přivolávání deště, pohřební obřady, nelovení totemového zvířete, poděkování za dobrý úlovek apod.).

Prožívali každoročně probíhající cykly v přírodě (jaro, léto, podzim, zima) a ty se také snažili vysvětlit.

Vysvětlovat to, co se kolem nás děje, je v podstatě přirozeným chováním člověka. Tím, že si něco vysvětlí, se domnívá, že tomu porozuměl a nemusí se toho už tolik obávat, protože to ztratilo punc neznámého, tajemného (dnes hledáme svou „jistotu“ ve vědeckém vysvětlení jevů). A myslí si, že to může ovládat, dostat pod kontrolu.

Lze říci, že ve všech kulturách zimní období bylo vnímáno jako spánek, smrt nebo odchod do podzemí některého z božských bytostí, která se pak na jaře probouzí, či vrací na zem nebo znovuzrodí, bojují s bohem/bohyní zimy a smrti (Persefona, Proserpina, Jarilo, Jurja, Jarun, Eostra apod.).

Podle tibetského učení je smrt a vše co následuje bezprostředně po ní nejvýznamnějším prožitkem a zkušeností celého lidského života. Ve většině kultur panuje víra, že smrt je jen přechodem do jiné formy života, znovuzrození. Mrtvému na této pouti poskytovaly úspěšnou pomoc tzv. *knihy mrtvých.* Obsahovaly poučení, kudy se má duše ubírat, co znamenají úkazy, s nimiž se postupně setkává, a jak má na ně reagovat. Smyslem je, aby se duše na své cestě správně orientovala. Předčítání knihy mrtvých ale také sloužilo k poučení živých, aby se o umírání a přechodu na druhou stranu dozvěděli co nejvíce.

_Tibetská kniha mrtvých_ (pevně daný text sepsaný koncem 8. st. po Kristu) je předčítána zesnulým 49 dní. Po této době si duše v našem hmotném světě nalezne jinou tělesnou schránku a inkarnuje (převtělí) se do ní. Pokud to dopadne ideálně, duše se dočká osvícení a nebude se už muset inkarnovat.

_Egyptskou knihou mrtvých_ dnes označujeme sbírku různorodých textů jako přísloví, modlitby, hymny apod., které vznikaly v průběhu tisíců let. Vkládaly se do hrobů. Pokud si někdo nechával vyhotovit „knihu mrtvých", pak písař vybral pasáže, které by byly pro zákazníka nejvhodnější. V knize mrtvých bylo obsaženo všechno, co člověk potřeboval, aby se dostal do říše smrti. Číhala na něj různá nebezpečí, např. podsvětní bytosti, které se chtěly zmocnit jeho duše. Mrtvý je mohl zkrotit, pokud znal a správně vyslovil jejich jméno. Ta se dozvěděl z knihy mrtvých.

Faraonům byly určeny „podsvětní knihy", které popisovaly nebezpečnou plavbu slunečního boha Re podsvětím.

Pro Egypťany bylo důležité „oživnutí na onom světě". Po splnění všech podmínek se stával „blaženým zesnulým".

V pohádkách a mýtech se setkáváme se situací, kdy se hrdina/ka musí vydat do **zásvětí** - místo za světem živých. Není to svět zemřelých. Je to místo přerodu duše. Jen tam může hrdina/ka získat to, co potřebuje. Žije tam Baba Jaga. Je charakteristické, že její domek nemívá okna ani dveří, bývá na kuří nožce a kolem něho je plot, kde na kůlech jsou napíchnuty hlavy těch, co neuspěli (a v důsledku toho v reálném životě "ztratili hlavu"). U ní musí hrdina sloužit a vysloužit si např. nejrychlejšího koně na světě, aby mohl získat zpět svou unesenou manželku.

Do zásvětí nevede žádná cesta a hrdina se tam dostává dlouhým putováním, jeskyní, či za pomocí nadpřirozených sil (např. Slunce, Měsíc, Vítr, rada vědmy). Studánky a studny jsou v pohádkách místem, kterými se může hrdina také dostat do zásvětí. V nich se totiž shromažďuje podzemní voda a pramen je přechodem, který je v lidových bájích znám jako studna dětiček. Přebývají tam nenarozené děti a také mrtví. Pramen je spojením s říši mrtvých.

Pobyt v zásvětí je velmi hlubokou zkušeností, proto moudrost a vědění souvisí také s pramenem, studnou, hlubinou (např. Ódin sestoupil do hlubiny pramene k Mimirovi, a aby získal moudrost).

Hrdina se na onen svět může také dostat skokem do studny, jak je to v pohádce bratří Grimmů Paní Zima/Frau Holle (další postava, která dlí v zásvětí a podrobuje jedince zkoušce a podle toho, jak u ní uspěli, je odměňuje).

_Žila jedna vdova se dvěma dcerami. Ta vlastní byla ošklivá a líná, nevlastní pilná a krásná. Vdova nevlastní dceru neměla ráda a chtěla se ji zbavit. Neustále ji dávala mnoho práce a nutila ji každý den u studny příst, až dívce z prstů tekla krev. Jednou svou krví zamazala přadeno, a když se sklonila nad studní, že ho ve vodě vypere, přadeno ji do studny spadlo. Macecha ji přikázala, aby do studny pro přadeno skočila. Dívka tedy zavřela oči a skočila. Ztratila vědomí a když přišla k sobě, viděla, že leží na nádherné louce._

_Vydala se přes louku. Uviděla pec plnou upečeného chleba. Pec ji prosila, aby je vytáhla a dívka tak učinila. Pak přišla k jabloni obsypanou jablíčky a na prosbu jabloně ty jablíčka setřásla. Nakonec došla k chaloupce, ze které vyhlížela stařena, která měla veliké zuby. Dívka se ji velice lekla a pocítila úzkost. Ale stařena ji nabídla, aby u ni zůstala, starala se o domeček a pořádně natřásala peřiny, aby na světě krásně sněžilo. Dívka se velice snažila a Paní Zima s ní byla spokojená._

_Po čase se dívce zastesklo po domově. Paní Zima ji vrátila přadeno a dovedla ji k bráně. Když dívka bránou procházela, padal na ni zlatý déšť a celou ji pozlatil._

_Macecha si přála, aby i její dceru potkalo takové štěstí. Její dcera hodila vřeteno do studny a skočila za ním. Také se ocitla na krásné louce, ale peci ani jabloni neulevila. Ve službě u Paní Zimy byla líná, všechno dělala nepořádně. Také ji zavedla Paní Zima pod branou, ale místo zlata se na ni vylila černá smůla._

V zásvětí plyne čas jinak, než na zemi (plyne velmi rychle nebo velice pomalu). V zásvětí to, jak co vypadá, se nemusí jevit tím, co je ve skutečnosti. Např. hrdina, který si jde vysloužit nejrychlejšího koně dbá rady a vybírá si toho nejvychrtlejšího a nejslabšího, který se na zemi mění v nejrychlejšího tátoše. Přinesené zlato se na zemi mění v kámen ale odměna ve formě smetí a suchého listí se na zemi mění ve zlato.

V pověsti o blanických rytířích (symbol naděje v těžkých chvílích českého národa) _pozval neznámý rytíř kováře, aby mu okoval koně. Vstoupili bránou do Blanické hory, kde spali koně i rytíři. Když byl kovář s prací hotov, dostal jako odměnu pytel smetí, které v hněvu před horou vysypal. Doma se dozvěděl, že byl rok pryč a když se podíval do pytle, našel tam tři dukáty, které zbyly ze smetí. Když se vrátil k hoře, našel tam jen kopu smetí, kterou vysypal._

V keltské mytologii se hovoří __o boji mezi smrtelnými lidmi a Tuatha dé Danann (božské bytosti) o vládu. Ovšem lidské kovové zbraně božské bytosti zabíjí. Proto se odstěhovali ze světa lidí do vílích kopců zvaných Sídhe (jsou duté a v podstatě zásvětím) v Irsku a Skotsku. Toto zásvětí je mimočasové, obyvatelé jsou krásní a nestárnou. Přes tyto kopce mohou vstupovat do světa lidí a přivádět si lidi, kteří jim pak slouží...__

V irské báji Dar od Sidheů _požádala vědma Nano Hayes pasačku koz Noreen, aby ji půjčila její nejlepší kozu. Potřebuje kozí mléko pro velice nemocnou princeznu kouzelných bytostí. Noreen souhlasila s podmínkou, že ji stařenka vezme s sebou. Ta ji řekla, že nesmí nic jíst ani pít, když ji budou kouzelné bytosti něco nabízet. Má se vymluvit, že má ráda velice solené jídlo a tyto bytosti sůl nesnesou. A že pije jen ze železných pohárků, které taky nesnesou. Hlad a žízeň nebude pociťovat. Pokud něco ale sní nebo vypije, uvízne mezi kouzelnými bytostmi jako v pasti a nikdo ji nebude moci pomoci._

Dále ji řekla, že v noci sidheové vyjíždějí jako duchové na svých koních na svět a někdy chytají dívky a mládence, které si pak přivezou do svého světa, aby jim sloužili. A někdy také vymění moc hezké lidské miminko za své škaredé. Jako dospělí jsou nádhernými bytostmi, ale jejich miminka jsou škaredá a oni mají rádi jen krásné věci. A ještě ji upozornila, že čas zde plyne jinak, než lidem na zemi.

Po celých dvanáct týdnů každý den Noreen podojila kozu a princezna to mléko vypila. Když byla zdravá, mohla Noreen s vědmou odejít. Když se vrátili na zem Noreen zjistila, že byla pryč jen několik minut. Za svou službu obdržela od kouzelných bytostí čarovný váček se zlaťáky.

Podle psychologů cesta do zásvětí je symbolickým popisem psychického procesu individuace jedince. A jedině absolvování této cesty (symbolické setkání se smrtí) může završit proces individuace hrdiny ( podle C. G. Junga jedná se o vědomé vyrovnávání se se svým vnitřním středem – bytostným Já). Pozoruhodně tuto symbolickou cestu popsal a výstižně nazval J. R. R. Tolkien ve své fantasy knize Hobit aneb Cesta tam a zase zpátky.

Hrdina, který na své cestě „tam a zase zpátky" uspěje, se vnitřně změní - stává se sám sebou. Kdo selže, může být vnitřně poškozen, zmrzačen, tedy ne–celistvý. Z tohoto pohledu lze většinu pohádek vnímat jako vyprávění o cestách tam a zpátky.

Je nutné rozlišovat mezi individuaci a iniciačním rituálem. Iniciační rituál (zasvěcení) představuje rituální uvedení jedince do určité životní fáze (např. chlapec se stává mužem), situace (např. přijetí do tajného spolku), jiného postoje ke světu a smrti (např. mystéria).

S otázkou cesty duše na onen svět je také spojená otázka hodnocení/vážení lidské duše – jejich dobrých a zlých skutků. Představa o soudu na konci života je přítomná ve všech náboženstvích či kulturách. Potřeba spravedlnosti je v nás hluboce zakotvena. Známe dva druhy *posledního soudu*:

- ve významu apokalypsy (katastrofa, která svým rozsahem hrozí zničit celé lidstvo, svět) na konci všech věků, kdy v podstatě svět zaniká:
+
_Armagedon (křesťané)_ - místo závěrečné bitvy mezi Satanem (antikristem) a Hospodinem, kdy Boží vojsko povede Ježíš Kristus. Má vést k nastolení nového spravedlivého světa.
+
_Ragnarök_ (severská mytologie). poslední bitva mezi mocnostmi dobra a zla, konec světa a zánik bohů. Po něm povstane nový svět.

- ten na konci života každého jedince, kdy se váží jeho skutky.

Podle Tibeťanů (buddhismus) probíhá tento soud v poslední fázi stavu bardo (mezistav – fáze mezi smrtí v předešlém a znovuzrozením v novém životě), kdy se duše začíná připravovat na novou reinkarnaci. _Nejvyšším soudcem je král mrtvých Jama. V jeho službách jsou tisíce „pánů zesnulých" a ti k němu přivádějí mrtvé, Mrtví jsou od začátku pokládání za obžalované. Každý mrtvý má svého žalobce, který za každý hřích vytáhne z velkého pytle černý oblázek a položí jej na misku vah. Každý má i obhájce, který za každý dobrý skutek položí na protější misku vah bílý kámen. O osudu duše rozhodne to, která miska převáží._

Podle jiné legendy mrtvý vypráví sám o svém životě.

_Král mrtvých je zásadně nedůvěřivý. Proto se mrtvému po jeho výstupu předloží karmické zrcadlo. Zobrazují se v něm všechny činy zemřelého (obžalovaného)._ Zrcadlo má zde funkci jako v jiných náboženstvích kniha hříchů a dobrých skutků. Pokud převáží dobré skutky, znamená rozsudek pro duši nové zrození. Ním se přiblíží definitivnímu cíli – osvícení.

Tibeťané všechno spjaté s posledním soudem pokládají za psychický proces odehrávající se v nitru zesnulého. Peklo je odrazem vlastních duševních vlastností. Pekelné útrapy si způsobuje tedy každý sám.

V *Severní Americe* se obecně onen svět popisuje jako místo plné pokoje a štěstí, kde je nadbytek zvěře. Proto jej prérijní indiáni nazývají také Věčná loviště. Mnoho kmenů nezná podsvětí ani peklo. Po smrti se člověk odebere do duchovního světa a tam pokračuje v životě jako na zemi. Než se tam ale jeho duše dostane, musí překonat určité překážky, které se ji staví do cesty. Živí lidé se mohou do onoho světa také podívat a to po duze, nebo musí přejít bouřlivou řeku či jezero, vstoupit do jeskyně.

Indiánská pohádka Červená labuť hovoří _o třech bratřích, kterým po otci zůstaly tři kouzelné šípy. Odjivba, nejmladší, jednou použil všechny tři šípy, aby střelil červenou labuť. Dva šípy se minuly, třetí labuť zasáhl a Odjivba se vydal labuť hledat. Nakonec ji našel. Byla to sestra kouzelníka. Musel splnit úkol, aby dívku získal. Na zpáteční cestě se mu podařilo získat dvě dívky jako manželky pro jeho bratry._

_Bratři mu ale začali závidět a chtěli, aby jim vrátil dva šípy po otci. Odjivba se rozhněval a rozhodl se vydat za zemřelým otcem, aby při rozsoudil. Putoval dlouho, až přišel k jeskyni. Tou sestoupil do obydlí zemřelých. Země tam byla krásná, bylo tam mnoho rozličných zvířat. Spatřil buvoly a ti mluvili lidskou řečí. Svěřil se jim. Vůdce buvolů mu řekl, že jelikož je živý, otce nenajde. Má se však vrátit domů, protože zde_ _nesmí zůstat dlouho. Odjivba najednou uviděl jasné světlo. A buvol mu řekl, že je to obydlí dobrých. Když se ptal na černý mrak, buvol mu řekl, že se nemá ptát. Odjivba se za pomocí svých strážných duchů dostal na zem. A oběma šípy své bratry zastřelil._

*Čipevajové *(Kanada) si vypráví tento mýtus o světě Duchů: _Šaman se trápil, protože mu nedávno zemřela jediná dcera. Svým přátelům sdělil, že se rozhodl jít do světa Duchů za svou dcerou, aby ji přivedl zpět. Pět mužů se rozhodlo jít s ním._

_Nejprve museli vyhledat Vinaboja, který byl Manitu, protože jen on jim mohl ukázat cestu. Šaman se odebral k hrobům svých předků, vyvolal jejich duchy a ti mu řekli, kde ho najde. Vinaboja opravdu našli a ten jim ukázal cestu do země Duchů. Upozornil je na nebezpečí, které na ně číhají. Dal každému náhrdelník a důrazně je upozornil, že ho nemají sundávat z krku a že v zemi Duchů mohou pobýt jen čtyři dny a čtyři noci. Duchové vycházejí až v noci, shromáždí se v největším stanu a tančí. Mají si sednout mezi ně a až se objeví dívka, kterou šaman hledá, má ji chytnout, schovat do pytle a nepustit ven, dokud se nevrátí do světa lidí._

Když šaman s přáteli přišel do země Duchů, našli největší stan a v noci do něj vstoupili. Duchové tančili, děvče se však neobjevilo. Druhá noc probíhala stejně a také třetí. Jeden z Indiánů přestal dbát na radu Vinaboja a náhrdelník si sundal. Namístě se proměnil v Ducha.

Čtvrtou noc si šaman všiml ženy se zahalenou tváří. Podle způsobu chůze poznal, že je to jeho dcera. Skočil k ní a za pomocí přátel, i když se bránila, ji vstrčil do pytle, který pevně svázal. Cestou nazpět se stavili u Vinaboja, který jim řekl, aby každou noc dobře pytel ukryli a dbali, aby byl pevně zavázaný a neotvírali ho.

__Když přišli do vesnice, šaman čekal, co se bude dít. Zanedlouho uslyšel hlas své dcery, která ho volala, aby ji osvobodil. Když pytel rozvázal, stále před ním jeho dcera živá a zdravá. K životu ji vzkřísila otcovská láska__.

Kmen Indiánů **Mapučé **__(Chile) si vypráví, že Threngthreng při velké potopě zachránil lidi na hoře Stvoření. Protože je naučil všem dovednostem, říkají mu Čau Uentru, dobrý otec. A ten je také pánem nad čluny duchů, které přepravují duše zemřelých na ostrov mrtvých. Na té dlouhé cestě je vždy nechá nějaký čas odpočinout na Stříbrném moři, než je uvede do druhého života, kde je věčná pohoda a slavnosti.__

Těla nebožtíků se úplně rozpadnou, jejich duše však žijí dál na onom světě.

*Tahitská pohádka* Létající ryba _vypráví o mladém bojovníkovi Oroovi, který se rozhodl přinést kouzelný kámen z říše mrtvých, aby získal ruku krásné Maevy, dceři náčelníka._

_Kouzelník mu poradil, aby nejdříve ze dna moře přinesl perly na dlouhý náhrdelník. Když tento úkol splnil, řekl mu, aby se podíval na noční oblohu vyvrtanými otvory v kokosovém ořechu. Spatří hvězdu, která ho povede na jeho cestě daleko za obzor, kde zapadá slunce. Až dopluje na konec světa, uvidí skálu, která ční z moře. Skálu podplave a pak se ocitne v říši mrtvých. Ještě ho upozornil, že také bojovník Athi chce přinést Maevě kouzelný kámen z říše mrtvých. To Oroa hodně nahněvalo. A tak co nejrychleji vyplul na moře._

_Po obtížné plavbě se dostal ke skále, podplaval ji a ocitl se v krásné zátoce. Tam ležela obrovská ryba s modrými a zlatými šupinami a s křídly místo ploutví. Oroa se ji poklonil. Pochopil, že je tu strážcem._

_“Proč přicházíš, když jsi živý? Sem mohou jen ti, kteří si svým dobrým životem zaslouží štěstí po smrti.“ řekla ryba. Oroa se ji svěřil. „Můžeš získat kouzelný kámen, když se přede mnou třikrát pokoříš a třikrát mi řekneš laskavá slova.“ řekla ryba. Nejdříve se proměnila v škaredého kraba, pak v ohyzdnou medúzu. Oběma se Orea poklonil a řekl jim, co je na nich krásné. Když se však ryba proměnila v Athiho, zapomněl, že jde o zkoušku, vzkypěla v něm nenávist a zvolal: „Nikdy se před tebou neskloním, Athi!“_

Najednou se Athi proměnil v rybu. “Nedokázal jsi zlomit svou pýchu.“ řekla mu, „nemáš právo na kouzelný kámen a abys nemohl vyprávět, cos v říši mrtvých viděl, staneš se rybou.“

Orea se do vsi nikdy nevrátil. Maeva nosí na jeho památku dlouhý perlový náhrdelník. Nevrátil se ani Athi.

*Japonský* mýtus o božském páru, který tvořila bohyně Izanami a bůh Izanagi, vypráví o tom, jak _Izanami zemřela při porodu, když se ji narodil kami (bůh) ohně. Izanagi byl zoufalý a proto vstoupil do království mrtvých - Jomi. Setkal se zde se svou Izanami, ale ta mu řekla, že již ochutnala zdejší pokrm a proto se k němu nemůže vrátit._

_Rozhodla se však poprosit boha, který zde vládl, aby ji přesto propustil. Bůh souhlasil. Jeho podmínkou bylo, že se na ni Izanagi po celou tu dobu, co budou v Jomi, nesmí podívat. Při zpáteční cestě z Jomi, se Izanagi přeci jen na milovanou ženu podíval. Ta se ihned změnila ve strašného démona. Izanagi utíkal, protože ho začalo pronásledovat osm bohů hromu a bojovníci z Jomi. Podařilo se mu je odehnat třemi kouzelnými broskvemi, které utrhl po cestě. Zachránil se, ale navždy ztratil svou Izanami._

Věřilo se, že duše toho, kdo nebyl řádně pohřben, bloudila mezi světem živých a mrtvých a tím škodila sobě i lidem. Zjednodušeně se dá říci, že zvyk pohřbívat mrtvé je běžný zejména ve společnosti, která vyznává vzkříšení těla a tam, kde se preferuje kremace, je tato symbolem očištění, přeměny a nanebevstoupení. Často se vše spalovalo proto, aby se zničil zdroj nákazy, nečistoty.

Spalování těla má své kořeny v zápalných obětech (i lidských), které se předkládaly bohům. Zde hrál významnou úlohu stoupající dým, který přinášel dotyčnému bohu spalovanou oběť přímo a velice rychle. Oheň byl totiž vnímán jako posvátný živel, který dodává obětem nesmrtelnost. Tak např. Héra (manželka Dia) slíbila Médei, že její děti učiní nesmrtelnými, když je položí na obětní oltář v jejím chrámu. Médea tak učinila.

Spalování zemřelého mělo další význam - dostat se co nejdříve ke svému bohu. Např. mýtičtí hrdinové byli velice často spalování na hranici s přesvědčením, že duše těch, kteří byli božstvem vyvoleni, při procesu hoření jsou z hranice odvezeni příslušným bohem na Olymp (např. Héraklés, který se později stal dveřníkem, strážcem brány na Olympu).

Jiný význam mělo upalování v křesťanství (např. čarodějnic) a v židovském náboženství (např. za smilstvo). Zde se jedná o trest.

V **severské mytologii** byly různé možnosti života po smrti. Hrdinové padlí v boji odcházeli do Ódinovy Valhally (síň padlých v boji), zejména ti, co zemřeli jeho zbraní – oštěpem. Smrt v boji byla považována za velice čestnou. Šlechtic, který umíral doma, se nechal probodnout oštěpem, aby se mohl dostat do Valhally.

K bohyni Freyji přicházely zemřelé ženy a část padlých bojovníků, bohyni Gefion patřily zemřelé neprovdané ženy a dívky a do podsvětí Helu k Hel odcházeli ti, co zemřeli na nemoc, při nehodě nebo stářím. Bylo to nehostinné místo. Vodnaté, vlhké, dešťové, zamlžené. Proto je také označováno jako Niflheim (nifl = mlha)

Věřilo se, že se lidé znovu rodí (např. jedna sága z Eddy uvádí, že Helgi a Sigrún se znovu narodili jako Helgi a Kára). Také se věřilo, že slovo umírajícího má velkou moc. Proto se každý obával kletby umírajícího.

Čím více darů a služebníků bylo nebožtíkovi obětováno, tím si mohl zemřelý v příštím životě více užívat majetku.

Staří Germané dávali mrtvému do hrobu na levou nohu speciální botu (střevíc mrtvého).Tento obyčej souvisel s bohem Wodanem (Ódin), který zvítězil nad vlkem Fenrisem tak, že mu do chřtánu vstrčil levou botu a roztrhal ho na půl.

Fylgja byla neviditelná bytost, která doprovázela každého člověka a pomáhala mu. Dovedla se odpoutat od těla a ukázat se jiným, často ve zvířecí podobě. Obyčejně před smrtí toho, komu se zjevila. Jedinec mohl mít i několik fylgjí.

*Keltové* věřili, že po smrti přejde duše z jednoho těla do druhého. Vnímali smrt jako přerušení dlouhého života, jako etapu mezi dvěma životy. Jejich víra ve znovuzrození byla tak pevná, že placení dluhů bylo odkládáno na setkání na onom světě a válečníci se nebáli smrti. Existují příběhy o nerozlučných, osudových milencích, kteří se znovu setkávají po své smrti tak, že se znovu narodí v jiných tělech. Keltové ctili kult předků. Byli pro ně živí, kteří jen odešli ze zemi lidí.

Měli konkrétní představu Onoho světa (Annwfn nebo Annwn). Šťastný Onen svět je podobný zemskému světu, ale mnohem lepší. Neexistuje v něm bolest, choroby, stárnutí, je plný světla, hudby, oslav.

V mýtech, zejména zasažených křesťanstvím, se objevuje druhý aspekt Onoho světa, který je v ostrém kontrastu: pochmurné místo plné nebezpečí. Pro živého návštěvníka je velmi ohrožující.

V *Irské* mytologii je Onen svět (Tir na nÓg) místo, kde neexistuje čas ani věk. Tedy země věčného mládí, moudrosti, krásy, harmonie, nesmrtelnosti. Zde neplatí pozemský čas. Pokud jej navštíví živí lidé, zůstanou mladí, ale když se vrátí domů, pozemský věk je dožene.

Nejznámější je příběh O Oisínovi, __kterého odvedla na západ do Země mládí krásná Niam Zlatovlasá. Žil tam šťastně tři sta let. On si však myslel, že uběhly jen tři roky. Zastesklo se mu po domově a rozhodl se navštívit rodné Irsko. Niam ho varovala, aby se nedotkl nohou země, jinak se k ní nebude moci vrátit.__

Oisín nasedl na koně. V Irsku ale nic a nikoho nepoznával. Seskočil z koně a najednou se z něho stal vetchý stařec, který se rozpadl na prach.

Onen svět se mohl nacházet na západních ostrovech, pod mořskou hladinou, v podzemí, v pahorcích zvaných sidhe.

Symbolem znovuzrození byl zejména „kotel znovuzrození“, ale také hadi, opadavé stromy - na zimu umíraly, na jaře se opět pokryly listím a květy a rodily ovoce.

**Finská** říše mrtvých Tuonela (někdy Manala) bylo nehostinné místo. Zemřelé zde přiváděl bůh mrtvých Tuoni, zahaloval je do svého pláště a poskytl jim rukavice. Od světa lidí ji oddělovala černá Tuonelská řeka. Na břehu stařec se železnými drápy a železnou sítí hlídá, aby se mrtví nemohli vrátit mezi živé. Přesto se to několika lidem podařilo.

_Mladík Lemminkäinen byl zabit čarodějem když se ucházel o dceru čarodějnice. Jeho matka byla také čarodějnice a svého syna navrátila životu tím, že části jeho mrtvého těla vylovila magickými hráběmi, zaříkáváním a mastmi je spojila, a víla mu vdechla život._

*Sumerský* mýtus popisuje _sestup bohyně Inanny/Ištar (bohyně lásky, plodnosti, války) do podsvětí, kde je královnou její sestra Ereškigal. Je to místo, ze které není návratu, je temné a ponuré. Hraniční řekou podsvětí je Hubur. Zemřelý, který se ocitá v podzemí, se stává Gidim, duchem. Duše zemřelého sestupuje do podsvětí sedmi branami. Hlavním strážcem podsvětí je Neti. _

_Bohyně prochází sedmi branami a u každé je zbavena symbolu svého božství (koruna, šaty, prsteny apod.). Když se ptá proč se tak děje, odpovědí je, aby se neptala na rituály podsvětí. Nakonec nahá předstupuje před svou sestru a Anunnaki ( sedm soudců z podsvětí). Ti nad ní vyslovili svůj soud - upřeli na ni své oči smrti a na jejich slovo se proměnila v nemocnou ženu a mrtvé tělo. To pověsili na kůl._

_Bůh Enki (pán podzemní říše sladkých vod) se postaral o její propuštění. Poslal do podsvětí dvě bytosti s chlebem života a živou vodou. Ereškigal byla nemocná. Tyto bytosti ji vyléčili a jako odměnu si vyžádali tělo Inanny. Té pak podali chléb života a živou vodu. Inanna za propuštění zaplatí tím, že za sebe jako náhradu vydá Dumuziho, svého manžela._

Dle představy *Peršanů* člověka tvoří dvě podstaty: podstata duchovní (urván) a tělesná. Duchovní část člověka přežívá tělesnou smrt. Po smrti se s duší zachází podle toho, jaký byl život dotyčného. Svět je totiž neustálá konfrontace mezi dobrem a zlem. Člověk má svobodnou vůli a záleží jen na něm, kterou cestu si vybere.

Duše setrvává u svého těla tři dny a recituje Ghátu (texty připisované Zarathuštrovi). K duši jedinců, kteří se rozhodli žít podle principu dobra, připluje vonný vítr představující Deané, mladou krásnou dívku. Ta doprovází duši do říši spravedlivých. Duše stoupá k nebi přes tři nebeské sféry (hvězd, měsíce, slunce) až do sféry světla nemajícího počátek. Tyto duše pak mohou spočinout po boku Ahury Mazdy a ostatních spravedlivých. Toto místo představuje ráj.

Duši člověka, která nesmí vstoupit do říše spravedlivých, doprovází ošklivá babice do pekla, hrozné jámy, plné hrůzy, děsu, zla a utrpení.

Tyto dvě bytosti představují svědomí člověka a na jejich vzhledu se odráží lidské zlé či dobré skutky.

Duše se od sebe oddělují na Mostě rozlišení, který se nachází na vrcholku kosmické hory ve středu světa a je spojnicí mezi nebem a zemí. Dochází k soudu duší, kterého se účastní Mithra, Sraoša a Rašnu, který má k dispozici váhy. Duše jsou děleny podle míry dobra a zla, které během života vykonaly. Pokud tato míra je poloviční, i míra blaženosti a utrpení se stane poloviční.

V islámském lidovém prostředí je rozšířena představa o výslechu duše, kterou vedou černí modroocí andělé Munkar a Nakír. Když je tělo pochováno do hrobu, tito andělé zjišťují, zda jde o věřícího či nevěřícího. Nevěřící bude trpět věčným trestem.

Důležitým mýtem *muslimských Arabů Severní Arábie* je vyprávění o stvoření světa. Bůh zemi vytvaroval do sedmi vrstev, sedmi zemí a umístil je nad sebou. Vzdálenost mezi jednotlivými zeměmi je veliká – člověk by ji ušel za pět se roků.

První zemi Bůh osídlil džiny, lidmi, zvířaty. Druhá je domovem větrů. Třetí obývají zbožní tvorové. Čtvrtá země je peklem pro duše hříšných lidí. Pátá země je domovem obřích škorpiónů a hadů pekla. Šestou zemi Bůh určil pro zatracené duše. Sedmá země je položena nejníže a je domovem Iblíse, hlavního Ďábla a jeho zlých džinů. Zde neustále dují hořící větry a mrazivé vichry.

Bůh poté z oblohy uhnětl sedm vrstev, sedm nebes. Vzdálenost mezi nimi je obdobná vzdálenosti mezi zeměmi.

První nebesa Bůh stvořil z vodních par a z mlhy. Obklopují první zemi, kterou bůh osídlil lidmi a džiny. Obývají ji andělé, které Bůh stvořil z ohně a větru. Anděla hromu ustanovil jejich velitelem. Na nebesa zavěsil hvězdy, planety, slunce a měsíc.

Druhá až šestá nebesa nebesa Bůh vytvaroval z různých materiálů a osídlil je anděly a cherubíny.

Sedmá nebesa obývají nejvýše postavení andělé. Každý z nich je jedinečný, jejich křídla září různými barvami, jsou ohromně velká. Nejvyšší anděl je Duch (al-Rúh) a čtyři archandělé: Džibrá’íl, Miká′íl, Isráfíl a anděl Smrti. Mají kosmické rozměry.

Sedmá nebesa jsou také místem ráje (džanna) pro spravedlivé lidi. Jsou zde Zahrady slasti, kterými protékají řeky s průzračnou čistou vodou. Spravedliví budou sedět na březích ve stínech stromů oblečeni v nádherné šaty a oblažování věčně mladými pannami (huriskami). Duše budou jíst ovoce a pít vodu z rajského pramene nebo víno, které jim nalijí rajští chlapci. Nad sedmým nebem se vznáší obrovský žhnoucí oblak a nad ním se tyčí Boží Trůn. Podpírají ho čtyři vysoce postavení andělé . První má podobu člověka, další býka, sokola, lva.

Bůh stvořil ze světla anděly. Jsou to éterické a inteligentní bytosti, pro lidské oči neviditelní, dokáží se však v cokoli proměnit. Nikdy jimi necloumají emoce, nehřeší, poslouchají a uctívají Boha, k němuž se neustále modlí.

Mezi nejvýznamnější patří Duch (al-Rúh). Jemu Bůh svěřil do péče duše všech bytostí a tvorů. Jeho ústa každým dechem vydechnou duši každého zrozeného tvora.

Archanděl Miká′íl obdařuje lidské duše vědomostmi, moudrostí a touhou dosáhnout dokonalosti.

Archanděl Isráfíl pečuje o posvátnou Knihu, do které Pero zapisuje všechna Boží rozhodnutí. Je mu také svěřena Trumpeta vzkříšení. V jejích prostorách pobývají duše mrtvých lidí. Čekají na chvíli, kdy Bůh Isráfílovi přikáže, aby na ni třikrát zatroubil. První zatroubení je zatroubení strachu, druhé posledního soudu a konce světa, třetí vzkříšení. Pak nastane soud. Andělé na váhách zváží skutky každé duše a Bůh vyřkne svůj soud. Duše, jejichž miska dobrých skutků převáží, poputují do ráje.

Anděl Smrti, archanděl Isrá′íl, se nikdy neusměje. Je symbolem smutku. Sídlí v sedmém nebi. Hlavou se dotýká sloupů Božího Trůnu, jednou nohou spočívá na svém křesle, druhou stojí na mostě, který spojuje nebe s peklem. Je obklopen pomocníky, kteří plní jeho rozkazy. Nalevo od něho se tyčí vysoký strom, jehož listech jsou jména všech žijících lidí. Když člověk zemře, jeho jméno v Knize zčerná, list s jeho jménem na stromě zežloutne a spadne. Anděl Smrtí v té chvíli vezme do rukou dvoje kopí. První je kopí Boží milosti a druhé Božího hněvu. Pokud je umírající člověk spravedlivý, vytáhne mu duši z těla kopím milosti a pošle ji do sedmého nebe. Pokud je zlý a hříšný, vytáhne jeho duši kopím hněvu a pošle ji do sedmé země, kde se vaří a škvaří a čeká na soudný den.

Ve společenství andělských bytostí přebývají anděl ráje Radwán s krásnou a ušlechtilou tváří a anděl pekel Málik, stvořený ze zloby a pomstychtivosti. Nikdy se neusměje.

Kromě andělů stvořil Bůh z bezdýmového ohně džiny. Ti obývají první zemi. Dožívají se mnoho set let, ale jsou smrtelní. Mají nadpřirozené vlastnosti. Jako lidé přijímají potravu a rozmnožují se. A jako lidé se musí sami rozhodnout, zda budou zlí nebo dobří.

Každý člověk má svého strážného anděla, který ho ochraňuje a má také svého džina, který se ho neustále snaží svést.

*Řekové* mají několik mýtů o vstupu živého člověka do podsvětí (podsvětí nelze ztotožňovat s křesťanským peklem). Velmi známý je o Orfeovi a Eurydice. _Orfeus proslul svým zpěvem, který okouzloval lidi i zvířata. Velice miloval svou manželku Eurydiku. Jednou šlápla na zmiji, ta ji uštkla a Eurydika zemřela. Orfeus byl zdrcený žalem a nakonec se rozhodl jít do podsvětí a vyžádat si ji zpět._

Svým zpěvem okouzlil v podsvětí všechny, i vládce Háda a jeho ženu Persefonu. Hádes rozhodl, že si Eurydiku smí odvést na svět, ale Orfeus půjde první a nesmí se ohlédnout, dokud nepřijdou na svět. Orfeus to slíbil. Těsně před koncem strastiplné cesty ale začal pochybovat, zda Eurydika opravdu za ním kráčí, protože neslyšel žádné kroky, žádný dech. Ohlédl a jen zahlédl stín Eurydiky, který mu navždy zmizel.

*Řekové a Římané* chápali posmrtný život jako stínovou existenci v podsvětí (Hádes – země, ze které není návratu). V řecké mytologii je popisováno jako podzemní říše obklopená řekami Acherón (řeka Vzdechů), Styx (řeka Hrůzy), Léthé (řeka Zapomnění), Kokýtos (řeka Nářků), Pyriflegethón (řeka Ohně). Vládne ji Hádes, bůh s pláštěm a kapucí, jež ho činí neviditelným (v mýtech i pohádkách bývá kapuce symbolem neviditelnosti). Duše při vstupu do podsvětí projde kolem trojhlavého psa Kerbera, který hlídá, aby do říše mrtvých nevstoupil nikdo živý. Poté duši převeze převozník Charón za poplatek (obolos) přes řeku Acherón (Řekové kladli do úst mrtvému peníz, aby měl čím za převoz zaplatit). Na druhém břehu se duše napije z řeky Léthé (řeka Zapomnění) a zapomene na pozemský život. Pro velké hříšníky je určen strašlivý Tartaros a vyvolení vstupují do rajského Elysia a ti, co nebyli ani příliš dobří ani příliš zlí, jako stín bez těla pobývají na asfodelové louce.

Pobyt v podsvětí je věčným údělem vyvolených nebo zatracených. Ostatní tu pobývají jen určitou dobu – je to čas mezi dvěma pozemskými existencemi.

Ve starém **Egyptě** byl vládcem podsvětí Usir (řecky Osiris). Egyptské podsvětí leželo na západě, kde zapadá slunce. Vypadalo jako svět, ve kterém žili lidé, ale bylo větší, úrodnější, vládl tu mír. Každý pokračoval ve svém životě, jak ho žil na zemi, až na to, že nemusel pracovat. Měl na to služebníky (sošky v hrobech- vešebty). I zde mohl zemřít a to už byla smrt definitivní.

Původně byl tento svět umístěn do vesmíru a až později pod zem. Hvězdy byly „obyvatelé Duatu". Podle staré víry žili mrtví dále ve hvězdách. Přáním mnoha starých Egypťanů bylo, aby směli dále žít jako malá svítilnička mezi nočními hvězdami. Proto na rakve malovali ornamenty s hvězdami.

Každá duše mrtvého se musela dostavit před Usirův trůn. Cesta záhrobím, kterou musela duše zvládnout, byla plná nástrah a hrůz. Proto se do truhly zemřelého vkládal papyrusový svitek se zaklínadly, které měly zesnulému pomoci překonat cestu záhrobím. Pokud by ji nezvládl, zemřel by podruhé a to znamenalo navždy se rozplynout v temnotách. V těchto textech se hovoří o těle, srdci, jménu, stínu, ka, ba, ach zesnulého.

__Tělo:__ Tělesná připravenost pro zásvětí byla důležitá (schránka pro „duši“). Proto se tělu věnovala péče (mumifikace).

__Srdce__ představovalo zdroj myšlení a emocí. Proto bylo nositelem zodpovědnosti a svědomí. Bylo ponecháno v mumifikovaném těle. Před Usirovým trůnem se váží srdce zesnulého pomocí pera pravdy bohyně Maat.

Pokud je srdce lehčí než pero pravdy, je mu srdce navráceno a je mu umožněno zrodit se jako blažený zesnulý (ach). Duše může odejít do podsvětí Duatu. Mrtvý bude přijat mezi bohy a bude se moci nakrátko vracet na zemi. Má právo vstoupit do zahrad v Jalu. Už nikdy nepocítí hlad, žízeň a bolest. Může se procházet po nekonečných zelených lukách, nebo mezi třpytícími se hvězdami. Každý mrtvý se znovu ocitne v postavení, ve kterém žil před svou smrtí. Nikdy ho však nepostihne hmotný nedostatek, trápení a nepříjemnosti.

Pokud je srdce při vážení těžší než pírko pravdy, sežere ho nestvůra Amemait (Požíračka). Někteří jsou předání hrozivým duchům, kteří je budou mučit a potom je sežerou.

_Jméno_ vyjadřovalo podstatu nositele. Proto zesnulý na své pouti podsvětím překonával překážky tím, že je pojmenoval. Výrok „znám tvé jméno" má význam „mám nad tebou moc".

_Stín_ byl chápán jako symbol ochrany a bezpečí. Jeho oddělení znamenalo zkázu pro člověka.

_Ka_ je nositelem života. Rodí se spolu s člověkem a v okamžiku jeho smrti se od něj na okamžik odděluje. Ka se přenáší plozením z otce zejména na prvorozeného syna – Ka zůstává otci a zároveň se rodí v synovi. Smrt znamenala přerušení života. Ka se od těla odpoutá (přestane dodávat životodárnou sílu). Ka je věčná síla, duchovní podstata, základ fyzických a psychických sil a tak se po pohřebních obřadech se zemřelým opět spojí a člověk vstupuje do nového života v zásvětí.

__Ba__ znamenala božskou sílu („duše"), vznikala se zrozením člověka. Po smrti se spojí s jeho Ka.

_Ach_ (duch, blažený zemřelý) zastupuje jednu ze tří základních sfér moci, které byly tvořeny bohy, achu (plurál od ach) a žijícími lidmi. Nemateriální zdroj psychických a intelektuálních schopností člověka. Je komplexním posmrtným projevem lidské bytosti. Proto bylo velmi důležité, aby tělo zemřelého bylo správně mumifikováno a podle předpisů pohřbeno. Bylo důležité, aby pozůstalí přinášeli Ach zesnulého oběti v podobě jídla, nápojů, protože tím zajišťují zesnulému blaženou existenci v zásvětí. Ach zesnulého pak pečuje o své žijící potomky. Mezi živými a zemřelými tedy existoval velice úzký vztah vzájemné závislosti. Achu se zjevují na noční obloze v podobě hvězd.

V **Indii** védy (vycházejí z ústní tradice) učí, že každá bytost na tomto světě je nesmrtelnou duší, přebývající v pomíjivém těle. Jednotlivá duše (átman) je součástí božské povahy a propůjčuje tělu energii. Její snahou je užívat světa, a proto vstupuje do koloběhu znovuzrození (sansára). Duše opouští umírající tělo a znovu se narodí v jiném těle. Přechází z jednoho těla do druhého a prochází všemi živými formami, od hmyzu až k bohu. Existovala však také víra, že do mrtvého těla může vstoupit démon a pak se zdá, že mrtvý oživl. To byl jeden z důvodů, proč bylo nutné držet stráž u zemřelého, než byl spálen.

Pohádka **ásamského kmene Kukí** Věrná láska _vypráví o lásce mladíka jménem Ngámbang a dívce Thuithling. Jako děti si spolu hrávaly a jeden bez druhého nemohl být. Když vyrostli, bylo zřejmé, jak se mají rádi. Ovšem otec dívky se rozhodl, že si jeho dcera vezme mladíka ze vzdálené vesnice. Ngámbang a Thuithling byli zoufalí. I jejich matky prosily otce dívky, ať změní své rozhodnutí a dovolí Ngámbangovi a Thuithling, aby se vzali. Odmítl._

I když to bylo proti zvyklostem, Ngámbang dívku doprovázel do vesnice tchána. Bylo totiž zvykem, že nastávající snacha musela nejdříve v rodině svého ženicha pracovat, aby všichni viděli, jak je pracovitá. Oba mladí lidé se loučili u dvou vysokých bambusových stromů, které se k sobě neustále nakláněly. Thuithling požádala Ngámbanga, aby z každého bambusu uřízl jednu hůl s tím, že každý bude mít jednu hůl u sebe. Když bude Ngámbang vidět, že hůl, kterou bude mít u sebe, bude praskat, znamená to, že Thuithling onemocněla. A kdyby se hůl rozštípla odshora dolů, tak umřela.

Ngámbang se vrátil domů. Chodil jako tělo bez duše, s nikým nemluvil, přestal pít a jíst, jen držel v ruce bambusovou hůl a díval se na ni. Za několik dnů Ngámbang viděl, že hůl začala praskat a následujícího dne se rozštípla. Thuithling zemřela.

Když ji chtěli příbuzní v rakvi obléci, žádné šaty na jejím těle nedržely. Lidé si uvědomili, že k mrtvé doposud nepřišel její přítel Ngámbang. Zavolali ho a ten položil svůj šat na mrtvou dívku a šaty nespadly. Mohl se konat obřad.

Mužové chtěli rakev zvednou, ale ta byla jako z kamene. Musel přijít Ngámbang a ten zvedl mrtvou dívku a odnesl ji na připravenou hranici. Když lidé zapálili hranici, plameny se těla ani nedotkly. Lidé chtěli, aby hranici zapálil Ngámbang. Ale on to nechtěl udělat.

Přistoupil mrtvé a řekl jí: “Thuithling, pro lásku k tobě jsem porušil všechny zvyky, obětoval jsem své dobré jméno. Nyní je však čas, abys mne opravdu už opustila. Mrtví nepatří do světa živých.“ Tu uslyšel hlas své milé:“ Rozprostři na zem svůj šat, a co na něj padne, vezmi a zakopej na svém nejmilejším místě.“ Ngámbang tak učinil, a na jeho šat dopadlo srdce mrtvé Thuithling. Lidé zapálili hranici a tělo mrtvé shořelo na prach. Ngámbang srdce své milé zakopal na poli jejich rodičů, kde spolu jako děti nejraději sedávali.

Za několik dní na tom místě uprostřed pole vyrostl fíkovník a ten rostl tak, že jeho větve zastínily pole a úroda uschla. Otec mrtvé chtěl fíkovník vykopat, ale nikdo to nedokázal. Pochopil, že jedině Ngámbang toto dokáže. Museli ho o to požádat, jinak by umřeli hlady. Ngámbang fíkovník vykopal. Zbyla po něm obrovská a hluboká jáma.

_Ngámbang druhý den na dvoře zasadil malý keř, aby měl každý den květy a mohl je položit na památku své mrtvé milé na místo, kde pohřbil její srdce. Ale kdykoli keř nasadil na poupě, do rána se ztratilo. Rozhodl se v noci keř hlídat._

Po půl noci se vplížil do dvora divoký kocour a ulomil poupě. Ngámbang ho chytil a chystal se ho zabít. Tu kocour promluvil:“ Proč mi chceš ublížit? Trhám květy pro tu, pro niž jsi zasadil tento keř, a která je teď v říši mrtvých.“ Ngámbang požádal kocoura, ať ho k jeho milé zavede. Musel zavřít oči a chytit se kocoura za ocas a jít za ním. Než se rozednilo, byli v říši mrtvých.

_Najednou stáli před velkým palácem a se schodů scházela Thuithling. Padli si radostně do náručí, sedli si na schody a hovořili spolu. V říši mrtvých neplyne čas. Ale Ngámbang začal cítit jakousi malátnost a úzkost, jakoby mu na prsou ležel balvan. Thuithling mu řekla, že pozemské tělo v říši mrtvých jen překáží. Je velký div, že jako živý mohl přijít do říše mrtvých a proto ona ho vrací mezi živé. Když ji Ngámbang odmítl opustit, řekla mu, aby se vrátil a podíval se kolem sebe. Ať vidí, jak je život krásný. A kdyby se i potom rozhodl být s ní, ať zavolá její jméno._

Ngámbang se ocitl doma. Všichni ho radostně vítali. On ale vyšel před dům a hlasitě zavolal jméno své milé. Tu přilétl havran, usedl prudce na střechu domu, až kus dřeva sjel ze střechy a zabodl se do Ngámbangova srdce. Ngámbang padl mrtev k zemi a tak se vrátil ke své Thuithling a byli pak spolu věčně, protože v říši mrtvých čas neuplývá.

V *čínské* kultuře se odráží myšlenka koloběhu umírání a rození. V příběhu Vděčnost _se hovoří o služce pana Sie Sunga. Svěřila se mu, že ve svém předchozím životě byla mužem, který uměl zbavovat lidí nemocí a bolesti. Jednou však podal těhotné ženě, jejíž střeva byla napadena červy, víno s květy lýkovce. Žena i její dvě nenarozené děti zemřeli._

Soud podsvětí jej shledal vinným za tři zmařené lidské životy. Byl proto ve svém příštím životě poslán na svět jako děvče. Svou službou svému pánu odčinil své někdejší provinění a proto bude moci svou duši očistit pro věčný koloběh umírání a rození.

S myšlenkou převtělování se setkáváme také v našich pohádkách. Převtělování se netýkalo jen lidí, ale i zvířat.

Pohádka O hlupáčkovi: _Sedlák měl tři syny. Ti dva starší byli rozumní, uměli všechny práce kolem chalupy i na poli. Nejmladšímu říkali hlupáček, protože všechno pokazil, nebyl prostě k ničemu._

_Jednou se začaly sedlákovi ztrácet z pole brambory. Nejdříve šel hlídat pole nejstarší. Přišel za ním stařeček a prosil ho o několik brambor, že má hlad. Nejstarší syn ho napadl holí, že to on chodí krást jejích brambory. Ale se zlou se potázal. Sám dostal tolik ran, že se nemohl ani hýbat a velký kus pole byl zase vykopán a brambory byly pryč. Tak se dělo i druhorozenému a pak přišel na řadu nejmladší – hlupáček. Když ho stařeček poprosil o několik brambor, ochotně mu je dal a stařeček se mu odměnil. Podaroval ho křesadlem – když s ním křísne, splní se mu cokoli bude chtít._

Hlupáček se rozhodl vydat s křesadlem do světa. Přišel ke královi, který se chystal do války s mocným sousedem a sliboval, že ten, kdo pro něho tuto válku vyhraje, dostane za manželku princeznu a půl království. Hlupáček se přihlásil, vykřesal si vojsko a vyhrál. Z nepřátelského vojska zůstal naživu jen bílý koníček, kterého si hlupáček ponechal.

Ovšem král ani princezna nechtěli ani slyšet, že by měli splnit to, co slíbili. Všichni se na královském dvoře na hlupáčka mračili a posmívali se mu, jen komorná princezny se na něho mile dívala. Král se s princeznou rozhodli, že hlupáčkovi ukradnou křesadlo. Připravili hostinu, na kterého hlupáčka opili, vzali mu křesadlo. Druhý den ho nechali oběsit, protože, jak tvrdili, když se opil, svými řečmi urazil krále i princeznu.

_Hlupáčka oběsili a pod šibenicí pochovali. U jeho hrobu zůstal jen jeho bílý koníček a princeznina komorná. Koníček ji požádal, že ho určitě také zabijí, aby uschovala kvítko, které vyskočí z jeho hlavy a to zasadila princezně pod okny. Tak se i stalo a následují den vyrostla pod okny princezny překrásná jabloň_ s _nádhernými jablky._

Princezna si chtěla utrhnout jedno jablíčko, ale jablka promluvila: „Pro tebe jsem nerostlo, vražednice!“ Princezna nechala jabloň skácet a spálit, ale přeci se jedno jablko zakutálelo do rybníka.

_A ráno na rybníce plavala kachna se zlatým peřím s diamantovýma očima. Princezna ji chtěla mít, proto si odložila křesadlo i šaty na břehu rybníka, a vlezla do vody, aby kachnu polapila. V tom okamžiku kachna vzlétla, chytila do zobáku křesadlo, přinesla ho komorné a požádala ji, aby šla ke hrobu, kde je hlupáček pochován. Pak křesla křesadlem a přála si, aby hlupáček ožil. Stalo se a hrob se otevřel a hlupáček z něho vyšel, vzal od komorné křesadlo a přál si, aby na zámek padal oheň a síra, aby celý zámek a všichni v něm shořeli. Tak se i stalo. Přitom ale ztratil křesadlo a když ho hledal, vykopal velký poklad._

_Hlupáček se vrátil domů a oženil se s komornou._

Téma převtělování je blízké také mongolské kultuře. Pohádka O přátelství hovoří _o velkém přátelství dvou mláďat – tygříka a býčka. Jednou lovci zabili býčka, který se pásl na louce a snědli ho, zanechali jen jeho kosti. Tygřík_ _ze žalu vedle býčkových kostí skonal. Tu se nad stepí rozlehl mocný hlas větru: „Kdo miluje svého přítele víc než vlastní život, ten bude žít i po smrti!“_

_Jednou tou stepí hnal chánův pastevec stádo ovcí. Uviděl kosti a zakopal je do země. Na tom místě vyrostly dva statné a krásné stromy. Při východu slunce seskočili s větví stromů dva chlapci. Celý den si hráli, a když slánce zapadlo, zmizeli v korunách stromů. Dozvěděl se o tom chán a nechal chlapce přivést k sobě, aby mu sloužili. Jednoho nazvali Altan Gu, druhého Mungun Gu._

Když vyrostli, nařídil chán, aby se Antal Gu stal vojákem. Tak byli chlapci rozděleni. Mungun Guovi chán nařídil, aby pro něho unesl krásnou dceru sousedního chána, Ojun. Bylo to velmi nebezpečné, ale podařilo se mu to. Protože se oba do sebe zamilovali, rozhodli se postavit si jurtu a žít spolu. Chán se o tom dozvěděl a vyslal proti těm dvěma vojsko. Tou dobou se vrátil z války Altan Gu a postavil se na bratrovu stranu. Podařilo se jim přemoci vojsko a připravit o život chána. Pak všichni tři žili spolu šťastně daleko od lidí.

**Rusové** měli koncept „dobré" a „špatné" smrti. „Dobrá" smrt proběhne ve stáří, v čase, který určil Bůh. Umírající je obklopen rodinnými příslušníky. Tito zemřelí se nazývali „roditeli" (rodiče, předkové). Po vykonání příslušných rituálů, které jim zajistilo rychlou cestu k posmrtnému životu, jsou pohřbeni do posvátné země. To mělo mít blahodárný účinek na úrodnost půdy.

Do kategorie „špatné“ smrti byli zařazování ti, kteří zemřeli příliš brzy (zavraždění, zemřelí nešťastnou náhodou, sebevrazi, oběti epidemií). Ti nesměli do onoho světa, dokud nenastane jejich čas. Museli do té doby dlít v beznaději na zemi. Nesměli do posvátné půdy, proto je vhazovali do vykopané jámy, nebo ponechali na zemi a zakryli kamením a větvemi. Nazývali je „mertvjaki" nebo „založnyje" (skrytí). Byli obviňováni ze suchého počasí nebo krupobití.

Věřilo se také, že rusalky jsou duše dětí nebo utonulých panen. Víly byly duše zemřelých dívek, které zemřely nepokřtěny, nebo kterou opustil milý a jejichž duše bloudily mezi nebem a zemí. Duše mrtvých se mohly také usadit ve stromech a rostlinách a ty pak dostávaly lidské vlastnosti.

Duše se oddělovala od těla nejen v okamžiku smrti, ale často i během spánku. Mohla na sebe vzít podobu Kikimory (ohyzdná stará žena s dlouhými, vlajícími vlasy), která mohla svým nářkem přivolat smrt.

V pohádkách se setkáváme s hrdinou/hrdinkou, kteří musí projít královstvími (jejich počet se většinou rovná násobku tří), sníst tři kamenné chleby, prochodit troje železné boty, zničit tři železné hole, zdolat horu ze skla a nakonec se ocitnou na „onom světě“, který je popisován jako bájný ostrov Bujan v moři, jako místo věčného slunce a štěstí. Tam přebývají duše mrtvých i dosud nenarozených lidí, všechna semena, rostliny a ptáci, kteří se objeví na jaře. Žijí tam tři bratři , Severní, Západní a Jižní vítr. Roste tam dub, v jehož větvích má Kostěj nesmrtelný ukrytou svou duši

**Staří Slované** věřili v nesmrtelnost duše a představovali si, že po smrti duše odlétá. Považovali ji za vzdušnou bytost, která vychází jako dech ústy. Bohové Rod, Lada a Svarog stvořili člověka ze země, slova-duše a vědomí. Proto se po smrti tělo vrací zemi – bohyni Mokoši, duše odchází do podsvětí, kde ji provází bůh Veles, a vědomí se vrací k bohu Rodovi (Stvořitel).

Slovanský bůh Veles (zpodobňován jako mladý rohatý bojovník oděný v kůži) býval bohem dobytku a úrody, umění, obchodu, magie, a věštění. _Přemohl temného Dije a ten se mu chtěl pomstít. Uspořádal hostinu, na kterou pozval i Velese a podal mu otrávené víno. Veles se napil, ztratil vědomí a navěky musel zůstat v podsvětí, kde bojuje se silami temna a provází duše podsvětím._

Morana (bohyně zimy a smrti) je dcerou bohyně Mokoš (bohyně země a osudu, štěstí a neštěstí). Vstoupit do jejích komnat může jen její syn Smrt. Morana spolu se Smrtí udělají každému smrtelníkovi hned po narození otisk dlaně a vedle tohoto otisku hoří každému smrtelníkovi lampa. Do lampy není vidět. Jen Smrt do ní dokáže strčit svůj dlouhý kostnatý prst, a tak jen on ví, kolik života komu ještě zbývá. Až v lampě dohoří olej, pošle Morana svého syna, aby tuto duši přivedl do podsvětí. Podle toho, zda je tato duše čistá, nebo temná, ji přivede do království Prav, či Nav.

_Stalo se, že bohyně Pizamar (patronka zpěvu a ostatních umění) se zamilovala do pozemského mladíka Igrice, který nádherně zpíval. Ostatní bohové si z ní tropili legraci a aby ji pozlobili, řekli ji, že Igric brzy zemře. Pizamar byla nešťastná a tak se odhodlala k zoufalému činu. Požádala Igrice, aby ji otiskl svou dlaň do hliněné destičky. Pak uprosila bohyni Mokoš, a ta ji ušila roucho, které ji umožnilo dostat se nepozorovaně do podsvětí. Tam našla Igricův otisk na stěně a dolila mládencovu černou lampu._

Při návratu ale vyrušila trojhlavého vlka a byl z toho velký rozruch. Pizamar byla bohy potrestána: V Igricově přítomnosti nesměla na sebe vzít žádnou podobu, jakou je lidské oko schopno vidět, a nesměla vydat žádný zvuk, jaký dokáže lidské ucho slyšet.

Aby se tato situace nezopakovala, učinili bohové opatření. Smrt totiž musí chodit pro duše umírajících, aby je doprovodil do Velesova království. Aby v té době bohové nemohli svým oblíbencům dolévat do lamp oheň, střeží teď posvátné lampy obrovský netopýr se sedmdesáti sedmi očima.

Morana byla zobrazována zpravidla jako krásná mladá žena v bílých šatech se svíčkou či svítilnou v ruce, černovlasá, modrooká. Ze stromů ji byl zasvěcen smrk.

Její syn Smrt je vládcem nad smrtí. Společně s bohem Provem rozhoduje o tom, zda lidská duše půjde do podsvětí, kde vládne Veles spolu s Mokoší (krajina Prav), nebo do částí, kde vládne Kaščej a Morana (krajina Nav). V Navu duše mrtvých trpí. Mají podobu havranů a černých vran. Čekají, až se nad nimi osud slituje a vysvobodí je z ponuré jeskyně, kde není jediného slunečního paprsku, jediného hlásku či trochu vůně.

V *křesťanství* se hovoří o pekle, nebi a očistci, kde mohou přijít duše zemřelého. Nehovoří se o podsvětí (sídlo duší zemřelých). Peklo proto nelze ztotožňovat s podsvětím.

__Peklo__ bylo původně božím věčným trestem pro Lucifera/Satana/Ďábla a jeho padlých andělů. Jelikož se člověk může vydat na stejnou cestu (vzpoura proti Bohu), hrozí peklo i jemu. V pekle končí všechny naděje. Duše čeká věčné zatracení. Zde totiž nedlí Bůh.

_Nebe_ je místo, kde Bůh dlí. A ten je absolutní láska, radost i pokoj. Nebe je stav, který slovy nelze popsat, jelikož je to spasení duše.

_Očistec_ je místo/stav dočasného trestu duše člověka, který sice zemřel v Boží milosti, ale nebyly mu odpuštěny lehké hříchy. Jeho duše musí být nejdříve očištěna, než může vstoupit do nebe.

Velmi zajímavý popis těchto míst vytváří **A. Dante** (1265-1321), hluboce věřící křesťan, ve své Komedii (tzn. příběh s dobrým koncem). G. Boccaccio ji pojmenoval „*Božská komedie*“.

A. Dante začíná popisem PEKLA, místa nekonečného zatracení (zatracení není trestem za hřích jako takový; člověk zatratí sám sebe tím, že se odvrátí od Boha). Do něj se vstupuje pekelnou bránou. Průvodce mu dělá Vergilius.

_Peklo je rozděleno na devět okruhů: Limbus čili předpeklí ( je to místo dobré, ale není to nebe, dlí zde nepokřtění nevinní a cnostní pohané), ve kterém teče řeka Acheron, přes níž duše převáží Cháron do druhého okruhu, kterým je Chtíč (zde netvor Mínos soudí duše). V tomto a následujících okruzích jsou pro duše hříšníků připravena nekonečná muka. Třetí okruh je Obžerství,čtvrtý je Lakomství. V pátém okruhu nazvaném Hněv, teče močálovitá řeka Styx. Šestým okruhem je Kacířství, sedmým Násilí (v něm teče řeka vřící krve Flegeton), osmým okruhem je Malebolge (tvořen deseti soustředěnými kruhy – každý kruh_ _pro jiné hříšníky). Posledním okruhem je Kokyt – mrazivý střed vesmíru, nejvzdálenější místo od Boží lásky. Zde se vlévají všechny řeky pekla a zamrzají zde. Je rozdělen na čtyři kruhy, každý určen pro nejtěžší zločince (např. Kain, Jidáš, Mordred, někteří biskupové). V nejhlubší propasti posledního kruhu pekla je Lucifer, někdejší Pán světla, který povstal proti Bohu. Je zamrzlý v ledu v samém srdci pekla. Místo andělských křídel má křídla netopýří, kterými neustále mává, aby se osvobodil. Ale tímto pohybem se vytváří studený vítr a proto je Kokyt neustále zmrzlý._

_Úzkým průchodem se z pekla Dante i jeho průvodce dostávají do OČISTCE k Očistcové hoře. Nejdříve se dostávají do Předočistce, kde se nacházejí ti, kteří odkládali své pokání. Na rozdíl od Limbu (předpeklí) se nevzdávají naděje na spasení. Po zdolání jednotlivých stupňů Předočistce (patří vyobcovaným, lenivým, nevyzpovídaným, nedbalým vládcům), se oba_ _dostávají před bránu svatého Petra, kterou se vstupuje do Očistce. Ten má sedm teras. Každá odpovídá jednomu ze sedmi smrtelných hříchů (pýcha, závist, hněv, lenost, lakomství, obžerství, chtíč). Na vrcholu hory je Pozemský ráj (Rajská zahrada, ve které kdysi pobývali Adam a Eva). Odsud vede cesta do RÁJe._

_Zde je Dantemu průvodcem jeho platonicky milovaná Beatrice. Ráj je tvořen devíti nebesy - soustředěné sférické kruhy - v jejich centru je Země. Nebesa mají různé vlastnosti, které odpovídají jim přiřazeným planetám: Měsíc (nejblíže k zemi), Merkur, Venuše, Slunce, Mars, Jupiter, Saturn, Nebe stálic (v podstatě souhvězdí zvěrokruhu), Primum Mobile – křišťálová klenba nebeská._

_Každý kruh je symbolickým obydlím zářících duší, které mají touhu dostat se co nejblíže_ _k Bohu (Šalamoun, Adam, Eva, Mojžíš, starozákonní David, Konstantin Veliký atd.). Tyto zářící duše v jednotlivých nebesích provázejí Danteho a Beatrici, zpěvem oslavují Boha, ochotně odpovídají na jeho otázky dřív, než byly vysloveny (např. co je to spasení, svobodná vůle, podstata lidské přirozenosti)._

Přechodem do vyšší sféry krása jeho průvodkyně vzrůstá, oslavné hymny jsou nádhernější a slova pro popsání všeho chybí. Dante dokonce několikrát omdlévá prožitkem boží lásky, která vše prostupuje.

_Deváté nebe, Primum Mobile, je zcela obklopeno Boží vůli. Kolem bodu nejryzejšího světla se otáčí devět soustředěných kruhů. Tím bodem je Bůh a otáčející se kruhy jsou řády andělů. Bůh je všeobjímající a je současně středem. Zářící boží střed obklopují duše požehnaných jako okvětní lístky tajuplné růže. V jejím středu Dante spatří tři kruhy světla, které jsou jedním. Boží obydlí je mimo čas a prostor. Je to Empyreum (zjednodušeně vesmír)._

Úplně jinak, přitom emočně a sugestivně, je peklo popsané L. Lukačovičovou a M. Dobešem. Jejich fantasy Vánoční příběh vypráví _příběh hádajících se dětských dvojčat Petra a Magdy a dvojčat Ježíška a Luciena (Lucifera). Lucien, pán pekla, se rozhodne ukrást Vánoční hvězdu, aby zničil Vánoce. Petr a Magda se zapletou do jeho plánů, protože se rozhodnou Vánoce zachránit. Dostávají se do Ježíškovy říše, do říše Tří králů a nakonec i do pekla._

Cesta do pekla je dlážděná dobrými předsevzetími. Každá dlaždice představuje nějaké předsevzetí či dobrý úmysl a unese jen toho, kdo se mu nezpronevěřil. V pekle jsou všudepřítomné pekelné ohně, a naříkání, všechno je ukováno z křičících a trpících duší.

_Petr nakonec podlehne Lucienovým slibům a zaprodá mu duši své setry, aniž ví, co to vlastně znamená. Když zjistí, že Lucien chce Magdinu duši překovat ve výhni a udělat z ní řetěz pro spoutání Vánoční hvězdy, snaží se její duši zachránit a tím vlastně i svoji._

Křesťané uznávají Ježíše Nazaretského jako spasitele, který je vykoupil z hříchů. Očekávají opětovný příchod mesiáše, který přinese vykoupení.

Podle písma nastane apokalypsa, poslední boj s nepřáteli Krista. Lidé vstanou z mrtvých a spravedliví budou přijati do království nebeského. Křesťanství tedy nabízí příslib věčného života v nebi – vzkříšení. Náboženství, která vycházejí z věčně se opakujících cyklů zrození, růstu, plodnosti a rozpadu nabízí znovuzrození, inkarnaci.

V **Arktických oblastech** panuje víra, že každá osoba má trojí duši: osobní duši, volnou duši (dech) a duši jména. Jméno má velkou moc a dědic jména zdědí dobré vlastnosti zemřelého. Díky duši jména se stávají zemřelí strážnými duchy svých potomků.

Po smrti se duše člověka rozdělí. Jedna zůstane s tělem zemřelého ve světě živých jako duch, druhá putuje na nebesa a posléze najde cestu k nejvyšší bytosti Ponovi, a třetí odchází do říše stínů, kde se nakonec stane sama stínem. Cesta pro duši do říše stínů je namáhavá. Když se ale duše stane stínem, vede stejný život jako ve světě živých. Stínová duše se připojí k duším svých pozemských příbuzných a přátel. Loví stínové duše zvířat a chytá stínové duše ryb.

Duše nakonec z říše stínů odejdou a vrátí se na zemi, aby se znovu narodily. Zatímco duše čekají na znovuzrození, vytvářejí polární záři (Laponci věří, že šťastné duše tančí v polární záři). Když si však živí neváží duše zemřelých, ty se nechtějí vrátit a ženy pak nemohou otěhotnět.

Specifické představy o smrti měli lidé určitých povolání. V severské mytologii **duše válečníků**, kteří se vyznamenali v boji a zemřeli na poli válečném, zejména oštěpem, a které si vybral Ódin (nejvyšší božstvo), odvádí Valkýry (krásné válečnice na okřídlených koních) do Valhally (Síně padlých). Valkýry je tam obsluhují a válečníci se veselí, hodují, bojují mezi sebou a když padnou, druhý den opět vstanou a pokračují v hodování. Jsou Ódinovou osobní armádou (inherjové), kterou tento povolá do poslední bitvy (Ragnarök), proti mocnostem zla vedeným bohem Lokim a jeho nestvůrnými dětmi.

*Námořníci* vždy věřili v přízračnou loď. Bretaňská legenda mluví o takové bárce mrtvých s bílou plachtou, která ohlašuje blížící se smrt utopením. Námořníci vědí, že jedno místo na palubě čeká na každého z nich. Řídí ji buď hrozivá posádka mrtvých, nebo jediná postava, poslední člověk, který se v daném roce utopil (nazývali ho Ankou) a dosud neví, kde se nachází jeho vlastní tělo. Tento převozník duší má odvést mrtvého na onen svět.

K poslední cestě totiž duše zemřelého potřebuje most, bárku nebo ponton, protože si nesmí namočit nohy.

Pohádka Stříbrný albatros _vypráví o mladém rybáři Michalovi a jeho sestře Maryně. Michal miloval moře. Na moře vyjížděl i za bouře, aby pomohl druhům v nesnázích. Ti ho varovali, že za svou dobrotu bude pykat, protože mocný pán hlubin nikdy neodpustí tomu, kdo mu odnáší jeho kořist. Michal se tomu smál._

Jednou zuřila strašlivá bouře a Michal se domu nevrátil. Najednou se objevil stříbrný albatros, který kroužil nad mořem vždy, když měla přijít bouře. Sotva ho rybáři zahlédli, v ten den se na moře nevydali.

Maryna po svém bratru velice tesknila. Každý den chodívala na břeh moře a ptala se vln, zda vědí, kde je její bratr. Jednou ji vlny odpověděly, že ten stříbrný albatros jej její bratr. Pokud s ním chce být, musí za ním plout. Maryna sedla na loďku a vyplula na širé moře. Plula dlouho, když se tu najednou přihnala bouře. Loďka se zmítala na ohromných vlnách a hrozilo, že se potopí. Tu přiletěl stříbrný albatros, uchopil omdlelou dívku a doletěl s ní na ostrov obestřený těžkou mlhou. Tam ji položil na zem.

Albatros se proměnil v Michala. Maryna jej prosila, aby se vrátil domů. On ji však řekl, že nemůže. Je opředen čarovnou mocí hlubin. Kdo zemřel ve vlnách, ten se nikdy nevrátí. Vejde do říše jiných světů, které jsou zastřeny těžkou mlhou, která obejme člověka ve chvíli jeho smrti. Člověk ji neprohlédne a nikdy její tajemství nepochopí. Všichni utonulí žijí, ale jiným životem, než kterým žili ve slunečním světě.

Když Michal domluvil, neproniknutelná mlha Maryně zakryla oči. Když opět prohlédla, její loďka byla na břehu moře, odkud před několika dny vyjela za svým bratrem Michalem.

Ve světě převažuje víra v *nesmrtelnost duše*. Tato víra se odráží i v pohádce o Šípkové Růžence (duše), která se na základě kletby píchne o vřeteno a má zemřít. Nezemře (duše je nesmrtelná), jen usne na sto let.

Z tohoto spánku ji může vysvobodit polibek z pravé lásky (vzkříšení, znovuzrození), což se i stane a Šípková Růženka (duše) je osvobozena. Smrt je často vnímána jako specifický spánek, který umožňuje znovuzrození či přechod do věčnosti, do nebeské, všepohlcující lásky.

Víra, že člověk není pouhým tělem, je prastará. Tělo je jen schránkou pro cosi jiného – pro duši (životní princip, dech, síla, duch).

Římský mýtus o Psyché (duše) _hovoří o královské dceři Psyché, která byla tak krásná, že vyvolala žárlivost bohyně lásky Venuše (odpovídá ji řecká bohyně Afrodité). Poslala svého syna Amora, aby ji pomstil. Ten se však do Psyché zamiloval a unesl ji do svého sídla. Navštěvoval ji jen v noci. Měla ním zakázáno, spatřit ho._

_Když byla Psyché navštívit své setry, ty velice žárlily a namluvily ji, že je to nějaký netvor, kdo k ní v noci přichází. Přesvědčily ji, aby v noci zažala lampu a podívala se na něho. Psyché tak učinila a uviděla krásného jinocha. Horký olej z lampy ukápl na jeho rameno, popálil jej a Amor se probudil. Musel Psyché opustit._

_Venuše ji nechala zbičovat a uložila ji čtyři nesplnitelné úkoly. Dívka je však splnila. Posledním úkolem bylo přinést od vládkyně podsvětí trochu její krásy uložené v malé skříňce, kterou neměla otevřít. Když se Psyché vrátila z podsvětí, zvědavost a touha po kráse, aby se více zalíbila Amorovi ji přemohla a ona skříňku otevřela. V ní byl věčný spánek, do kterého upadla. Amor ji hledal a našel ji. Sňal z jejich víček věčný spánek._

_Nakonec ji Venuše odpustila a Jupiter Psyché daroval nesmrtelnost._

Psyché je zde v podstatě personifikací lidské duše. Nádherná, zvědavá, podléhající pokušení, zvládající překážky… nesmrtelná. V umění byla často ztvárňována jako dívka s motýlími křídly, nebo motýl.

Křesťané hovoří o duši a těle. V pohanském smyslu je to dvojnictví. Naši pohanští předkové věřili v existenci Dvojníka. Je to naše nezávislé druhé já, které je osvobozené od těla, když toto spí, je oslabené nemocí, nebo strnulé v transu či v kómatu (šaman, vizionář). Dvojník může putovat mezi světy, získávat poznatky, které se pak odhalují v našich snech.

Sen je v každé kultuře akceptovaným prostředkem komunikace se záhrobím, s věcmi neviditelnými apod. (např. se praktikoval zvyk strávit noc na posvátném místě či hrobě v očekávání, že jeho nadpřirozený obyvatel dotyčnému poskytne věštecký sen).

Duše křesťana je vázána k Bohu, duše pohana je spojena s celým kosmem, ze kterého může čerpat. Díky Duši/Dvojníkovi nejsme sami a žijeme věčně (např. prostřednictvím stěhování duší).

Na téma různých představ o životě po smrti natočil režisér V. Ward v r. 1998 zajímavý film Jak přicházejí sny. Film je plný symbolů, uchvacujících vizuálních obrazů a ztvárnění různých představ o posmrtném životě.

Lékař Chris s manželkou Anni přišli o své děti při nezaviněné autohavárii. Anni poté spáchala sebevraždu. Chris velice trpí a nakonec úmyslně ukončí svůj život doufaje, že se s Anni a dětmi setká.

_Každý jednotlivec má svůj individuální posmrtný život, vytvořený jeho vlastními představami. Chris se po své smrti ocitá ve svém posmrtném světě, vytvořeném jeho vlastními představami, vzpomínkami a sny. Setkává se v něm se svými dětmi. Děti mají jinou podobu, než v reálném životě a trvá mu, než je zpozná._

Chris se pak vydává za svou Anni do jejího posmrtného světa - do pekla, které si vytvořila. Dlouho se mu nedaří ji zachránit (dostat z jejího pekla), protože Anni ztratila naději. Nakonec se mu podaří ji zachránit a celá rodina se setkává. Jejich posmrtné světy se prolnou.

_Příběh ale pokračuje, protože je možná reinkarnace. A tak se Chris i Anni opět setkávají v reálném životě, samozřejmě ne ve své původní podobě._

*PODOBA SMRTI* se vyvíjela. Zpočátku byl „démon smrti“ vnímán jako neviditelná bytost, která se objeví nečekaně a skrytá před lidskými zraky. Následně měl podobu zvířete (zejména psa, vlka, hada, ptáka, koně). Později je vnímán jako lidská postava a tím se smrt stává bohem (bohové bývají personifikování).

Může mít různou podobu. Může mít podobu ženskou i mužskou. Jako žena je zobrazována jednak jako krásná mladá dívka v bílém, jednak jako stará zamračená babizna v bílém – Zubatá.

Jedna pověst z Moravy vypráví o období, kdy _celou zemi sužovala nouze a hlad. A začala se šířit cholera. Jednou večer se vracel švec Karas z města. U lesa ho dohnala nějaká žena, vysoká a vyzáblá, hlavu měla celou zabalenou do režné plachetky. Vyhlížela podivně. A tak šli dál spolu. _

Švec ji vyprávěl, co se děje po okolí. Že v poslední době tady zemřelo na dvě stě lidí. A žena mu pověděla toto: „Z těch dvou set jich polovic umřelo jen strachy přede mnou.“ Pak vytáhla z pod plachetky kostnatou ruku se svazečkem květin. Ty mu podala, aby lidem dal pít odvar z těch květin a nebudou mřít. A v té chvíli se mu ztratila z očí. Karas poznal, že potkal Smrt.

Ráno prohlížel květiny, co dostal. Byla to třezalka a ten, kdo si ji uvařil a pil, choleru nedostal.

V mužské podobě je zobrazován jako kostlivec často oděný do černé kutny s kapucí (kapuce symbolicky činila dotyčného neviditelným). Dalšími atributy jsou přesýpací hodiny, kosa nebo srp a někdy také kůň. Kůň evokuje rychlost. Kosa a srp jsou symbolem ničivého aspektu času a smrti. Původně jsou spolu s přesýpacími hodinami atributem starořeckého boha Času Chrona (později splynul se Saturnem). Přesýpací hodiny jsou symbolem neúprosně plynoucího času a smrti. Protože se musí zase převrátit, aby se písek opět přesypával, jsou také symbolem konce a nového začátku.

Smrti bývá přisuzována úloha převozníka, který převáží mrtvé na onen svět; průvodce, který převádí duše na onen svět; toho, kdo svou kosou ukončuje lidský život (rozhodnutím vyšší moci).

Mezi další spodobnění smrti např. patří:

- *Jama*, indický bůh smrti a zmaru. Je to krásný, zářící muž. Je oděn v tmavočervené roucho, na hlavě má zlatou čelenku a v ruce provaz se smyčkou. Někdy bývá zobrazen jako kulhavý mužík, který jede na černém buvolovi.

- *Kálí* je hinduistická bohyně zkázy a zmaru, Matka smrti, stvořitelka a ničitelka. Její tělo je vychrtlé, vlasy dlouhé a rozcuchané, kolem krku má náhrdelník z lebek, sukni ze stehenních kostí, vyplazený jazyk, má několik paží. Je to nejhrozivější podoba bohyně Párvátí, Šivovy manželky. Je ztělesněním ničivého aspektu bohyně matky – přírody. Je to země, která vše dává i vtahuje vše zpátky do sebe. Proto je na smrt pohlíženo jako na milující matku.

- *Hel* je Paní smrt nordického panteonu. Žije na planině Niflheim , která je studená a temná jako skandinávská zima. Je zpodobňována napůl jako krásná žena, napůl jako kostra. Je šeredná i krásná, vlídná i děsivá.

- *Valkýry* severské mytologie. Krásné, ale nebezpečné dívky jezdící na koních rychleji něž vítr. Dle Ódinových pokynů sbírají na bitevních polích duše padlých válečníků.

- *Banshee* (Bean Sidhe) – irská víla smrti. Každý starousedlý irský rod má svou vlastní Banshee. Varuje jejich příslušníky svým nářkem, pokud je čeká nějaké neštěstí nebo smrt člena jejich rodiny. Někdy se zjevuje jako dívka, která u potoka pere zakrvácené prádlo toho, kdo má zemřít.

- *AnPuch* (vyslov ach puč), mayský bůh smrti. Mívá podobu kostlivce.

Nejvýstižněji a nejpoetičtěji se podařilo popsat Smrt M. Vopěnkovi v pohádce Sestra Smrt (in O duši a dívce – pohádky z hor):

_Smrt chodívá oděna v průsvitném rouchu ztrácejícím se k západu, východu, severu i jihu, avšak před sebou vrhá temný stín. Tak se stávalo, že kdo se před ní skrýval nebo kdo ji naopak běžel v ústrety, viděl mnohdy jen tmu, zatímco kdo ji v klidu očekával, mohl skrze ni nahlédnout do věčnosti. Neboť smrt a věčnost jsou sestry. Přijde-li někam smrt, můžete si být jisti, že opodál stojí i věčnost. Jindy přicházejí v opačném pořadí nebo i současně._

V mnoha mýtech se setkáváme s třemi *bohyněmi osudu* (Řecko – Moiry, Řím – Párky, severské mýty – Norny, Slované - sudičky). Jsou to přadleny, které tkají vlákno života každého člověka a jedna z nich v předurčený čas nit přestřihne a tím život tohoto člověka končí.

U Slovanů panovala víra v Rožanice (rodičky, matky rodu) a Sudice (sudičky), které určovaly osud novorozence. Jsou oděny v bílé roucho. Nit, kterou Rožanice předou, je symbolem spojitosti osudu s rodem.

Čechové věřili, že Sudičky pošlou na šestinedělku hluboký spánek, vezmou nemluvně a položí jej na stůl (nebo se nad nemluvnětem v kolébce nakloní) a určují mu osud.

Obyčejně se zjevovaly tři Sudičky, z nichž ta, co mluví jako poslední, to, co vyřkne, je vždy rozhodující a splní se.

Předení se pro Slovany, Vikingy a Kelty vztahovalo k osudu, a proto v období Vánoc pro ženy platil přísný zákaz předení.

I když se lidé smrti báli, připouštěli, že je spravedlivá, protože si vezme každého. V české básni Rozmlouvání člověka se smrtí z 15. století __se snaží boháč přemluvit Smrt, aby ho nechala žít. Argumentuje tím, že by raději měla navštívit chudé, mrzáky, těžce nemocné … Smrt namítá, že bůh sám ji pověřil její spravedlivou práci (ona sama nerozhoduje o tom, kdy kdo zemře, je jen vykonavatelem).__

Boháč namítá, že po něm zůstanou děti a žena bez jeho ochrany. Smrt odpovídá, že děti budou pod ochranou Boha a jeho žena se časem vdá. Boháč Smrti slibuje, že se polepší, že bude vést příkladný život. Smrt se mu ale směje, že má zkušenosti s lidskými sliby a proto na lidské sliby nevěří. A bere si jeho život.

V jedné z verzí pohádek Smrt kmotřička, __kdy chudák hledá kmotra pro své narozené dítě, potkává Boha. Odmítne jeho nabídku být kmotrem, protože je nespravedlivý, když dovolí, aby lidé žili v bídě, byli nemocní.__

Pak potkává čerta, který mu také nabídne své kmotrovství. I toho odmítne s tím, že je nespravedlivý, protože pomáhá špatným a zlým lidem a podporuje zlo.

Nakonec potkává Smrt. Tu přijme za kmotru svého dítěte, protože ta jediná je spravedlivá. Přijde si pro každého bez rozdílu.

Způsob, jak dá smrt o sobě vědět může proběhnout i bez její přímé účasti. Židovská pověst Zavolání k Tóře vypráví, jak _rabín Moše Hahn se jednou vracel domů od svého přítele, se kterým studoval talmud. Byla už půlnoc a on prošel kolem hřbitova a blížil se k synagoze. Tuto cestu od svého přítele už prošel mnohokrát._

Najednou uslyšel zvuk modliteb, které vycházely z uzamčené synagogy. Rabín věděl, že ve dne se v synagoze modlí živí, v noci mrtví. Proto musí první zbožná Žid, když jde ráno synagogu otvírat, třikrát zaklepat na vrata, aby dal mrtvým na vědomí, že jejich doba skončila a oni musí uvolnit místo modliteb živým.

Rabím se zastavil a naslouchal. A uslyšel hlasy svých dávno mrtvých přátel. Najednou uslyšel, jak někdo pronesl jeho jméno a ještě jednou. Shromáždění volalo, aby předčítal Tóru. Rabín dobře věděl, že tato pocta se neodmítá. Že se bude muset připojit ke sboru mrtvých.

Když přišel domů, dal své věci do pořádku, rozloučil se se všemi a večer skonal. Druhou noc po jeho pohřbu procházel jeho přítel v noci kolem Staronové synagogy a uslyšel hlasy modlících se mrtvých. Nejjasněji zněl hlas rabína Hahna, který ostatním předčítal Tóru.

*ANDĚLÉ* jako duchovní bytosti jsou prostředníky mezi bohy či bohem a smrtelníky. Jsou součástí téměř všech velkých náboženství. Jejich hlavním úkolem je dohlížet ve vesmíru na vše stvořené, udržovat vesmír a velebit slávu Boha.

Nejstarší historické záznamy o okřídlených bytostech pocházejí z jednoho z nejstaršího náboženství - zoroastrismu. Andělské bytosti jsou zde nazývané ahurové. Judaismus také zná anděly. Strážným andělem izraelského národa je archanděl Michael. V křesťanství jsou andělé chápání jako duchovní bytosti, které jsou prostředníky mezi Bohem a lidmi. Buddhisté věří, že andělé jsou „bódhisattvové“ (osvícení) - bytosti, které dosáhly vysoké úrovně, ale jejich vstup do nirvány je odložen, aby pomohly dosáhnout osvícení i ostatním. Víra v anděly je jedním ze základních pilířů islámské víry. Podle Koránu byli andělé stvořeni ze světla. Andělé mají křídla, jsou krásní a mají obrovské rozměry. Jibril je poslem mezi Bohem a lidmi. Doprovázel Mohameda přes různé úrovně nebes, aby dosáhl Božího trůnu. Keltští andělé jsou duchovní bytosti. Anamcharové (andělé ) jsou ti, kteří mají nejblíže k člověku i k našemu hmotnému světu. Byli součástí každodenního života Keltů. Někdy měli křídla.

V minulých i současných kulturách existuje představa osobních strážných duchů, kteří doprovázejí každého jedince jeho životem. V Japonsku je to _kami_, v Řecku _daimón_, v předkřesťanském Římě to byl _genius_ (chránil chlapce), a _juno_ (chránila dívky), Skandinávci znají fylgju. V islámu má každá osoba dva páry ochranných bytostí (_hafaza_) – jeden ji stráží ve dne, druhý v noci. Křesťanství hovoří o _andělech strážních_, kteří pomáhají jedinci v boji proti ďábelským svodům a vedou ho ke křesťansky naplněnému životu.

Svátek strážních andělů se slaví 2. října.

Osobní strážní duch nás doprovází od našeho narození až do naší smrti. Je prastarým zvykem tomuto duchovi každý rok přinášet oběti a oslavovat ho – dnes tento zvyk známe jako oslava narozenin.

Hovoří se také o _andělech smrti_, jejichž úkolem je sběr duší a jejich předvedení před soud. Podle knihy Zohar (kabalistický spis židovského mystického učení) je Jehudia andělem sloužícím ve chvíli smrti. Sestoupí k umírajícímu s dalšími anděly, aby vynesl duši na nebesa. Islám zná několik andělů smrti, nejznámější je Azrael.

Muslimové říkají: "Když se k tobě blíží Anděl smrti, je hrozný. Až tě uchvátí, zažiješ blaženství."

Perská pohádka Rybář ormunský _hovoří o kouzelnici Dale-Mutaleha, která přinášela bohatství a duchu Tyr-Abana, který přinášel vědění. Ti se jednou hádali, kdo z nich přináší člověku větší blaženost. Rozhodli se, že si vyberou muže, kterému Dale-Mutaleha poskytne bohatství a Tyr-Aban mu pak otevře pramen moudrosti. Pak budou z účinku těchto věcí usuzovat na lidskou povahu._

Vybrali si chudého rybáře Ismaela z ostrova Ormus. Kouzelnice proměnila Ismaela v syna bohatého Noserata. Musel však dodržovat to, že Noseratův syn měl zvyk mhouřit jedním okem. Ismael musel neustále myslet na to, že nemá zapomenout mhouřit jedním okem, aby se neprozradil. To ho časem velice unavovalo a pranic se netěšil užívat si bohatství.

_Tehdy duch Tyr-Abanamu mu ukázal cestu k vědění a za chvíli nebylo učenějšího člověka nad Ismaela. Když byl bohatý, lidé mu pochlebovali, teď, když byl moudrý, lidé ho oslavovali jako největšího mudrce a vyhledávali a žádali jeho rady. Ale časem se ozvaly závistivé hlasy, že není autorem spisů, které vydal. Ismaela to hněvalo a odebral se do pouště. Přidala se k němu dívka, která jej obdivovala a stala se jeho ženou. Narodilo se mu několik dětí a on je s potěšením vyučoval._

_Jednoho dne se rozstonal. Manželka i děti přišli k jeho loži, kromě nejstaršího syna, který byl v Teheránu. Před jeho domem hořely svíce umírajících._

Ismaelovi se zjevila Mutaleha a Tyr-Aban. Mutaleha měla v ruce kvítek Gulbad-Samur, který má moc otrávit dech. „Ismaeli“, promluvila kouzelnice, teď odbila tvá hodina a ty vejdeš do nesmrtelnosti. Nato se u jeho lůžka zjevilo čtvero andělů smrti: Monkir, Nakir, Mardal a Asrael. „Zadržte“, zvolala Ismael, „u mého lůžka chybí jedno z dětí. Nemohu zemřít, dokud jej nespatřím“. „Dobře“, řekl Tyr-Aban, „musíš se ale zříci mnoha století posmrtné slávy a my odložíme tvou smrt o tři dny.“ Ismael řekl: „Ať zemřu jako neznámý, ale chci ještě jednou přivinout k srdci nejstaršího syna.“

Křesťanským andělem smrti a božské spravedlnosti je archanděl Michael ale také archanděl Gabriel, který je andělem zvěstování, vzkříšení , milosrdenství, narození a smrti. Gabriel prý dává pokyny ještě nenarozenému dítěti (v sedmém nebi, které je příbytkem Boha, dlí duše ještě nenarozených lidských bytostí) aby mlčelo o posvátných zákonech (prohlubeň mezi nosem a horním rtem je Gabrielovo znamení toho pokynu). Při umírání pomáhá duším při velkém přestupu do jejich zaslouženého cíle.

Existuje také víra, že každá lidská bytost, když se narodí, zrodí se s ní dva její andělé – anděl života a anděl smrti, kteří ji sedí na ramenou a doprovází ji po celý její život, v době její smrti a po její smrti.
