== Jak přišla smrt k lidem

Indická pověst vypráví o ženě, které zemřel její jediný milovaný syn. Nechtěla se s tím smířit a vydala se k Buddhovi, aby jejímu synovi vrátil život. Ten s tím souhlasil pod podmínkou, že mu přinese olej do lampy jako dar od rodiny, ve které nikdo nezemřel.

_Žena prošla velký kus cesty, ale takovou rodinu nenašla. Nakonec pochopila, že život je vždy spojen se smrtí a smířila se se synovous smrtí._

Staré mýty ale i náboženství vypráví o tom, že na počátku byli lidé nesmrtelní, ale o tuto výsadu přišli a stali se fyzicky smrtelnými (např. přestoupili boží zákaz; příchod smrti je spojen s první vraždou; nechali se oklamat zlým duchem; zvíře vyslané se zprávou o nesmrtelnosti se opozdilo; hyena překousla provaz vedoucí do nebe, pomocí kterého se lidé dostávali do nebe a tam omládli; projevili sklon ke zkaženosti).

*Konové*(Guinea) mají mýtus o Smrti a Tvůrci: _Na počátku nebylo nic, jen Sa, Smrt, který žil v temnotě světa se svou ženou a jedinou dcerou._ _Aby měl kde_ _žít, stvořil moře bahna. Jednoho dne se objevil Alatangana, Bůh, a ten z toho bahna vytvořil zemi, rostliny a zvířata. Později si tajně odvedl dceru Sa, protože mu ji Sa nechtěl dát za ženu._

_Několikrát se stalo, že Alatangana si musel jít pro radu k Sa. Vždy mu pomohl. Když Sa dal lidem slunce, měsíc a hvězdy, řekl, že on vždy činil dobře, ale Alatangana mu ukradl jediné dítě a proto mu musí dát vždy toho, koho si přivolá._

A tak proto, že Alatangana nezaplatil za nevěstu, jak bylo zvykem, musí lidé umírat.

*Lambové* (Zambie) mají svůj mýtus o tom, jak přišla na svět smrt: _Jednou poslal náčelník své lidi za Bohem, aby přineslo semena na osev. Bůh jim dal několik sáčků. Na jeden ukázal a řekl, že ten nesmí rozvázat. Na zpáteční cestě ale byli tak zvědaví, že ten zakázaný sáček jeden z mužů rozvázal a z něho unikla smrt. Když to náčelník zjistil, nechal toho muže zabít. A tak na svět přišla smrt._

*Masajové* mají svou legendu o tom, jak lidé ztratili nesmrtelnost: _Když bůh stvořil lidi, vybral si Le-eyo, a dal mu radu, že až zemře první dítě, má odříkat určité zaklínadlo a to zaklínadlo mu svěřil. Tak se to dítě vrátí do života a lidé budou nesmrtelní._

Stalo se, že zemřelo dítě, které ale nepatřilo do Le-eyovy rodiny, a ten proto nevykonal obřad, jak mu bůh poradil. Pak ale zemřel jeho syn. Le-eyo nad ním vyřknul zaklínadlo, ale dítěti život nevrátil. A bůh mu řekl, že ho zklamal, když to zaklínadlo nepoužil už při smrti prvního dítěte z cizí rodiny a proto lidé budou jeho vinou smrtelní.

*Bainingové*(papuánský kmen) vypráví, že _Slunce jednoho dne svolalo všechny věci a zeptalo se jich, kdo chce žít navěky. Člověk ale tuto výzvu neposlechl a nepřišel na toto setkání. A proto kameny a hadi nyní žijí věčně, ale člověk nikoli. Kdyby člověk Slunce poslechl, mohl by občas měnit kůži jako had._

*Polynéský mýtus* o smrtelnosti lidí hovoří toto:__Maui (hrdina polynéských mýtů) si všiml, že jeho matka má bílé vlasy mezi svými černými. Matka mu vysvětlila, že je to proto, že zestárla. Až bude mít hlavu úplně bílou, znamená to, že brzy umře, pak ji Maui pochová do země a už ji nikdy neuvidí.__

Maui chtěl vědět, jak by lidé mohli získat nesmrtelnost. Matka mu vysvětlila, že by musel mít žaludek mořského slimáka. Maui se vydal na břeh moře a když našel mořského slimáka, vytrhl mu žaludek, pak vyvrátil svůj žaludek, a začal polykat slimákův žaludek. V té chvíli přišli jeho přátele a začali se mu vysmívat, že polyká žaludek mořského netvora.

Maui rychle slimákův žaludek vyplivl. Rychle polkl svůj žaludek a pak řekl: „Chtěl jsem lidem zabezpečit nesmrtelnost. Když jste mi to překazili, každý, kdo se narodí, bude muset umřít.“ Proto lidé umírají.

*Šajenský* mýtus (severoameričtí indiáni) Proč nežijeme věčně _vypráví o lidech - předcích. Když byli lidé stvořeni, chtěli vědět, zda budou žít věčně. Usnesli že, že když bude kámen plavat ve vodě, budou žít, kdyby se potopil, měli umřít. Koláči uschlého bizoního trusu přisoudili opačné podmínky._

Hodili do vody kámen. Chvilku zůstal na hladině a lidé se radovali, že budou žít věčně. Pak se ale potopil.

Hodili do vody bizoní trus a on se potopil a opět se radovali. Ale potom se vynořil a proud ho odnášel pryč.

Krátká chvíle, kdy kámen plave a bizoní trus se potápí , to je lidský život, než přijde smrt.

Kulturní hrdina šajenských mýtů Motséeóeve jednou vešel do velkého obydlí uvnitř kopce, kde byli věci a bytosti patřící na tuto zemi. Seděl v ní také černý muž, dobře stavěný hnědý muž, hezký bílý muž a velmi hezký hnědý muž. Náčelník shromážděných osob mu řekl, že si má vybrat jednoho, kterým se stane.

Motséeóeve si vybral velmi hezkého hnědého muže, protože chtěl být hezký. Muži zmizeli a místo bílého muže tu stál bílý kámen a místo černého muže, černý kámen, místo statného hnědého muže zde byla vysoká štíhlá rostlina a místo muže, kterého si vybral, stála nádherná rostlina vysoká po kolena.

Náčelník mu řekl, že si vybral špatně. Měl si vybrat bílého nebo černého muže. Pak vždy, kdyby zestárnul, proměnil by se v mladého muže a žil by věčně.

*Na ostrově Seram* se vypráví mýtus o smrti Hainuwele. _Za starých času se narodila ze stromu božská panna Hainuwele a zjevila se lidem. Neustále zahrnovala lidi cennými dary. Zpočátku se jim to líbilo, později byli znepokojeni. Mysleli, že neustále množství darů narušuje harmonii jejich života._

Lidé tehdy byli rozděleni do devíti rodin. Pravidelně tančili velký tanec Maro. Tančili ho po devět nocí na devíti posvátných místech a měl podobu devítinásobné spirály. Mulua Hainuwele sedávala ve středu spirály a rozdávala dary tanečníkům. Ti se ale jednou tajně dohodli, že ji po osmém tanci usmrtí. Na posledním z tanečních míst vyhloubili jámu. Do ní deváté noci pannu uvrhli a během tance na ni navršili zem, kterou pak udupali.

Příští ráno pannu hledal její otec. Vyhrabal její tělo a to rozdělil. Jednotlivé kousky pohřbil na jednotlivých tanečních místech. Tyto se pak proměnily ve věci, které předtím na zemi neexistovaly, např. v hlíznaté plody.

Její paže však neuložil do země, ale odnesl Mulua Satene, která vládla lidem. Ta se na lidi rozhněvala. Tam, kde dříve lidé tančili, postavila velkou bránu ve tvaru devítinásobné spirály uspořádané jako při tanci Maro. Stála na jedné stráně brány a svolávala lidi na druhou stranu. Řekla lidem: „Teď vás opustím. Ale ještě než tak učiním, musíte ke mně skrz tuto bránu přijít. Jen ti, kteří touto branou projdou, zůstanou lidmi. Kteří neprojdou, stanou se zvířaty či duchy lesů.“ A tak vznikla prasata, jeleni, ptáci, ryby, duchové.

__Satene držela v každé ruce jednu paži zavražděné Hainuwele. Jak lidé procházeli branou, každého z nich se paží dotkla. Od těch dob musí lidé zemřít a vydat se na „pouť mrtvých“, aby opět mohli Malue Satene spatřit. __Podle dalšího mýtu mohou od té doby lidé uzavírat sňatky – čili až s příchodem smrti může docházet k plození a rození.

S příchodem zemědělské kultury se prosazuje pohled na smrt jako na nutnost, aby mohl vzniknout nový život. V mýtech se objevují božstva, která umírají nebo jsou zabita a z jejich těla (nebo hrobu) vyrůstá rostlina, která dá lidem obživu (kukuřice, kokosová palma). Tedy někdo musí zemřít, aby mohl vzniknout nový život.

Objevuje se tu základní vzorec bytí: ze smrti se rodí život a zrození otevírá cestu smrti. Čili smrt a život jsou dvě stránky jedné mince - bytí.

*Perská pohádka* Šaty nesmrtelných se zabývá otázkou, proč musí lidé umírat. _Jeden bohatý kupec se dozvěděl, že uprostřed hlubokého lesa žije v domečku krásná víla s úplně bílými vlasy, ze kterých tká plátno a ten, kdo si z toho plátna ušije šaty a oblékne si je, bude žít věčně._

_Kupec se bál smrti a tak se vydal na cestu za bělovlasou vílou_. Protože__ se mnoho měsíců nevracel, rozhodl se jeho syn vyhledat ho. Když došel k onomu lesu, pokračoval statečně dál až skutečně došel na mýtinu. Tam stála chaloupka celá zelená a zlatá, u ní rostl statný dub a před chaloupkou stála krásná dívka s bílými vlasy v bílých šatech.__

Víla si ho vyslechla a pak mu řekla, že bílé plátno svých šatů utkala ze svých vlasů před sto léty, a dokud je nosí, nezestárne. Jeho otce neviděla. Proto svolala lesní zvířátka a od lišky se dozvěděla, že mladíkův otec je v zajetí vládce lesních duchů. Je očarován, nic si nepamatuje a pracuje pro lesní duchy.

Víla dala mládenci větev ze svého dubu a řekla mu, co má udělat. Požádala lišku, aby jej dovedla na místo, kde je jeho otec. Mládenec se řídil radami víly a již následující den s vysvobozeným otcem a liškou, která je vedla, se vrátili na palouček k víle. Ale domeček víly byl zničený, dub vytržen z kořenů a polámán a víla byla pryč.

Lesní zvířátka lišce řekla, co se stalo a ta kupci a jeho synovi vše tlumočila: „Poslyšte zprávu, kterou vám mám tlumočit! Padišách lesních duchů přiletěl na palouk, zničil domek i dub a unesl navždy vílu a všechno její bílé plátno do své říše. Nechce, aby se dostalo do rukou kupce. Člověk nemůže žít věčně. Kdyby přespříliš trávil svá léta na světě, země by se přeplnila a bylo by těžké žít. Nechť přicházejí lidé na svět jeden za druhým, a když skončí běh jejich roků, ať odejdou a postoupí místo dalším.“

Kupec a syn vyslechli liščinu zvěst a smutní se vrátili domů.

**Sumerský epos** o Gilgamešovi mimo jiné také hovoří o jeho snaze získat nesmrtelnost: _Gilgamešův přítel Enkidu zemře. Gilgameš je otřesen jeho smrtí a rozhodne se vydat za Utanapištim (člověk, který přežil potopu), jemuž bohové darovali věčný život. Gilgameš má podstoupit zkoušku šest dní a sedm nocí nespat (spánek je bratr smrti), ale tuto zkoušku nesloží. Přesto mu Utanapištim řekne o zázračné rostlině dávající věčný život, která roste na dně moře. Gilgameš ji získá, ale nakonec mu ji ukradne had. Gilgameš pochopí, že člověku není souzeno být nesmrtelným, ale může se stát nesmrtelným, když proslaví své jméno. Takže Gilgameš se v podstatě nesmrtelným stal._

*Křesťanská* víra operuje pojmem prvotní/dědičný hřích (stav hříšnosti, tedy nedokonalosti). _Adam a Eva byli první lidé, které Bůh stvořil. Rajská zahrada (zahrada Eden) bylo místo, které jim Bůh poskytl pro život. Bůh je upozornil, že jediné, co nesmí, je pojíst ovoce ze stromu poznání dobra a zla. Když tak učiní, čeká je smrt._

Ďábel v podobě hada Evu přesvědčil, že ovoce ze zakázaného stromu poznání by je učinilo rovným Bohu. A tak Adam i Eva pojedli ovoce ze stromu poznání (spáchali tím prvotní hřích) a Bůh je potrestal tak, jak řekl. Vyhnal je z Ráje a a od té doby Adam, Eva a všichni lidé stárnou a umírají.

Ztracený Ráj je spojen s **nesmrtelností**. Touha žít věčně je stará jako lidstvo samo. S touto touhou se setkáváme i v pohádkách.

Pohádka Panna věčně mladá _hovoří o královském synovi, který si přeje žít věčně. Vydává se proto na cestu, aby našel místo, kde není smrt a kde nic neumírá a kde je věčné mládí._

_Potká obrovského jelena, který mu říká, ať zůstane žít s ním, protože až jeho parohy dosáhnou nebe, teprve zemře. Princ odmítá. Přichází na poušť, kde je obrovská a hluboká propast. Na kraji sedí havran, který hází zrníčko písku za zrníčkem do propasti a žít bude tak dlouho, až propast zasype pískem. Ale ani s tím není princ spokojen a pokračuje ve své cestě. Potkává malého ptáčka, který sedí na obrovském stromě rostoucím až do nebe, se širokou korunou plnou listí. Ptáček každý den jeden lístek utrhne a shodí na zem. Až všechny lístky utrhne, zemře. Ale ani zde nechce princ zůstat a pokračuje ve svém hledání._

_Přichází ke krásnému zámku, v němž žije překrásná panna. Řekla mu, že takové místo, kde je věčný život a věčné mládí, na zemi není. Ale může zůstat s ní v jejím zámku, protože zde je věčné mládí. Ona sama je stará jako lidstvo samo, a nemá ani jednu vrásku. A tak bude žít až do skonání světa. To se princi líbilo a zůstal s ní. Žil v radovánkách a v hojnosti._

_Ale přeci se mu najednou zastesklo po domovině a rodičích. Rozhodl se, že je půjde navštívit. Vždyť uběhla jen krátká doba, co je pryč. Ale krásná dívka mu řekla, že čas u ní plyne jinak, než na zemi a tam už nikoho známého nenajde. On ale trval na svém. Dala mu tedy na cestu tři červená jablíčka. Až mu bude po ní smutno, ať je sní a ona si pro něho přijde a už se nikdy spolu nerozloučí._

Princ se pln očekávání vydal na cestu. Uviděl obrovský strom bez listí a ptáčka pod ním mrtvého. Jáma byla v poušti zasypaná a na hromadě písku ležel mrtvý havran. A také jelen byl už mrtvý a jeho paroží dosahovalo nebesa.

_Princ přijel na místa, kde bylo kdysi království jeho rodičů. Ale svět už nepoznal, nikdo ho neznal, o jeho rodičích nikdo nevěděl. A tak si smutně sedl na zem, vzpomenul si na pannu věčně mladou a zastesklo se mu po ní. Snědl první jablíčko a vrásky mu naskákaly po celé tváři, vlasy zbělely a narostly dlouhé bílé vousy. Snědl druhé jablíčko a ruce se mu roztřásly, srdce přestávalo bít, pocítil velikou slabost. Snědl třetí jablíčko a hlava mu spadla na prsa, oči se zavřely, ale ještě viděl, jak panna věčně mladá přijíždí na kočáru, chytá ho za ramena a do svého kočáru vtahuje. A lidé, co šli kolem řekli: „Hle, zemřel cizinec“. _

Skutečně, jen Smrt může být věčná a tudíž věčně mladá do konce všech dní.

Podobné téma nacházíme v pohádce O královně života. _Královský syn se velmi trápil nad tím, že všechno na světě jednou umře. Rozhodl se vydat do světa a hledat zemi, kde je věčný život. _

Na své cestě potkal krále, který každý den ulomil třísku z mohutného stromu, který byl stromem života krále a jeho rodiny. Až král ulomí poslední třísku, rodina i celé království nebude existovat. A to bude až za 600 let. Krásná králova dcera zvala prince, aby u nich zůstal. Odmítl, že bude pokračovat v cestě za svým cílem. Darovala mu šátek, který ho ponese vzduchem, aby rychleji pokračoval na své cestě.

_Princ se brzy dostal do krajiny, kde uprostřed stál mohutný kopec. Král této země každý den malou lopatkou nabral trochu hlíny do košíku. Až celý kopec přemístí, a to bude za 800 let, přestane království a jeho obyvatelé existovat. Ani zde nechtěl princi zůstat. Krásná králova dcera mu darovala prsten, kterým, když na prstu otočí, dostane se tam, kde si přeje být. Princ si přál být na konci světa. Za chvíli se ocitl před nádherným zámkem. Na jeho schodech seděla překrásná královna této země a držela v ruce závoj. Každý den na něm musela udělat jeden steh. Zavedla prince do velké síně, která byla naplněna jehlami. Až všechny jehly spotřebuje, a to bude za tisíc let, skončí ona i její království. Princ odmítl i její nabídku, aby s ní zůstal. Královna mu řekla, že místo, kde se neumírá, na zemi neexistuje. Ukázala mu na obloze malé a jasné světlo, jako drobnou hvězdičku. Podle mudrců je tam zámek nevýslovné krásy. Možná to bude místo, které princ hledá. Darovala mu svůj pás. Když ho vyhodí do vzduchu, udělá se z něho most, který ho dovede na to místo. Princ tak učinil._

Kráčel po mostě velice dlouho, až nakonec přišel k jasnému zámku. V něm ho přivítala krásná královna. Byla to královna Života a zámek bylo jediné místo, kde nikdo neumírá. Pozvala prince k sobě. Čas mu plynul v krásných radovánkách. Ale jednou se mu zastesklo. Chtěl se podívat na otce a matku, na království. Marně ho královna zrazovala. Nakonec souhlasila. Na cestu mu dala bílou lahvičku s vodou života a černou s vodou smrti.

Princ hodil pas směrem k zem a z něho se stal most, kterým došel do království, kde královna šila závoj. Byla mrtva. Postříkal ji vodou života a ona procitla. Prosila ho, aby ji znovu uspal, že byla životem unavená a že se ji dobře spalo. Takto pochodil i v dalších dvou královstvích, které předtím navštívil.

_Nakonec se dostal pomocí prstenu na místo, kde stávalo jeho rodné království. Ale tam byly jen bažiny a neproniknutelné lesy. Nic jiného mu nezbývalo, než se vrátit ke královně Života. Ale tu z černého lesa vyskočila kostnatá žena: „Jsem Smrt. Nikdo mi neunikne. A tebe jsem konečně našla také!“ Princ rychle otočil prstenem a přál si být u královny Života. Letěl rychlostí blesku, ale smrt mu byla v patách. Když už byl na prahu zámku královny Života, Smrt na něj dosáhla a roztrhla ho v půli. Ale to už královna Života na Smrt křičela, že k ní nemá přístup, ať ji vrátí tu půlku prince, kterou ji vzala. Ale Smrt nechtěla a tak se hádaly, až se nakonec dohodly, že půl roku bude kralevic odpočívat pod zemí a druhou půli pobývat v slunečním zámku u královny Života._

Tato pohádka připomíná svým koncem staré mýty o vegetačním cyklu přírody – znovuzrození na jaře, a spánek v zimě. O tom hovoří mýty mnoha národů. Např. řecký mýtus o Adónisovi, _do kterého se zamilovala bohyně lásky Afrodita i bohyně podsvětí Persefona. Žárlivý bůh války Ares, manžel Afrodity, se proměnil v kance a v této podobě Adónise_ __zabil. Nejvyšší bůh Zeus rozhodl, že jarní a letní polovinu roku bude Adónis trávit s Afroditou a druhou půli v podsvětí s Persefonou. __Adónis se takto stal symbolem koloběhu života přírody.

Jiný řecký mýtus o Deméter a Persefoně zpracovává také toto téma. _Persefona byla unesena Hádem, bohem podsvětí. Deméter, bohyně plodnosti země, svou dceru hledala a přestala dbát o přírodu. Příroda hynula. Nakonec se bohové rozhodli, že část roku bude Persefona trávit v podsvětí u Háda (podzim a zima) a na jaře a v létě bude se svou matkou. Když Persefona na jaře přichází ke své matce, příroda ožívá, vše roste, kvete, zraje._

Sumerský mýtus o bohyni plodnosti a války Inanny (mezopotámská Ištar) a jejího partnera Dumuziho (mezopotámský Tammuz) vypráví o tom, jak _Inanna sestoupila do podsvětí, kde vládla její starší sestra Ereškigal. Ta ji v podsvětí uvěznila. Inanna se může na zem vrátit jen tehdy, když za sebe pošle náhradu. Posílá za sebe Dumuziho. Ten ale naříká nad svým údělem a vládkyně podsvětí se nad ním smiluje. Může na zemi vždy strávit půl roku, když za něj toho půl roku jiný stráví v podsvětí. Jeho sestra tuto podmínku přijímá. A tak, když se vrací Dumuzi na zem, zem ožívá, stává se plodnou. Když se vrací do podsvětí, příroda přestává plodit._

Židovská pověst Víno z ráje _vypráví o bohatém kupci, který se chtěl napít vína z ráje, protože prodlužuje život a hojí všechny nemoci a neduhy. Obrátil se proto na rabína Chajima, aby mu pomohl toto víno získat. Ten mu to nakonec slíbil. Kupci řekl, že musí o půlnoci přijít k bráně hřbitova se dvěma vědry, třikrát na bránu zabouchat a zavolat, že ho Chajim posílá pro víno. Pak má obě naplněná vědra donést k němu domů. Nesmí se však přitom ohlédnout ani promluvit, jinak by se mu špatně vedlo._

Kupec tak učinil a když volal "Chajim si posílá pro víno", uslyšel svist ohromných křídel a přelévání vína do věder. Pak vědra popadl a utíkal k rabínova domu. Náhle uslyšel, jak se otevírají všechny hroby na hřbitově, a kvílení mrtvých, kteří ho žádali aspoň o jedinou kapičku. Kupec utíkal, ale slyšel, že hlasy ho dohání, cítil dotyky. Zachvátila ho hrůza.

Když uviděl dveře rabínova domu, rozběhl se k nim, ale na prahu zakopl a víno se z věder vylilo. Rozlítil se a zvolal "Nic vám nedám".Tu se do něho zarylo tisíce ostrých nehtů. Rabín však už stál v otevřených dveřích a kupec mu dopadl k nohám. Z rozedraného těla mu tekla krev. Rabín kupce ošetřil a zeptal se ho, zda ještě stojí o víno z ráje. "Už ne, rabi," řekl kupec.

Někteří ale poukazují na druhou stránku přání získat nesmrtelnost v duchu myšlenky „Dávej si pozor na vyslovená přání, mohou se ti splnit“.

{empty}J. R. R. Tolkien (1892 – 1973), náš novodobý tvůrce mýtů, ve svém díle (Pán prstenů, Silmarillion, Hobit aneb cesta tam a zpátky) se také zabývá touto otázkou. Tolkienovi lidé a hobiti jsou smrtelní, elfové nesmrtelní.

Ti, kteří tolkienovo dílo studovali do hloubky, upozorňují, že většina elfů lidem závidí, že mohou zemřít, a většina lidí__ __elfům závidí jejich nesmrtelnost. Když tělo lidí zemře, jejich duše opustí Ardu (Zemi). Nevědí, co se s nimi po smrti stane. Elfí tělo může také zemřít (opotřebování, zranění). Elfové ale vědí, že jejich duše zůstane „uvnitř okruhu světa“ (vytvořeno První hudbou Ainur, Svatých), ze kterého se nemohou vymanit. Duše lidí ano. Smrtí se vymaní z bolestí a zoufalství tohoto světa

Smrt je darem Ilúvatara, stvořitele, lidem. Tento dar lidem umožňuje nebrat život jako samozřejmost. S tím souvisí dar svobodné vůle. Lidé umírají, ale je jim Ilúvatarem (Nebeský otec) přislíbeno, že vstoupí do Druhé hudby Ainur (Svatí).

Elfové jsou nekonečným životem znavení, protože i když jejich tělo zemře, získají nové (reinkarnace), ale všechny vzpomínky jim zůstávají. A prožívat nekonečný smutek, je velmi trýznivé. Je proto pochopitelné, proč Arwen (elfka) volí Aragorna (člověk) a jeho smrtelný osud. Dává tím přednost konečnému životu plnému hluboké lásky před nekonečným životem bez ní. Oba přijímají smrt, protože to, co pak přijde, bude požehnáním.

Lidstvo tedy provází život a smrt v těsném sepětí. Vítězí však představa, že smrt není „konečná „ ale „přestupná" stanice do další formy existence.

[quote, J. Campbell]
____
Smrt a narození
jsou jen prahy přechodu závojem
sem a tam.
____

Smrt je vždy symbolicky i fakticky začátkem něčeho nového. To umožňuje
jeho nesmrtelná část – duše. Proto bývalo a bývá zvykem, když někdo
zemře, otevřít okno, aby duše mohla odejít (potom se okno hned zavřelo,
aby se nemohla duše vrátit), zapálit svíci (dříve hromniční) jako světlo
pro duši na cestu k věčnosti.

[quote, A. C. Clark]
____
Magie je lidstvem nepochopená věda.
____

**ZRCADLO **hraje významnou roli. Protože zrcadla odrážela podobu toho, kdo se do nich díval, působila tajemně, vševědoucně a přičítala se jim magická moc (např. kouzelné zrcadlo v pohádce O Sněhurce a sedmi trpaslících). Jako předmět s magickou mocí se zrcadla používala k věštění, odhalování ne-lidských bytostí, ale také ke škodění. Proto se do zrcadla neměli dívat děti, šestinedělky a nemocní.

V čínském příběhu Starožitné zrcadlo __nás její dočasný majitel seznamuje se situacemi, kdy mu např. pomohlo odhalit dívku, která byla ve skutečnosti liščím démonem; paprsky od něj odražené pronikaly zdí; prosvítily vnitřnosti člověka a tak odhalily jeho nemoc. Toto zrcadlo se samo rozhodovalo, kdy svého majitele opustí.__

Zrcadla se v Japonsku vždy těšila mimořádné úctě jako symbol bohyně slunce a k uctění památky předků. Podle japonského mýtu, _když odcházel božský Ninigi z nebes na zem, dostal od bohyně slunce Amaterasu několik magických předmětů, mezi nimiž bylo zrcadlo. Bohyně Amaterasu mu řekla, že to zrcadlo má uctívat jako její duši a tím i ji samotnou. Jeho vnuk se stal prvním japonským císařem a toto zrcadlo se stalo součástí obřadů japonských císařů a symbolem jejich moci._

V Andersenově pohádce Sněhová královna se vypráví o tom, že _zlý čaroděj stvořil kouzelné zrcadlo, které mělo moc pokřivit obraz toho, kdo se do něj díval. Když se snažil zrcadlo dostat do nebe, spadlo mu a roztříštilo se na mnoho malých kousků, které se mohou dostat člověku do oka nebo srdce. Takový člověk pak vidí svět i lidi pokřiveně a srdce má zmrzlé, bez citu. Chlapci Kayovi se takové střepy dostaly do oka a srdce. Sněhová královna, která ho k sobě odnesla, mu dává za úkol znovu složit ze střípků původní zrcadlo. Kaye nakonec zachraňuje jeho kamarádka Gerda, které se podaří svými slzami odplavit střepy z jeho oka i srdce._

Zrcadlům se věnovala velká pozornost po stránce výzdoby. První skleněná zrcadla byla velice drahá, proto rozbité zrcadlo mělo přinést sedm let smůlu a neštěstí (sedm let je doba potřebná k obnově duše).

Věřilo se také, že rozbité zrcadlo věští smrt do roka někoho z rodiny. Střepy zrcadla jsou symbolem bolesti ze smrti, kterou zrcadlo ukázalo.

V zrcadle se každý vidí takový, jaký je. Není v něm ale vidět ďábel, upíři, démoni, čarodějnice a jiné nadpřirozené bytosti, protože nemají duši.

{empty}J. Mahen ve své pohádce Mlynářův student _vypráví o studentovi, který se zamiloval do krásné rusalky a chtěl v ní probudit lidskou duši, aby i ona ho milovala jako on ji. Až mu nakonec bylo povězeno, že rusalka může získat lidskou duši, když oni dva budou spolu bydlet dva roky a slova na sebe nepromluví._

A tak studen mlčel, i když začala rusalka, které do té doby nepromluvila, mluvit. Jen se na ni díval. Postupně se stěhovala jeho duše do jejího nitra a zatímco ona se stávala člověkem, on scházel, stárnul.

Jenže duše se nemůže narodit ve druhém, když by tento netrpěl. V den, kdy dostala rusalka duši, student umřel a rusalka poznala zoufalost a smutek, který do té doby neznala.

Podle pověry to, co se zjevuje v zrcadle, je duše. Proto mají být zrcadla zarámovaná, aby k ní nemohl ďábel. Právě proto se i v domě, kde někdo zemřel, zakrývala zrcadla. Tím se zabránilo tomu, aby byla duše v zrcadle uvězněna a nemohla odejít do ráje.

Jiná pověra říká, že se zrcadla zakrývají z toho důvodu, aby se zabránilo duši mrtvého hledat v zrcadle další duši, kterou by si odvedla.

Věřilo se také, že duše člověka může vstoupit do zrcadla. Krajina za zrcadlem byla považována za klam, kde není nic takové, jak se jeví.

Svět za zrcadlem byl také zásvětím (za světem), kde se může duše setkat s těmi, co již zemřeli, kde může být zdravá, krásná, vítána, a přesto zůstat v ní bylo pro duši ohrožující.

Dříve funkci zrcadlo plnila vodní hladina, vyleštěný štít apod. Ve staré Indii i Řecku se zakazovalo dívat se na svůj obraz na hladině, aby nemohli vodní duchové stáhnout zrcadlící se podobu člověka (tedy jeho duši) pod hladinu. Člověk bez duše by totiž zemřel.

Také se mělo za to, že se na vodní hladině díváme na svého zrcadlového dvojníka, na sebe sama a tudíž se musíme sami se sebou utkat. Takové setkání přináší často jedinci zkázu (např. starořecký mýtus o Narkissovi/Narcisovi, který se zamiloval do svého obrazu na hladině tak silně, až ho to stálo život). Jedinec totiž může v klamech a iluzích uvíznout.

Zrcadlo jako magický nástroj může probouzet sílu duše, intuici, reflexi, slouží k ochraně, ale i klamu a sebeklamu, pomáhá při sebepoznání a koncentraci. Může dát nahlédnout do minulosti, přítomnosti i budoucnosti. V rituální a magické praxi slouží jako brána do jiných světů.

Na druhé straně různé bytosti se mohou přes zrcadlo dostat i do našeho reálného světa. Proto se doporučovalo, jako ochrana proti nočním můrám, na noc zakrýt zrcadlo v místnosti, kde se spí.

Zrcadla jsou silným ochranným nástrojem, protože mohou spoutat světlo a vracet jej zpět jako odraz. Ve feng-šuej (umění bydlení) se používají ke zvyšování energie v místnosti, jako ochrana do oken, aby zadržely negativní energii, která se chce z venku dostat dovnitř.

Zrcadla (zejména vodní plochy za úplňku a vypouklá zrcadla) mají významné místo při rituálech, k rozluštění znamení, pro získávání pohledu do budoucnosti a do jiných světů, vysílání signálů do jiných světů, k jejich přijímání, spojnicí světa živých se světem mrtvých.

Všeobecně je zrcadlo symbolem sebeuvědomění, sebezpytování, moudrosti, učenlivosti, marnivosti a sebelásky.

**BRÁNY/DVEŘE** jsou symbolem přechodu, vstupu do neznáma, do budoucnosti, do jiného světa, do tajemna, do nových možností a nových začátků, nadějí.

Otevřené dveře nás zvou ke vstupu, nemáme se čeho bát.

Zavřené nám vstup odmítají - ještě nenadešel pravý čas, vstoupit násilím je nebezpečné.

Polootevřené nám naznačují, že rozhodnutí ne/vstoupit musíme udělat sami a to včetně všech následků.

Dveře jsou ale zejména symbolem smrti - přechodu z onoho světa na onen svět. Otevřené dveře - pozvání k dalšímu životu po smrti, zavřené dveře - smrt bez možnosti pokračování, polootevřené dveře - naděje na posmrtný život.

Egyptské sarkofágy byly často zdobeny zádušními texty a modlitbami, zejména Texty rakví a Knihou bran. Římské a Řecké sarkofágy byly často zdobeny dveřmi, mnohdy pootevřenými.

Dle křesťanů do království nebeského vede úzká cesta končící těsnou bránou (často zobrazovanou architektonicky), do pekel vede cesta široká končící širokou bránou (často znázorňovanou jako doširoka otevřená tlama monstra).

Významnou roli také hraje strážce dveří či brány. On vlastní klíče a rozhoduje, koho nechá vstoupit.

Římský bůh Janus, jeden z nejstarších bohů, je ochránce dveří a bran, začátků a konců. Je zobrazován se dvěma tvářemi. Jedná se dívá dopředu (budoucnost), druhá dozadu (minulost). Představuje symbol změny, přechodu, že konec jednoho je počátkem druhého a že minulost přechází v budoucnost. Jeho atributem byly klíče od brány slunovratu: letní slunovrat je bránou lidskou, symbolizuje slábnoucí sílu slunce - je to Brána podsvětí; zimní slunovrat je bránou božskou, symbolizuje narůstající sílu slunce - je to Brána nebe.

Etruskové po smrti také vstupovali do podsvětí dveřmi/bránou. Očekávala je tam bohyně Vanth s pochodní v ruce. Doprovázela mrtvé a pochodní jim svítila na cestu. Vlastnila klíč, kterým bránu do podsvětí odemykala.

Ve většině kultur má velký symbolický význam už práh dveří. Překročení prahu dveří znamená vstup do nového světa/životní fáze. Proto má překročení prahu symbolický význam v různých obřadech jako svatební, pohřební, zasvěcovací. Cílem těchto obřadů je uctění a usmíření domácího ducha/strážce.

Starým Slovanům často pomáhal vybírat vhodné místo k usídlení had, o kterého pečovala tzv. bogyňa. Kde se had stočil, zarazili vedle něj vpravo a vlevo kůl. Tento prostor vymezený dvěma kůly byl označen jako "prág" (dnes práh). Práh měl význam dnešního "základního kamene." Do vykopané díry bogyně vložila obřadní předměty, ty se překryly dubovým břevnem. Proti prahu byl vytyčen "svatý kout" a "ohniště." V dokončením domě se pod prahem usídlil had hospodáříček a stal se strážcem rodu.

Mnozí si z nás pamatují na dětskou hru, kdy dvojice dětí vytváří spojenýma rukama bránu, ostatní ji podcházejí a zpívají:

[verse]
____
Zlatá brána otevřená,
zlatým mečem podepřená,
kdo do ni vejde,
hlava mu sejde,
ať je to ten nebo ten,
praštíme ho koštětem.
____

Poslednímu, který bránou projde při závěrečném slově, ti dva, co tvoří "bránu" ho symbolicky svýma rukama "uvězní" a dotyčný vypadává ze hry. Podle některých autorů se jedná ozvěnu dávného rituálu obětování znovu se rodícího vegetačního božstva.

Významný sochař A. Rodin (1840 – 1917) v r. 188O byl vybrán, aby vytvořil portál plánovaného Muzea dekorativního umění. Muzeum nebylo nikdy postaveno, přesto Rodin mnoho let pokračoval ve své práci na sousoší Brána pekel, které bylo pro něj vyjádřením lidského osudu. Inspirací mu byla Danteho Božská komedie. Brána je tvořena volným seskupením figur (asi nejznámější je Myslitel).

Sochař Quido Kocián (1874 – 1928) ve svém symbolickém reliéfním díle Zapovězená láska znázornil pootevřené dveře, ve kterých stojí v objetí chlapec a dívka. Nad nimi číhá Smrt, symbol pomíjivosti lidského života, v podobě kostlivce. Dílo vzbuzuje dojem, že dívka je tou, na kterou Smrt čeká. Její objímající ruka ochable visí a dívka se nachází v podstatě již spodní částí těla za dveřmi.

*SVÍČKY* se staly nedílnou součástí rozloučení se zesnulým a také vzpomínkou na něj („Světlo věčné ať mu svítí“). Hořící svíčky u lože zemřelého mu osvětlovaly cestu na onen svět. Světlo svíce nás doprovází (při křtu - kmotr drží hořící svící v ruce), vyprovází nás (při rozloučení se zesnulým hoří svíce) a podněcuje vzpomínku na nás, když zemřeme (hořící svíčky na hrobech).

V katolické církvi počet použitých svící odpovídá významu obřadu. Katolická církev používá svíce z včelího vosku. Kořeny tohoto zvyku pravděpodobně spočívají v dávném zvyku uctívat včely, jelikož se věřilo, že přišly z Ráje. U nás bylo zvykem oznamovat včeličkám a stromům smrt hospodáře.

Věřilo se, že zbytky svící použitých při pohřbech a posvěcených na Hromnice (2. února), pomáhají při léčbě popálenin. Namodralý plamen svíčky znamenal, že se kolem ní pohybuje duch. Víra v ochrannou moc svíček byla a je stále živá (ochrana proti nebezpečí, blesku, bouři, epidemiím atd.), také víra v zprostředkování spojení s tím, na koho se obracíme (mše, magické rituály, mystéria atd.).

Svíčky svým světlem a teplem navozují stavy klidu, uvolnění, ochrany, harmonie. Symbolizují také spojení člověka s Kristem. Mohou být tedy komunikačním prostředkem k vyjádření vnitřního postoje.

Zapálení svíčky bylo vždy považováno za něco posvátného, mystického, magického, protože symbolicky představuje přírodní a prvotní element ohně a ten náleží Bohům – vnáší Světlo do Temnoty, představuje světlo Slunce, světlo Ducha, pozitivní kosmickou energii, je symbolem života, tedy Stvoření. Proto se věřilo, že se má svíčka zapalovat pravou rukou - přináší to štěstí. Jednou zápalkou se má zapálit jen jedna svíčka. Věřilo se, že pokud jednou zápalkou zapálíme více svíček, přinese to smůlu.

Světlo je symbolem života (tma symbolem smrti), a tak i svíčka je symbolem života. Proto se svíčka nemá sfoukávat ale uhasit, nebo nechat dohořet. Výjimku tvoří svíčky na narozeninovém dortu. Zde jejich sfoukáváni oslavencem je symbolickým loučením se s odžitými roky a očekávání nových let, pro které svíčka „tam někde“ hoří.

Svíčka je ale také symbolem lidského života pro svou pomíjivost a křehkost (protože ji sfoukne i malý závan větru).

**ZVÍŘATA a PTÁCI** představují významný zdroj symboliky, která je běžně využívaná v rozhovorech (je věrný jako pes, je špinavý jako prase, je moudrá jako sova, je silný jako býk, krade jako straka atd.). Jejich význam pro člověka má mnoho aspektů. Jako zdroj potravy, společníci, pomocníci v práci, zdroj inspirace pro technické nástroje, astrologické symboly, duchovní průvodci apod. Člověk jim záviděl rychlost, sílu, schopnost létat, vidět ve tmě, neslyšně se pohybovat …

Některé si spojoval se schopnosti věštění, ohlašování smrti, spolkem s ďáblem, přiřazoval je svým božstvům, přírodním silám. Ptáci a zvířata na erbech a vlajkách symbolizují moc a svobodu.

Staré kultury věděly, že ve chvíli smrti přijdou průvodci (*psychopompové* – průvodci duší), kteří duši doprovázejí do jiného světa. Nejsou Smrtí, ale průvodcem. Nesoudí, ale doprovázejí. Mají různou podobu: kůň, jelen, pes, pták atd. Někteří mohou být současně průvodci i zvěstovatelé odchodu (např. sova, vrabec, havran). Jako průvodci jsou vnímání i Vanth, Anubis, Horus, Hekaté, Chárón, Hermes/Merkur, andělé. Žijícím psychopompem je šaman, který dokáže dohlédnout na druhý břeh (onen svět).

Ptáci jsou často symbolem lidské duše, poslové mezi nebem a zemí. Staří Egypťané věřili, že když člověk zemře, vylétne z jeho těla duše v podobě ptáka s lidskou hlavou. Bohové často na sebe brali podobu ptáka (egyptský bůh Thovt zobrazován jako muž s hlavou ibise, v křesťanské symbolice holubice znázorňuje Ducha svatého).

Uzbecká pohádka Sumbul a Gul __hovoří o bajovi, který se po smrti své ženy znovu oženil. Jeho mladá žena jej přiměla, aby z domu vyhnal syna Gula. Ale jeho bratr Sumbul nechtěl doma zůstat bez bratra, a odešel za ním. Našel ho za městem, ležícího při cestě, vysíleného hladem. Sumbul šel hledat něco k snědku. Gul spal a tu k němu přiletěl velký bílý pták, sedl si mu na hlavu a vdechl do sebe jeho duši.__

_Když se Sumbul vrátil, našel bratra mrtvého. Tak se vydal na cestu sám. Dostal se do města, kde si volili nového krále. Vypustili ptáka štěstí a ten si sedl Sumbulovi na hlavu a tak se stal králem._

_Jednou královský lovec zastřelil velkého bílého ptáka a když k němu přistoupil, uviděl vstávat chlapce. Byl to Gul. Jeho duše se ze zabitého ptáka vrátila do chlapcova těla a on ožil._

*Fénix* je mýtický tvor, který si na konci svého, několik stovek i tisíce let dlouhého života, postaví hnízdo, shoří na něm a pak znovu vstane ze svého popele. Proto se stal symbolem slunce, znovuzrození, vítězství nad smrtí, nesmrtelností, věčností.

*Havran,vrána,krkavec* – chytří ptáci černého peří s výrazným krákavým hlasem. Často se zaměňují. Zejména havran a krkavec. Na bitevních polích hodovali černí ptáci na mrtvolách (byli to hlavně krkavci). Tak se tito ptáci stali zejména v Evropě a Orientě symbolem smutku, zmaru, smrti, předzvěstí nemocí a války. Jsou považováni za strážce tajemství, podsvětí a světa mrtvých.

Řecká měsíční bohyně Hekaté se může zjevovat v podobě havrana, vrány, krkavce. Irská trojjediná bohyně války a záhuby Macha, Badb a Morrígan má schopnost proměnit se ve vránu či havrana a ti byli spojování se smrtí. Když hrdina Cú Chulainn umírá v boji, na důkaz jeho smrti mu na rameno usedá v havraní podobě Morrígan.

Ve velšském mýtu o Branwen a jejím bratrovi Bendigeidfranovi (požehnaný havran) se __Branwen (bílá havranice) vdává za krále Irska. Jeden z jejich bratrů se svatbou nesouhlasí a proto krále urazí – zmrzačí mu koně. Bratr Bendigeidfran tuto roztržku zažene tím, že králi daruje kouzelný kotel, který dovede zabité bojovníky oživit.__

_Branwen odchází s manželem do Irska, avšak manžel na urážku nezapomněl a zachází s ní jako s otrokyní. Branwen o tom zpraví svého bratra a ten s vojskem putuje do Irska. Bendigeidfran je tak obrovský, že přes Irské moře se jen přebrodí. Jeho vojsko zvítězilo. On sám byl ale zraněn a když se blížila jeho smrt, věštil svým druhům, co se stane v příštích 87 letech. Nechal svou hlavu pohřbít v Londýně tam, kde dnes stojí Tower, obletovaný_ _havrany. Pověst říká, že pokud se počet těchto havranů sníží pod číslo šest, bude to znamenat pád monarchie._

V Japonsku byl havran poslem bohů, v Persii byl zasvěcen bohu světla a slunce. V severské mytologii nejvyššího boha Ódina doprovázeli dva havrani: Hugin (myšlenka) a Munin (paměť), kteří mu přinášeli zprávy z celého světa.

Legenda praví, že kdysi měl havran bílé peří a krásný hlas. Takže lidé naslouchali jeho zpěvu a zapomínali naslouchat kněžím. Proto mu Bůh dal černé peří a krákavý hlas.

Ovidius píše, že __havran měl původně sněhobílou barvu. Prozradil Apollónovi, že jím milovaná dívka Korónis se milovala s Ischyem. Apollón se nahněval a zabil ji šípem aniž tušil, že je s ním těhotná. Když to zjistil, vyrval z jejího těla chlapce – Asklépia (budoucí bůh lékařství) a dal ho na vychování kentauru Cheirónovi. Rozzlobil se na havrana a potrestal ho tím, že mu zčernalo peří.__

**Had** je mnohostranný a vícevrstevnatý symbol: je symbolem obnovy a znovuzrození (svlékání kůže), léčení (jeho jed může léčit), smrti a zkázy (jeho jed může zabít), strážcem vchodu do jiného světa (žije pod zemí), plodnosti (jeho tvar připomíná penis).

Je symbolem plodivé mužské síly a jeho přítomnost je téměř univerzálně spojována s těhotenstvím. Doprovází všechna ženská božstva a Velkou Matku.

Je tedy symbolem solárním, podsvětním (chtonickým), sexuálním, pohřebním, úzce spojován s představami života a smrti. Protože žije pod zemí, je ve styku s podsvětím a tudíž má přístup k silám, vševědoucnosti a kouzelné moci mrtvých. Je atributem říčních božstev. Hadi a draci jsou strážci prahu, pokladů, ezoterického vědění. Jsou vzývání při zaříkávání mrtvých, kteří přepluli vody smrti.

Z kosmologického hlediska je had praoceán, z něhož se vše vynořuje a vše navrací, počáteční chaos. Jako Úroboros (had zakousnutý do svého ocasu) je počátkem i koncem, symbol cyklů. Hinduistický bůh Višnu leží na smyčkách tisícihlavého hada Šéši plujícího vesmírnými vodami a sní. Dva vzájemně se obtáčející hadi znamenají čas a osud, symbolizují protiklady dualismu, které jsou sjednoceny. Aztécky opeřený had představuje slunce, ducha, dech života, déšť, vítr, hrom, prostředníka mezi bohem a člověkem. V židovské nauce je symbolem zla a pokušení, duše zavržených v šeolu, říše mrtvých. V Egyptě je kobra symbolem nejvyšší královské moci a moudrosti.

*Holubice* je symbolem míru, naděje a duše, která opouští mrtvé tělo a přechází z jednoho stavu bytí do druhého. V křesťanství je symbolem duše a Ducha svatého. Ve starověku a středověku symbolizovala nesmrtelnou duši. Posvátné holubice jsou spojovány s pohřebními kulty. Holubice s palmovou/olivovou ratolestí symbolizuje vítězství nad smrtí. Bílá holubice představuje spasenou duši. V řecké mytologii znázorňovala bohyni lásky Afroditu. Hinduistický bůh smrti Jama má za posly sovy a holubice.

V mnoha pohádkách se setkáváme s tím, že někdo (mluvící kůň, přítel atd.) pomáhá nezištně hrdinovi vyřešit uložené nebezpečné úkoly. Když se hrdina konečně ožení s princeznou, jako odměnu žádá jeho pomocník, aby mu sťal hlavu. Z těla vyletí holubička (duše již dříve zemřelého pomocníka) a děkuje za vysvobození.

*Jelen* patří k velice významným a rozšířeným kultovním zvířetem od dávných dob. Jeho kult souvisí s cestou do jiného světa ( je psychopompem – průvodce do podsvětí či jiného světa), sluncem a lovem. Germané zabalovali mrtvé do jejich kůže a věřili, že mrtví se mohou zjevit v podobě jelena.

Ve slovanské i keltské mytologii víly často jezdí na jelenu. Jelen je spojován s božstvem lovu. Keltský bůh Cernunnos, slovanský bůh Veles jako „páni zvěře" byli často zobrazování s parožím na hlavě.

Řecká bohyně lovu Artemis proměnila lovce Aktióna v jelena a nechala ho roztrhat jeho vlastními psy proto, že ji spatřil nahou, když se připravovala ke koupeli.

**Kůň** má speciální místo v srdci člověka, který jej považuje za ušlechtilé zvíře, důvěřuje jeho instinktům, vždy na něj spoléhal v době válek i na cestách. Je pro něj symbolem rychlosti, svobody. Kůň je atributem mnoha bohů, např. bohů – bojovníků, bohů – lovců, táhne vůz slunečního boha Apollóna.

Slovanskému Svantovítovi byl zasvěcen bílý kůň. Bílý kůň je častým symbolem života. Bílý posvátný kůň keltské bohyně Epony (koňská bohyně, bohyně plodnosti) byl vtělený bohatýr, obdařený věšteckou silou. Epona bývala zobrazována jak jede na bílém koni, nebo jako bílá kobyla.

Také Horymírův kůň byl bílý šemík.

Bílý kůň je prostředníkem mezi pozemským a oním světem, bývá také zapřažen ve svatebním kočáru a v pohádkách přichází princ na bílém koni osvobodit princeznu. Pohřební vůz je tažen černými koňmi, na černých koních s rudýma očima jezdí démoni.

Za starých časů byl kůň obětován na hranici s ostatky svého pána. Hranice symbolizovala zlatou bránu slunce, kterou duše reka vchází do síně věčnosti k dalším mrtvým rekům.

Kniha Zjevení svatého Jana se zmiňuje o jezdcích Apokalypsy. Jsou to čtyři jezdci na koních, kteří přinášejí lidstvu zmar a zkázu: na bílém koni sedí Antikrist, na ohnivě rudém Válka, na černém Hladomor, na mrtvolně bledém Smrt.

**Netopýr** má významnou úlohu spjatou se smrtí u Indiánských kmenů. Většinou je symbolem smrti a podsvětí. V podsvětí Xibalba je Dům netopýrů. Jako noční zvíře se v Evropě netěšil dobré pověsti - byl spojován s čarodějnictvím, nečistými silami, upírstvím a ďáblem. Satan bývá znázorňován s netopýřími křídly.

**Pes** patří mezi první divoké zvíře, které si člověk ochočil. Jeho symbolika je rozmanitá a protikladná. Je symbolem síly, oddanosti, ochrany, ostražitosti, věrnosti ale také nečistoty, neřesti, ponižující nadávkou (např. v islámu). Je také symbolem podsvětí, průvodce duši zemřelých, strážce vstupu do podsvětí (v antické mytologii trojhlavý Kerberos, lat. Cerberus). Legenda říká, že __matkou Cerbera byla Echidna (napůl žena a napůl had) a otcem obr Týfón. Jako štěně utekl z domova, kde ho zachránil Hádes před útokem Harpií. Ty zahnal do Tartaru a z Cerbera udělal strážce podsvětí__.

Germané věřili, že zločinci, vrahové, křivopřísežníci apod, byli svrženi do podzemí na pláž mrtvých, kterou hlídal pekelný pes Garm. V severské mytologii byly Valkýry, které přiváděly duše hrdinů padlých na bojišti do Valhally, doprovázeny psy. Germané věděli, že psi díky svým smyslům cítí a slyší věci, které jsou za hranicemi lidského vnímání. Věřili, že pes je schopen vidět duchy.

Aztékové věřili, že Xolotl s psí hlavou, který doprovázel slunce na jeho noční poutí podsvětím, stvořil prvního člověka. Do hrobu zemřelého se pak ukládali psi, aby mrtvému ukázali cestu na onen svět. Mayové pohřbívali psa s jeho pánem, aby jej doprovázel posmrtným světem. Starý perský obyčej přivést psa ke smrtelné posteli, aby se umírající mohl psu podívat do očí, spočíval ve víře, že pes je průvodcem duše.

Pes provází ženská božstva (zde symbolizuje uzdravování - lízání ran, lásku k dětem, plodnost) i mužská božstva (zde symbolizuje lov, boj a smrt). Řecká bohyně noci Hekaté má jako doprovod černé psy. Psi ji byli obětováni na křižovatkách cest. Asklépios, bůh lékařství, býval zobrazován jako starší muž opírající se o hůl ovinutou hadem, kterého doprovázel pes. Čtyřoký pes symbolizuje hinduistického boha mrtvých Jamu. Egyptský bůh mrtvých Anubis byl zobrazován s hlavou psovité šelmy.

Příslovečná je psí věrnost. Pes je také symbolem ochrany žen a dětí. Hovoří o tom také velšský příběh o psu Gelertovi. B__yl to pes prince Llywelyna. Když se jednou princ vrátil domu z lovu, přiběhl mu jeho pes celý zakrvácený naproti. Princ běžel do dětského pokoje. Často nechával svého syna hlídat Gelertem. Ale syn v pokoji nebyl, jen všude kolem byla krev. Princ v hněvu propíchl psa mečem. Najednou uslyšel křik svého syna. Našel ho schovaného a bez zranění. Vedle něj ležel mrtvý obrovský vlk. Princ litoval své prchlivosti a svému psu nechal zbudovat velkolepý hrob__.

Známá je legenda týkající se souhvězdí Orion a Velkého a Malého psa. _Do lovce Oriona se zamilovala bohyně Artemis. To se nelíbilo jejímu bratrovi Apollonovi a chtěl se Oriona zbavit. Jednou ho uviděl plavat daleko v moři. Vyzval svou sestru, zda dokáže lukem trefit malý černý bod daleko v moři._ _A ona se samozřejmě trefila. Když zjistila, že zabila svého milovaného, vyzdvihla ho jako souhvězdí Orion na oblohu. Jeho dva věrní psi ho však neustále hledali a tak i je vyzdvihla na oblohu jako souhvězdí Malý a Velký pes._

**Sova** tím, že je nočním ptákem, má vynikající zrak, žije samotářsky, létá neslyšně a je opředena mnohým tajemstvím, se stala symbolem prastaré moudrosti, nositelkou proroctví a mystických znalostí, víry, že má spojení s okultními vědami a magii. Stala se symbolem moudrosti, která překonává temnotu nevědomosti (je atributem řecké bohyně moudrosti Athény, společnice bohyně matky Danu – pramáti keltských bohů). Byla také spojována s tmou, smutkem, smrtí a vnímána jako průvodkyně podsvětím. Zejména v Egyptě, Japonsku a Indii byla ptákem mrtvých. Pro Indiány kmene Hopi je jeden druh sýčka symbolem Boha smrti. V Africe je poslem zpráv mezi šamanem a duchovním světem.

Někdy byla zpodobňována na náhrobcích jako symbol plodně prožitého dlouhého života.

V raném křesťanství jako noční pták je však symbolem duchovní temnoty, ďábla. Její houkání (zejména sýčka) prý předpovídá nebezpečí a smrt.

Jeden z keltských mýtů hovoří o květinové ženě Blodeuwedd. _Tu stvořil z květů čaroděj Gwydion pro Lleua, který byl proklet a nemohl se oženit s lidskou ženou. Ovšem ona se svým milencem svého manžela zavraždila a čaroděj ji za trest zaklel v sovu, odsouzenou lovit osamoceně a v noci._

**RITUÁL** je v podstatě slavnostní obřad, provázený speciálním individuálním nebo kolektivním chováním, které je standardizováno, a bývá založeno na stanovených nebo tradičních pravidlech. Jeho význam spočívá zejména v hlubokém prožitku, který umožňuje zvýraznit významné životní chvíle, zpracovat náročné životní situace, usnadnit přechod (a uvědomění si ho) životními etapami (např. dospělost, svatba, narození, smrt, povýšení v práci, vyznamenání), stmelit příslušnou skupinu, navodit společné duševní rozpoložení. Důležitou součástí jsou symboly.

Každá kultura má odlišné pohřební rituály. Jejich základním významem je pomoci zemřelému správně přejít na druhou stranu, zajistit, aby byl mrtvý přijat do světa zemřelých, rozloučit se zemřelým, pomoci pozůstalým vyrovnat se se ztrátou milovaného člověka a očistit pozůstalé od kontaktu se smrtí.

Pohřební rituál umožňuje si uvědomit, že smrti konkrétní osoby nekončí její vliv na náš život. Nejen Slované spatřovali v zemřelých předcích ochránce, kteří pečovali o štěstí a blaho rodiny (dědové se stávali strážnými duchy domu). Podle Slovanů osud člověka záležel především na rodu (tj. dědech a předcích) a na matce (rožanice, rodička). Toto propojení s předky naznačuje, že jedinec odpovídá za svůj život společenství předků. Tato zodpovědnost za svůj život se pak stává zřetelnou ve vztahu k smrti a smrtelnosti.

V pohádkách se dovídáme, že zemřelý se musí po tři dny a noci po smrti střežit. Přitom je důležité, aby u jeho hlavy hořely svíčky a aby se za něho vybraný člověk modlil či pronášel vybraná zaklínadla. Dělo se tak proto, že panoval strach, aby se těla mrtvého nezmocnil démon, což mu umožnilo vloudit se mezi lidi. Jde o strach, aby "oživlý mrtvý" neškodil lidem, ale také strach o mrtvého, aby mu nebyla překažena cesta na onen svět.

Židovská pověst Kadiš _o stařičké Jutele, která byla velmi zbožná. Věděla, že si pro ni už brzy přijde smrt, ale velice ji trápilo, že nezůstal ani jediný mužský příbuzný, který by se za ni pomodlil kadiš, až ona zemře. Manžel i synové ji zemřeli, žádné příbuzné neměla. Její vnučka se provdala velice daleko do Řezna a byla tam i pochovaná. Jutele nevěděla, zda po ní nezůstal syn, který ani neví, že má v Praze prabábu._

Když Jutele umřela, rabín přečetl její závěť. Své značné jmění i dům měl připadnout jejímu pravnukovi, pokud se on sám přihlásí. Hledat ho nemají. Pokud se nepřihlásí do desíti let, majetek připadne obci.

V Řeznu žil chudý krejčí Salomon. Nikoho na světě neměl a nevěděl nic o své prabábě v Praze. Protože třel bídu s nouzí, ani se neoženil.

Jednou v noci ho probudil pláč, ale nikoho neviděl. "Kdo jsi a proč pláčeš?" zeptal se mladík tmy. "Jsem tvoje prabába a přišla jsem tě poprosit, aby ses za mě zítra v synagoze pomodlil kadiš. Jsi poslední z mé rodiny, koho o tuto službu mohu poprosit." Mladík ji to slíbil a ucítil pohlazení po tváři. Druhý den měl ale tolik práce, že na to zapomněl.

A druhou noc ho opět jeho prabába vzbudila a prosila ho, aby se za ni pomodlil kadiš. Opět ji to slíbil a cítil, jak ho stará ruka něžně pohladila po tváři. Následující den ho majitel dílny proháněl ještě více. Mladík se ale neustále vracel ke svému nočnímu zážitku a nevěděl, co si má myslet.

Třetí noc o půlnoci ho opět probudil pláč a světlo v jeho světničce. U postele stála smutná drobounká stařenka a plakala. Pak Salomona pohladila po tváři. Sedla si na stoličku a vyprávěla mu o sobě. Pak mu řekla, aby se za ni pomodlil kadiš a pak se vydal do Prahy k jejímu hrobu. Ona se už o něho postará, aby nežil v takové chudobě.

Následujícího dne mladík splnil babiččino přání a vydal se do Prahy. Dostal se k jejímu hrobu a modlil se před ním. Tu k němu přistoupil rabín, který se o mladíkovi dozvěděl a pak ho seznámil se závětí své prababičky. Rázem byl z něho bohatý mladý muž.

Slunce je všeobecně uctíváno jako zdroj života a naděje. Východ je směrem zrození a znovuzrození, dětství, mládí, štěstí, energie. Řada náboženských obřadů se provádí s tváří obrácenou k východu. Východ je také směrem počátků, záhad, zázraků, domovem světla, zdrojem života, věčného mládí, nesmrtelnosti a věčnosti.

Západ je vnímán jako směr smrti, temnoty, zla a očistce. Se západním směrem bývá spojováno zlo, neštěstí, podzim, stáří, nemoci a svět zesnulých. Ve starověkém Řecku vládlo přesvědčení, že vchod do podsvětí (do Hádu) leží při západním okraji země.

Mnohé národy věřili, že mrtví znají věci, které jsou očím živých skryty, vidí do budoucna. Věřilo se, že když spíte na hrobě, dostane se vám vidění.

Ve finském eposu Kalevala se hovoří, že Väinämöinen vstoupil do říše mrtvých pro tři „vědmá slova". Byl to moudrý stařec a mocný pěvec, což znamenalo, že byl i mágem. Také severský bůh Ódin chtěl získat moudrost – napít se z Mímiho studny v podsvětí. Musel obětovat levé oko. Získal však nesmírnou moudrost a vědění.

**ZPĚV A HUDBA** jsou součástí života jednotlivce, skupiny, lidstva. _Když členka jednoho afrického kmene chce mít dítě, začne meditovat, dokud se ji v mysli neobjeví melodie, písnička. Ta patří jejímu budoucímu dítěti. Zpívá mu ji po dobu těhotenství a při narození ji dítě uslyší jako první zvuk. Pak mu ji zpívají všichni rodinní příslušníci při každé příležitosti (např. nemoc, přechod do dospělosti, svatba, pohřeb)._

Dříve pro lidi hudba a zpěv znamenala základ a vyjádření existence. Dnes, hlavně na západě, ji konzumujeme jako zboží. Přitom žádný rituál se bez zpěvu a hudby neobejde. Hudba a zpěv jsou nezastupitelné i při pohřebních rituálech. Uvolňují emoce, vzpomínky a tím ulehčují loučení. Zpěv, hudba a tanec (zejména jejich provozování) nás činí šťastnějšími, spokojenějšími, zdravějšími. Toto platí i pro celé lidstvo.

[quote, Konfucius]
____
Kdo chce poznat politickou situaci státu,
má si poslechnout,
jaké písničky se tam zpívají.
____

Vše kolem nás má svůj rytmus. I naše tělo, jeho orgány, každá buňka, mají svůj rytmus. Příroda i celý vesmír zní a pulsuje. Hudba a zpěv v podstatě interpretují tyto různé rytmy kolem nás a současně nás učí tyto rytmy slyšet (tlukot srdce matky dítě uklidňuje). Staré kultury a šamanská společenství považovaly hudbu a zpěv za jazyk bohů a jejich prostřednictvím se svými bohy komunikovaly.

Hudba a zpěv jsou také klíčovými při vzniku světa ve fantasy knize Silmarillion od J. R. R. Tolkiena: _Ilúvatar (Nebeský otec) svým zpěvem stvořil Ainur, Svaté. Mluvil k ním tak, že jim předkládal hudební témata a oni před ním zpívali. Dlouho však zpíval každý sám. Pak jim Ilúvatar vyjevil mocné téma a chtěl, aby v souzvuku hráli Velkou hudbu. Hudba je vyjádřením myšlenek, příběh, obraz světa, osud. Hudba a její ozvěny přetékají z Ilúvatarových síní do Prázdna a naplňují je._

_Jeden z Ainur, Melkor, však začal do ní vplétat látku dle vlastních představ, která neladila s Ilúvatarovým tématem. Melkor chtěl totiž zvýšit svou moc a slávu, sám se stát stvořitelem. Tak vznikl ve společné hudbě nelad a nesoulad._

_Ilúvatar pozvedl ruku a zaznělo nové, krásné téma. Ale Melkor se ji snažil přehlušit svou hudbou. Tehdy Ilúvatar pozvedl druhou ruku a vnesl do hudby další téma. Toto téma je v rozporu s Melkorovým, který se nevzdává. Nakonec Ilúvatar zvedl obě ruce a Velkou hudbu ukončil. A všem_ _Ainur ukázal, co svým zpěvem udělali. Dali vzniknout v Prázdnu novému Světu a ten počal odvíjet svou historii._

Židovská pověst Darovaný život _vypráví o krásné dívce Elle. Jeho otce i ji samotnou zachránil moudrý a laskavý rabín Jochanan před bídou. Oba mu byli vděčni, ale nevěděli, čím by se mu mohli odvděčit._

Jednoho dne rabín Jochanan umíral a jeho žáci svolávali Židy do synagogy, aby mu jejich modlitby zadržely duši v těle. To nestačilo. Ani další metody nepomáhaly. Nakonec se rozhodli, že půjdou pro rabína sbírat roky. Začali obcházet všechny židy v ghettu a na list papíru psali, kdo kolik dnů, týdnů ze svého vlastního života daruje umírajícímu rabínovi.

Když přišli k Elle, ta řekla: "Dám za rabína celý svůj život. Chci, aby rabín žil dlouho a mohl pomáhat ostatním, tak jako pomohl nám."A sotva žák napsal vedle jejího jména její nabídku, padla mrtvá k zemi a ve stejnou chvíli se rabín Jochanan uzdravil.

Velice se trápil tím, že Ella vyměnila svůj mladý život za jeho. Po první úplňkové noci uslyšel nádherný zpěv. Pod jeho okny stál stín krásné mrtvé Ell. Ella se na děj dívala a zpívala mu. V jejím zpěvu zněla láska a radost. Každou úplňkovou noc mu Ella takto zpívala. A rabín si každý večer kladl otázku, zda pro lidi dělá dost, aby alespoň z části vyvážil tak velikou oběť.

Roky letěly, ale rabín Jochanan příliš nestárnul. Jeho vlastní život udržoval nádherný zpěv mrtvé dívky, znějící při každém úplňku.

Život se mu postupně stával břemenem, cítil se velmi unavený. Po jeho stých narozeninách jedné nádherné letní noci zářil úplněk. Stál při otevřeném okně a čekal na Ellin zpěv. Tentokrát ale Ella stále vedle něj a zpívala. A v jejím zpěvu zněla láska a šum křídel anděla smrti.

Když jej ráno našli mrtvého, na tváři se mu zračil šťastný úsměv.

**SNY O SMRTI.** Dávní Toltékové věřili, že život je sen. Každý z nás žije ve svém osobním snu a naše sny dohromady vytvářejí sen planety. Australští domorodci hovoří o době stvoření, kdy vznikal vesmír (tedy období před vznikem lidské paměti), jako o „době snění". Podle nich má vše na tomto světě svoji vibraci, jejíž ozvěna popisuje okolnosti a duchy předků, kteří ji stvořili. Ti jsou stále přítomní formou, do jaké se koncem „doby snění“ převtělili.

Dle hinduismu Višnu spí v kosmickém oceánu a z jeho pupku vyrůstá vesmírný lotos. Na lotosu sedí Bráhma stvořitel. Otevře oči a vznikne svět, kterému vládne Indra. Potom Bráhma oči zavře a svět zanikne. Jeden Bráhma žije 432 000 let. Když zemře, jeho lotos zanikne a vyroste jiný lotos, na kterém sedí Bráhma, který otevírá a zavírá oči.

Višnu je spící bůh a vesmír je vlastně jeho sen.

V řecké mytologii je bohem spánku Hypnos, syn bohyně noci Nykty. Má bratra (dvojče). Tím je bůh smrti Thanatos.

Lidé se od nepaměti snaží porozumět svým snům. K jejich výkladům se přistupovalo a přistupuje různě: jsou předzvěstí nemocí, informací o nemoci a způsobu léčby, poselstvím bohů, rozhovorem mezi Bohem a lidmi, nástrojem satanovým, ukazují nám naši budoucnost, jsou zdrojem informací a poučení, slouží ke kompenzaci reality, jsou projevem individuálního nevědomí, projevem kolektivního nevědomí (všemi lidmi sdílená studnice vzpomínek, znalostí a zážitků kulturního rázu), které obsahuje archetypy (souhrn myšlenek, obrazových vjemů, které jsou univerzální a tedy všem společné a srozumitelné). V současnosti je zdůrazňováno pojetí snů jako zdroje poznání sebe sama, jako nevyčerpatelný zdroj informací o našem duševním životě.

Jazykem snu jsou symboly, metafory, obrazy. Ty jsou v podstatě vždy víceznačné.

Zejména v mýtech a pohádkách se setkáváme se snahou přijmout smrt jako základní podmínku lidské existence. Když je smrt vtělena do života, jsou lidé vyvedeni ze své omezené existence v přítomnosti a vystaveni proměně, která je v podstatě plodná. Základním specifickým lidským pocitem se stává pocit kontinuity života. Pocit, že člověk tak jako v přítomnosti žil také v minulosti a bude žít i v budoucnosti. Čili proměna je spojena s „poznáním", že smrt a život k sobě náleží, a že jeden bez druhého by sám o sobě nemohl existovat. Proto sny, ve kterých se člověk setkává se smrtí, často poukazují na začínající proměnu, jako začátek nového vývoje, začátek změny.

Pohádka O Sněhurce obsahuje mnoho symboliky týkající se smrti (smrt v podobě macechy jako stařeny, otrávené jablko, kouzelné zrcadlo, bloudění v hlubokém a neznámém lese, trpaslíci, kteří pracují v podzemí) a proměny (služba u trpaslíků, vlastní „smrt", obživnutí princovým polibkem – předání dechu/duše je symbolem nového života).

„Smrt" je symbolem mnohých mysterií, zasvěcení, iniciačních rituálů a těch událostí v životě, které mají aspekt nevyhnutelnosti a proměny (např. přechod jedince z dětství do dospělosti, kdy „umírá“ svému dětství a proměňuje se do nového stadia života).

*LIDSKÁ SNAHA OBELSTÍT SMRT* provází lidstvo odnepaměti. Odraz tohoto nacházíme zejména v pohádkách.

[loweralpha]

. **Přátelství se Smrtí **a pak následně léčení s její pomocí. V pohádkách _Smrt vystupuje jako kmotřička, která jde chudákovi za kmotru jeho dítěti. Protože Smrt nemá bohatství, umožní chudákovi, aby léčil s její pomocí. Jen on ji bude vidět stát u lůžka nemocného. Když nemocnému bude stát u nohou, může chudák nemocného léčit jak uzná za vhodné, vždy ho vyléčí. Když bude Smrt stát u hlavy nemocného, nemá se chudák o nic pokoušet, protože nemocný už Smrti propadl. Tak se i děje a chudák je za chvíli velkým boháčem._
+
A nakonec kvůli penězům kmotřičku Smrt podvede. Jednou je povolán k bohatému nemocnému a je mu slíbená veliká odměna, když ho vyléčí. Bývalý chudák ale vidí, že Smrt stojí u hlavy nemocného. Baží však po odměně. Proto nechá rychle otočit postel s nemocným, takže se Smrt ocitne v nohou nemocného a ten se uzdraví. Smrt ale bývalého chudák za to potrestá. Vezme si jeho život.
+
V reálném životě se snažíme poznat příčiny nemocí a tak zvítězit nad smrtí, nebo ji alespoň oddálit.

. **Znemožnění Smrti vykonávat svou práci.** __Pro hlavní postavu pohádky si přichází Smrt. Dotyčnému se ji podaří uzavřít do sudu (nebo také přilepit na židli, strčit do pytle) a Smrt ze světa zmizí. Nakonec se ukáže, že smrt je na světě potřebná (nic neumírá, lidí, zvířat, hmyz přibývají, nemají místo pro život a nemají ani potravu, hladoví, trpí bolestmi) a ten, kdo ji uvěznil ji nakonec osvobozuje a ona si bere jeho život. Smrt vítězí.__
+
V reálném životě se snažíme prevencí (zejména očkováním) zabránit onemocnění a tím i možné smrti.

. **Prodloužení života.** V pohádkách _Smrt přebývá v limbu. Každému člověku zde hoří svíčka života. Ten, komu Smrt dovolí, aby se do limbu podíval zjišťuje, že mu svíčka dohořívá. Prosí Smrt, aby mu zapálila novou svíčku, ale ta to odmítá, jednak proto, že každý má určenu délku života a jednak proto, že kdyby zapálila dotyčnému novou svíci, svíčka jinému by musela dohořet._
+
V jedné pohádce chudák tajně, když se Smrt nedívá, zapálí pro sebe novou svíčku, protože ta jeho už dohořívá. A když přijde domů, zjistí, že jeho novorozený syn, kterému byla Smrt za kmotru, zemřel.
+
V reálném životě využíváme první pomoc, transplantaci, přežíváme svou klinickou smrt pomocí lékařského zásahu.

. **Snaha získat něco, co může navrátit mládí, vyléčit neduhy nebo zajistit si nesmrtelnost, věčné mládí.** __V pohádkách nemocný král posílá své syny, aby mu přinesli něco, co jej uzdraví. Nebo starý král zatouží stát se opět mladým, aby aby získal srdce mladé nevěsty.__
+
V pohádce Ostrov se dvěma prameny _jeden mladík se zamiloval do dívky a ona do něho. Chtěli se vzít. On se dozvěděl o pramenu mládí a vydal se ho hledat. Chtěl se z něho napít. Po mnoha letech hledání se dostal na ostrov, který vypadal jako ráj. Našel tam pramen mládí – kdo se z něho napije, bude věčně mladý a nebude potřebovat jíst ani pít. Ale na ostrově byl i druhý pramen s opačnou mocí. Kdo se z něho napije, bude opět smrtelný a starý, jak odpovídá jeho věku._
+
Mladík se napil z pramene věčného mládí a vrátil se ke své dívce. Ale dívka, která ne něj stále čekala, byla už stará a rodiče zemřeli. Pochopil, jakou udělal chybu. A nechtělo se mu žít na světě, kde ostatním čas běží a vidět je umírat. Skočil do loďky a šel hledat ostrov, aby se napil z druhého pramene.
+
V mýtech a legendách hlavním zdrojem věčného mládí bývá pokrm zejména jablka, ambrózie, broskve (my se v současnosti snažíme pomocí diet, zdravé životosprávy uchovat si zdraví a mladistvý vzhled).
+
Druhým zdrojem bývá nápoj, zejména pramen živé vody, pramen věčného mládí, omlazující pramen (my v současnosti zdůrazňujeme pitný režim, povzbuzující a obohacené nápoje).
+
V reálném životě se snažíme porozumět procesu stárnutí, oddálit ho omlazovacími kůrami, plastickými operacemi, genetickou manipulací.

. **Najít místo, kde se žije věčně a kde se neumírá. **V pohádkách hrdina hledá takové místo. Nachází ho. Časem ale zjišťuje, že se mu stýská po rodičích, přátelích, známých místech. Nakonec se vrací a zjišťuje, že nikoho nezná, nic nepoznává, protože uběhlo mnoho stovek let. A zde ho stáří a Smrt dostihne.
+
V reálném životě se setkáváme s myšlenkou hibernace, s myšlenkous zpomalení stárnutí cestováním vesmírem.
