== Hřbitovy

[verse, J. Wolker, Pohřeb (Těžká hodina)]
____
Hřbitove, hřbitove,
zahrado zelená,
do tebe sejou se
nejdražší semena,
aby rostla.
____

*KŘIŽOVATKA CEST* byla vnímaná jako místo božstev změny a proudu, skrze něž mohou nadpozemské síly vstupovat do onoho světa. Nebezpečné místo, kde působí bohové i démoni. V severské tradici je považován bůh Wotan /Woden/Ódin za božstvo křižovatky. Bylo běžné na křižovatkách stavět šibenice, aby duch popraveného prošel rychle podél kosmické osy do podsvětí.

V antickém Řecku byla křižovatka působištěm boha Herma (Řím – bůh Merkur). Na křižovatkách cest se často odehrávaly hrdelní soudy, protože se mělo za to, že soudci na tomto místě byli nestranní a nepatřili k žádnému směru.

Hroby a hřbitovy bývaly v těch dobách často umisťovány na křižovatkách cest. Později zde byli pohřbívání ti, kteří neměli právo být pohřbeni na křesťanském hřbitově.

Na křižovatkách tří cest vládla prastará trojitá bohyně Hekaté (uctívali ji čarodějky a mágové) a zde se nacházela vstupní brána do podsvětí. Když jednou rozhněvala svou matku (pocházela z rodu Titánů), utekla na zem a později do podsvětí. Postupně se stala obávaným božstvím podsvětí. Má moc nad čarami a kouzly, nad životem a smrtí. Hekaté bývá zobrazována se třemi hlavami (propojení minulosti, přítomnosti, budoucnosti a propojení tří úrovní lidské bytosti).

Křižovatka je ale také symbolem volby, přechodu i osamělosti.

*HŘBITOVY* -- Pozemská krása je pomíjivá, ale ne v nebeských zahradách (stále rozkvetlé). S tím souvisí starý obyčej zakládat hroby v zahradách (ohraničená část přírody obehnaná zdí) anebo je alespoň osazovat květinami. Hřbitovy jsou upomínkou na nebeskou zahradu, která je plná květin, stromů, pokoje a míru. Židé nazývají své hřbitovy dobrým místem.

Zahrada, protože je určitým způsobem ohraničená (zeď, plot, živý plot) symbolicky něco uzavírá, omezuje, vyčleňuje, ale i ochraňuje. Ten, kdo o ní pečuje, nebo ji vlastní, ji má pod kontrolou (rozhoduje o tom, co v ní poroste, co se v ní bude nacházet, kdo do ní vstupuje), což v divoké přírodě neuplatní.

V starověkém Řecku a Římě se hovoří o Rajských lukách neboli Elysejských polích, které se nacházejí v podsvětí, o Ostrovech blažených. V Římě byly ohrazené pohřební zahrady považovány za protějšek Elysia a pohřební hostiny pořádané v těchto zahradách představovaly hostiny elysejské. Tyto zahrady byly často osázeny vinnou révou. Jednak proto, aby se poskytl obětní nápoj pro bohy, jednak jako symbol života a nesmrtelnosti. Pěstovaly se v nich také růže jako znamení věčného jara.

V raném křesťanském středověku byla velice rozšířená představa ráje jako nádherné zahrady se stromem života a stromem poznání, se čtyřmi řekami pramenícími z centra požehnané krajiny Edenu, kde spravedliví čekají na vzkříšení a poslední soud. Pro člověka tudíž byla zahrada obehnaná zdí symbolem domova pro duše a bezpečným útočištěm před problémy pozemského života.

Z 1. století př. n. l. máme zmínky o hřbitovní zahradě (kepotaphia). V Iliadě se Homér zmiňuje o hřbitovních hájích hrdinů. Na území Malé Asie a Egypta v helenistickém období byly oblíbené hrobky se zahradou. V antickém Římě byly také hřbitovní zahrady běžné. Hrobku obklopovala zeleň, zahrada či háj, které měly být hojně navštěvované, aby se vzpomínalo na zemřelého. Zeleň se stala nedílnou součástí hrobů a hrobek.

Hřbitovní zahrada mívá různé tvary. Bývá oplocena zídkou nebo plotem (pozdější doba). Strach z duší zemřelých byl značný. Toto oddělení od okolního světa slouží k tomu, aby pochovaným, tedy obyvatelům hřbitovní zahrady, vlastně jejich duším, bylo zabráněno vstupovat do světa živých, a také proto, aby zemřelí měli klid (nikdo jejich „spánek" nerušil). Většinou mívala i z těchto důvodů jeden vchod. Tyto hřbitovní zahrady se většinou stavěly blízko kostelů (zejména křesťané).

Hřbitovní zahrady byly a jsou skutečnými zahradami – roste v nich hodně stromů, tráva, květiny. V některých krajích se pod pojmem „růžová zahrada" skrývalo označení hřbitova. Hřbitovy se také nazývaly „obydlí pokojných".

Nelze opominout klášterní zahrady. Jejich součástí byl také hřbitov a často mezi hroby byly vysazovány i ovocné strom.

Spalování zemřelých je dávným zvykem. Popel se buď rozptýlí nebo uloží do určené schránky či zakope do země. Popel zemřelých je spojen s posledním místem odpočinku – urnový háj. Už sám název evokuje sepětí s přírodou, návrat k ní (prach jsi a v prach se obrátíš).

*STROMY* zde hrály a hrají důležitou úlohu. Mohou označovat vchod do jiného světa. Kdysi bývalo zvykem zasadit „do hlavy“ nebožtíka strom. Ten vlastně nebožtíka vstřebal, jelikož se mu stal zdrojem obživy. Tímto duše mrtvého měla možnost vtělit se ve strom a tak žít dál. S touto představou se setkáváme v mnoha pohádkách.

Jedna vypráví o dvou sestrách, které záviděly své nejmladší sestře, že ji mají rodiče nejvíce rádi a tak ji jednou v lese zabily a zahrabaly do země. Doma řekly, že neví, kde sestřička je, protože je neposlechla a sama se vydala domů.

_Na místě, kde byla dívenka pochovaná, vyrostl strom. Jeden pasáček si náhodou z něho uřezal větev a udělal si z ní píšťalku. Když zapískal, začala píšťalka hlasem dívenky zpívat o tom, jak ji sestry zabily a do země zahrabaly. Pasáček šel k rodičům zavražděné a tam jim začal pískat na píšťalku. Rodiče se takto dozvěděli, co se stalo._

Obě starší sestry utekly do lesa a tam se oběsily.

Moravská pohádka Rozmarýn _hovoří o dvou zamilovaných mladých lidech, kterým rodiče nechtěli dovolit, aby se vzali. Mládenec odešel do světa a před odchodem si oba zamilovaní slíbili, že jeden na druhého počká._

Uběhly dva roky a mládenec se nevracel a dívka chřadla, až umřela. Rodiče ji pohřbili na hřbitově a na její hrob vysadili rozmarýnu. Ta rostla a za chvíli pokryla celý hrob.

_Jednou šel kolem mládenec, který přicházel z velké dálky. Rozmarýna ho něčím nevysvětlitelným přitahovala. Ulomil si z ní větévku, strčil za klobouk a šel do kostela. „Zvony zvoní, v kostele ji určitě uvidím“, myslel si mládenec. Chtěl před vstupem smeknout klobouk, ale nešlo to, a začala ho velice bolet hlava. Tak vstoupil do kostela s pokrytou hlavou. Všichni se na něho ohlédli a vykřikli zděšením. „Vždyť je to rozmarýna, která roste na hrobě Maryšky!“ Tu pocestný poklekl. Už věděl, čí to byl hrob, na kterém ta rozmarýna rostla. Maryška na něj věrně čekala, ale v hrobě._

A větev za jeho kloboukem rostla a pučela právě tak, jako na hrobě Maryšky. Zachytila se mu v hlavě i mozku. Umřel v kostele, zastíněný rozmarýnou.

_Marně rodiče litovali, že svým dětem bránili v lásce. A tak mládence pohřbili k jeho Maryšce do jednoho hrobu. A nad jejich hrobem se skláněly dvě rozmarýny vysoké a košaté._

V egyptském mýtu o Usirovi hraje strom také významnou úlohu.

_Usir (řecky Osiris) byl egyptským bohem úrody a plodnosti. Jeho bratr Sutech mu záviděl a proto ho chtěl zabít. Pozval ho na hostinu, na které ukazoval nádhernou truhlu se vzácného dřeva. Vyzval hosty, že ji daruje tomu, čí_ _tělo se do ní dokonale vejde. Když si do ní Usir lehl, aby ji vyzkoušel jako ostatní hosté, Sutech přikázal víko zavřít a truhlu hodit do Nilu. Voda truhlu odnesla daleko až k ústí, kde se zachytila o kořen stromu. Jak strom rostl, pojal truhlu do svého kmene._

_Jeho manželka Eset (řecky Isis) truhlu nakonec získala a schovala ji v močálech Nilu, aby ji nenašel Sutech. Ten ji však našel a plný nenávisti mrtvé Usirovo tělo rozřezal na 14 dílů, které rozházel po celém Egyptě. Usirova žena Eset se snažila posbírat všechny části jeho těla a s pomocí boha Anupa jej oživit._

Usir se stal bohem podsvětí a zemřelých.

Byl zpodobňován v různých barvách: bílá (jako mumie), černá (odkaz na záhrobí), zelená (symbol vzkříšení). Později se několik měst pyšnilo tím, že vlastní část Usirova těla. Každé toto město mělo „Usiruv hrob!" a přímo nad rakví, která měla ukrývat údajnou část jeho těla, byl zasazen strom, který měl symbolizovat Usirovo vzkříšení.

Před příchodem křesťanství převažovala tendence pochovávat zemřelé ve volné krajině, mezi obydlími živých. Byli součásti života živých.

*HÁJE*, kde se pohřbívalo, byly neohraničené, volně přístupné a byly přirozenou součástí krajiny. Některé kmeny v Africe své významné členy po smrti ukládali do dutin popraskaných baobabů, které už nebyly používané jako vodní nádrže.

K této myšlence se někteří lidé vrací. Existuje představa tzv. pohřebních lusků. Poté, co je nebožtík pohřben v embryonální poloze (lusk), je nad jeho luskem zasazen strom nebo jeho semeno a tělo se stane pro něj výživou. Vizí tohoto přístupu je vytvořit vzpomínkové parky bez náhrobků.

*HROB* bývá symbolem bolesti a žalu, ale také vzpomínky, či symbol „pohřbeného těla“, které bude vzkříšeno. Je také chápán jako místo posledního odpočinku, které představuje definitivní ukončení jednoho cyklu a začátek nového.

Obdobně to platí i pro **hrobky**, které jsou navíc určeny jako místo posledního odpočinku pro příslušníky určité rodiny. V Evropě byly hrobky bohatých lidí často zdobeny vyobrazením cností zemřelých (udatnost, čestnost apod.). Naši předkové v nich viděli bránu do jiného života.

Bývalo častým zvykem dávat mrtvému s sebou na onen svět různé potřebné věci, nebo jeho osobní věci, peníze (mnohdy z důvodu, aby měl čím zaplatiti převozníkovi na onen svět). V Číně a Vietnamu se mrtvým vkládala do úst rýže, zlato, mince (aby nehladověli a nestrádali). Staří Slované dávali malovaná hliněná vajíčka (kraslice) jako upomínku na vznik vesmíru. Zasloužil se o něj Svarog, prabůh, který spí ve velkém vajíčku (Slunci). Židé dávají na hroby kamínky po starém způsobu Židů putujících pouští, kde nebylo květin.

Aby se na mrtvé nezapomínalo, označovaly se hroby náhrobky - náhrobními kameny, deskami, sochami, kříži apod. se jmény pohřbených.

*NÁHROBKY* označují hrob, odrážejí rozličné postoje k smrti a různým způsobem identifikují zesnulého, kdy se narodil a kdy zemřel, jeho zařazení ve společnosti, jeho profesi, k jaké rodině náleží. Často nesou nápisy k uctění památky zesnulého (např. Vzpomínáme, Odpočívej v pokoji – lat. zkratka R. I. P.); k útěše pozůstalých (např. citáty z bible, z děl zemřelého, známých osobností); varování žijícím o relativitě života (např. Prach jsi a v prach se obrátíš).

Do škvíry náhrobku slavného židovského učence rabína Löwa i dnes strkají lidé lístek se svým tajným přáním a s prosbou o jeho splnění.

Staří Germané věřili, že duchové mrtvých žijí dál ve svých náhrobních kamenech. Zvyk pokládat kameny na hroby někdy vychází ze symbolické představy, že z mrtvé osoby cosi věčného zůstává a to cosi nejlépe představuje nesmrtelný, neměnný kámen. Kámen také symbolizuje pouhou existenci bez emocí, myšlení, pocitů.

Mnoho náboženství používá kámen jako znamení boha nebo k označení místa bohoslužby, oběti. Pro alchymisty je „kámen mudrců“ ztělesněným symbolem tajemství hmoty.

Náhrobky jsou často zdobeny *symboly*:

- _Pochodeň_ je symbolem nesmrtelnosti a zápasu života se smrtí. Otočená dolů značí smrt.
- _Přesýpací hodiny_ symbolizují časovou vymezenost života, položené na bok sdělují, že pro zesnulého se již čas zastavil.
- _Zavřená kniha_ symbolizuje dočtení životní kapitoly.
- _Zlomený nebo zborcený sloup_ – pomíjivost vezdejšího života či nepřízeň osudu.
- Reliéf _smuteční vrby_ – symbol propojení života a smrti.
- _Kamenné hrozny_ hlásají moudrost a plodnost.
- Křesťanští _andělé_ symbolizují vzestup duše k nebesům, _lebky_ připomínají krátkost života, _biblické scény_ obraz nadějeplného zmrtvýchvstání, _holubice_ je symbolem duše, _lev_ značí odvahu, sílu a zmrtvýchvstání.
- _Dubový list_ je často na hrobech vojáků a je atributem síly, slávy, trvání a vítězství.
- _Motýl_ je symbolem duše, krátkosti života, svobody a proto se objevuje na dětských náhrobcích.

*Epitaf* (náhrobní nápis) je krátký text, který informuje o osobě a životě zesnulého. Nemusí být umístěn na hrobě. Může mít význam památníku, který přímo neoznačuje hrob.

*Smírčí kříž* je specifickým středověkým upozorněním na zločin (nejčastěji vražda) a současně formou pokání. Ve středověku bylo možno uplatnit tzv. „smírčí právo“. Zločinci bylo uloženo, kromě odškodnění pozůstalých, vytesat z kamene kříž (většinou i s informaci o zločinu) a zapustit ho do země, kde byl zločin spáchán. Šlo současně o snahu předejít krevní mstě.

*Rakev* je schránkou pro mrtvé tělo. Rusové ji nazývali „domovina“.

Podle starých Egypťanů byl člun nejen fyzickým objektem, ale také zrcadlovým obrazem prámu vědomí, na němž se duše plaví životem. V mnoha kulturách se nebožtík vypravoval na poslední cestu po vodě v pohřební lodi.
