== Flóra

Stromy a květiny jsou úzce spjaty se životem člověka. Narození, křest, svatba, smrt, slavnosti, magie a čarování, výroční oslavy apod. jsou spojeny s rostlinami.

Většina národů preferuje jako národní symbol určitý strom (Česko – lípa, Německo, Irsko – dub, Řecko – oliva, Rusko – bříza, Skotsko - borovice) či květinu (Egypt – lotos, Nizozemsko – tulipán, Skotsko – bodlák, Irsko – jetelový trojlístek).

Lidé se vždy určitým způsobem loučili se svými zesnulými. V podstatě při rozloučení nikdy nechyběly květiny a jehličnaté nebo olistěné větve, které se vkládaly do hrobů a vysazovaly na hroby.

Mezi všemi národy kolují pověsti o proměnách lidí ve stromy či květiny nebo opačně. Po celém světě najdeme víru, že květiny a stromy obývají nadpřirozené bytosti (víly, dryády, oready, gnómové).

Existuje mnoho mýtů, že první lidé byli stvořeni ze stromů (Austrálie, Afrika, Jižní Amerika). Germánští _bohové Ódin, Hoenir a Lodur nalezli na mořském břehu kmen olšový a jasanový. Z jasanu stvořili muže Asku a z olše ženu Emblu._

Podobnost života rostlin a lidí stála u zrodu víry, že duše zemřelých se po smrti vtělí v rostlinu a žije v ní dál. Když potom příbuzní přijdou ke hrobu, mohou s ní rozmlouvat. Nelze se divit, že zvyk osazování hrobů stromy a kvítím, zemřelým dávat na jejich poslední cestu květiny, je v nás hluboce zakořeněn.

Velké obliby se těšily a těší *STÁLE ZELENÉ STROMY*. To, že jsou neopadavé, symbolizuje věčný život a zelená barva je symbolem naděje a znovuzrození. Stromy jsou symbolem života, protože v sobě skrývají tajemství ročních období. V zimě jakoby odumíraly, aby se na jaře zrodily mohutnější, velkolepější.

Jsou také symbolem člověka – mají korunu (hlava), kmen (trup), kořeny (nohy). Jejich kořeny sahají hluboko do podzemí a koruna se tyčí k nebi.

Stromy jsou mnohdy chápány jako symbol spojení podzemí, země a nebe (Axis mundi – osa světa; Arbor vitae – strom života). Umožňovaly komunikaci mezi třemi světy (podzemím, zemí, nebem).

V keltské mytologii stromy představovaly spojení mezi životem a smrtí, světem pozemským a podsvětím. Zejména jabloně se objevují v mnoha mýtech o Onom světě.

Stezka mezi stromy je také paralelou člověka a jeho pouti životem. Stromy v blízkostí náhrobků a chrámů byly chráněné, protože se mělo za to, že v nich sídlí duchové mrtvých a bohů.

*ZELENÝ MUŽ* (olistěná tvář) má různé symboly (např. mužský aspekt přírody, personifikace divoké přírody, smrti a vzkříšení, obnovy). Primárně je symbolem znovuzrození, obrození, nového počátku, připomínka nekončícího cyklu, který je obnoven s každým jarem.

Setkáváme se s jeho ztvárněním také na hrobkách (zřejmý symbol vzkříšení či spásy skrze odpuštění po smrti) a v kostelech (zejména u západního vchodu – tato část podle kosmologické struktury je vyhrazená temnotě, zármutku, smrti a hrobkám zemřelých čekajících na vzkříšení a poslední soud). Někdy byl symbolem bezpečné cesty duše na blažený ostrov (u Keltů vedla tato cesta přes mlhu).

Často je jeho tvář listy doslova ověnčena tak, že tvoří věnec. Věnec představuje symbol smrti ve významu konec starého života a zrození pro život nový.

Obecně jsou **KVĚTINY** symbolem duše, duše šťastné, rozkvetlé, zbavené materiálního majetku. Jsou symbolem krásy, probuzení života, ale pro svůj krátký život také pomíjivosti života, jeho křehkosti. Číňané věřili, že za každou ženu, žijící na tomto světě, vykvete na onom světě květina. Křesťané vždy zdobili hroby svých mrtvých květinami, které symbolizovaly nádheru rajské zahrady.

Vázání a aranžování květin, **floristika**, je tvorbou rozmanitých květinových děl k různým účelům. Mezi ně patří floristika smuteční, pohřební. Jedna se zejména o věnce a kytice na rakev i k uctění památky při smutečním obřadu. Staří Římané používali palmový list, zdobený několika květy, který kladli na rakev nebo vhodili do hrobu zesnulého jako poslední pozdrav na rozloučenou. Z toho vznikla plochá kytice, kdy na větev chvojí nebo dřevin se kladly květy a drátem přitahovaly. U vrcholu byly květy nejdelší, v místě držení kytice nejkratší. Později se květy prokládaly kratší zelení a tak z plochého tvaru vznikal tvar prostorový. Malé kytice se na pohřbech rovněž používají, ale jako volně vázané a často doplněné stuhou.

**Věnce** jsou nezastupitelné díky svému kruhovému tvaru – kruh nemá začátek ani konec a je tudíž symbolem nepřetržitého koloběhu života, smrti a znovuzrození, také přetrvávání, zmrtvýchvstání, spásy. Proto se rostlinný materiál dekoruje ve směru hodinových ručiček (tak sledujeme běh času).

Věnec je současně vnímán i jako forma ocenění (věncem se korunovaly hlavy významných lidí, sochy bohů) a vzdání holdu. Slované věncem z kvítí položeném na rakvi přeji nebožtíkovi, aby alespoň po smrti si odpočinul na květech, když celý svůj život kráčel cestou těžkou a trnitou.

Smuteční věnce všeobecně souvisí s účastí i útěchou, a proto barevné složení nebývá pestré a vyzývavé ale vytváří harmonii a rovnováhu.

Řecký mýtus o Titánovi Prométheovi, _který stvořil z hlíny prvního člověka a bohům ukradl oheň, jenž daroval lidem, vypráví o tom, jak ho hromovládný Zeus za tyto skutky potrestal. Nechal ho přikovat ke skále na Kavkaze. Každý den přilétal sup (podle některých to byl orel) a vyklovával mu játra, která přes noc dorostla._

_Diův (2. pád jména Zeus) syn Hérakles prosil o milost pro Prométhea a Zeus ho vyslyšel. Jelikož ale Prométhea odsoudil k věčnému trestu, přikázal, aby Prométheus nosil prsten, zhotovený z řetězu, kterým byl přikován ke skále a to se vsazeným kamenem z té skály. Tak byl ke skále navěky připoután._

Lidé na Prométheovu počest začali nosit prsteny a věnce. Prométheus totiž po svém osvobození dostal nařízeno ověnčit se věncem z vrbového proutí. Hérakles si nasadil věnec z plané olivy, aby mu dělal společnost.

*Kytice* jsou po celém světě velmi oblíbené jako poslední pozdrav na rozloučenou. U nás a na Slovensku panuje zvyk vázat lichý počet květů do kytice darované živým lidem a sudý počet květin do smutečních kytic.

Používají se také vazby jiných tvarů např. *kříž* - významný křesťanský symbol smutku, smrti a spasení, současně je symbolem naděje na odpuštění hříchů a viny a symbolem překonání smrti, symbol rozbřesku světla, šířícího se do všech stran; *srdce* - symbol lásky, která přesahuje smrt; *květinový polštářek* - symbol nerušeného spánku a klidu; *květinová koule* - symbol završení života.

*Květinové koše* evokují symbol rohu hojnosti (v duchovním významu) a okázalosti.

*Girlanda* je závěsná výzdoba z květin, listů, chvojí, ovoce, větví – symbol uvolněné a bezstarostné oslavy života, plynoucího opakujícího se rytmu života a spánku.

Girland se často používají jako výzdoba katafalku.

S příchodem křesťanství se mění tématika dekorace funerálních (pohřebních, hřbitovních) prostor. Ustupují výjevy vážící se k individuu či sociálnímu postavení a zaměstnání zemřelého a nastupuje spiritualismus. Pozornost se obrací k představám o posmrtném životě, truchlícím pozůstalým až k motivům vyjadřujícím naději na spasení a vzkříšení.

Květiny byly a jsou vždy součástí náboženských rituálů a odvěkým symbolem vyjádření citů a lásky. Výběr funerální (pohřební, hřbitovní) flory v květinových vazbách a osazovaných na hrobech není nahodilý. Symbolika květin umožňuje sdělení pocitů, které často ani nedokážeme vyslovit. Proto jsou květiny jedním z nejdůležitějších symbolů spojených s rozloučením s našimi blízkými a s truchlením nad jejich ztrátou. Květinami si je připomínáme a jsou naším darem pro ně.

Žádná květina není ve smuteční vazbě nevhodná. Důležitý je výběr oblíbených druhů květin a také jejich barvy, které představují osobnost zesnulého. Volbu ovlivňuje také stáří zesnulého i symbolika rostlin.

**BARVA** květin je důležitá. Barvy působí na naše city bezprostředně. Reagujeme na ně téměř nevědomě. Barvy mají svůj vlastní symbolický význam a to ve všeobecné i osobní rovině.

**Bílá** je bohatá svou symbolikou. Měsíční bohyně je trojjediná a jednou z jejích vtělení je dívka, jejíž symbolem je bílá barva. Je spojovací barvou mezi zemí a sluncem. Je barvou duše, která stojí mezi materiálním tělem a duchem. Je výrazem uvolnění a svobody. Představuje původní začátek, neemotivnost, čest, nepopsanou stránku, světlo, měsíční světlo.

Je symbolem čistoty a nevinnosti, úcty a pokory, odvrácení se od hlučnosti a pestrosti života, dokonalosti, neplodnosti, chladu, symbolem zmrtvýchvstání, znovuzrození a reinkarnace, symbolické smrti. Symbolizuje nový začátek.

Je také symbolem prázdnoty a neživosti, sinalosti smrti. Proto v řadě civilizací byla barvou smutku, smrti, pohřbu. Pokud má v Japonsku nevěsta bílé šaty, tato barva nevyjadřuje její nevinnost, jako u nás, ale odloučení od stávající rodiny.

Bílá barva společně s černou vyjadřují dualitu: světlo – tma, den – noc, vědomí – nevědomí.

V marketingu je využívána pro zdůraznění čistoty, sterilnosti, hygieny, nedotknutelnosti.

**Černá** je synonymem absolutní prázdnoty a nicoty, zřeknutí se barevnosti života, symbol temnoty a noci, propojení s jádrem země. Symbolizuje konec. Je absencí světla, ale také nejtmavší odstín bílé.

Je barvou neznáma, neznámého, protože tma vše pohlcuje (černé díry ve vesmíru) a skrývá. Je to barva strachu, ďábla, hříchu, ale i nezávislosti.

V dávné minulosti existovala víra, že černá barva činí jejího nositele neviditelného pro duchy mrtvých, takže ti je s sebou nevezmou. Černá barva sloužila tedy k ochraně.

Ve starém Egyptě se na černou barvu pohlíželo jako na barvu plodnosti a úrodnosti půdy a života, znovuzrození. Pro hinduisty byla symbolem času. Později v západním světě se stala černá barva barvou smutku, zármutku, smrti, neplodnosti.

Symbolizuje konečné rozhodnutí, přímost, nesmlouvavost. Ve východních kulturách značí čest, význam (černý pásek v judu je znakem nejvyššího stupně dovednosti).

V marketingu je používaná zejména tam, kde je potřeba vyjádřit serióznost, důstojnost, převahu, sílu.

*Červená* tmavšího odstínu vyjadřuje lásku k zemřelému a bolest nad jeho ztrátou. Je to barva emocí, života v negativním i pozitivním smyslu, moci, ničení, bojovnosti. Je barvou krve. Symbolizuje odvahu a také smrt (válka, prolitá krev), ale i ocenění (červený diplom). Je spojována s ohněm, peklem a ďáblem (ten je často zpodobňován s červenou pletí, červenými vlasy a vousy).

*Fialová* je historicky vnímaná jako duchovní, církevní barva moci, symbolizuje pokoru a pokání. Je také barvou smutku a truchlení.

Je silně vnímaná jako mystická a duchovní barva.

*Hnědá* je symbolem země, ticha, bezpečí, pokory, askeze, rozkladu.

*Modrá* je na jedné straně barvou klidu, tradice, ženskosti, něhy, oddanosti, na druhé straně je spojována se smutkem, protože je spojována s deštěm – slzy, které proléval bůh Zeus, když byl nešťastný.

Je barvou víry a slitování, odpočinku a spánku, sklíčenosti a osamělosti. Je barvou touhy po klidu. Je barvou vody a nebe.

Někteří indičtí bohové mají modrou pleť.

*Růžová* symbolizuje něžnou lásku, oddanost a náklonnost, jemnost a zranitelnost, citovost.

*Stříbrná* barva je spojována s nocí a měsícem, tajemnem, tichem, nadpřirozeností, sněním a představivosti. Je symbolem neokázalého citu.

*Šedá* je zjemnění černé barvy a přítomností bílé barvy. Je symbolem přechodu, stínu, možností, hledání, neutrality, nevědomí, vyrovnanosti.

*Zelená* je barvou rostlin, růstu, prosperity, naděje i naděje na posmrtný život, znovuzrození a nesmrtelnosti (keltský Ostrov blažených, kam putovaly duše, měl barvu zelenou).

Symbolizuje ale také život a smrt, iniciaci, triumf nad smrtí, zmrtvýchvstání (bůh Osiris byl často zpodobňován se zelenou pokožkou – poukaz na jeho zmrtvýchvstání).

*Zlatá* je barvou slunce a božstev. Symbolizuje jedinečnost a význam, světlo a zář. Vyjadřuje klid a vyrovnanost, posvátnost.

Pro Inky je symbolem nejvyššího boha, v Egyptě představuje Slunce a boha Ra, pro Řeky je symbolem nesmrtelnosti, v hinduismu byla symbolem pravdy.

*Žlutá* je projevem souladu a harmonie, naděje, světla a schopnosti vidět i „za obzor“. Projasňuje vzpomínky a smutek. Pro buddhisty je symbolem pokory.
