= Funerální symbolika stromů a keřů

[quote, Kaun-tsu]
Plánuješ-li rok, zasej zrno. Plánuješ-li tisíciletí, sázej stromy.

Stromy mají pro člověka velký význam – estetický, uklidňující, zdroj potravy, zdravého ovzduší, léčení, úkryt, zdroj pro výrobu a stavbu, přístřeší, kolébka i rakev.

Lidé si vždy uvědomovali jejich význam a věděli, že bez stromů a keřů by nepřežili. Proto je také uctívali a zbytečně je nekáceli. Věřili, že to jsou živé bytosti, protože je obývají dryády a věděli, že ubližování stromům má za následek prokletí a mstu lesních bytostí.

O drusadách (keltské kněžky) se věřilo, že duše každé se prolíná s duši konkrétního stromu, a ona se k němu může obrátit se svou otázkou a dostane od něj odpověď, radu.

Všechny kultury mají pověsti, pohádky a legendy o tom, jak je člověk svým životem spjat se stromem.

Jedna z nich _hovoří o muži, který velice miloval svou ženu. V zahradě, o kterou se starala, rostla krásná *bříza*, kterou ta žena velice milovala. Často pod ní sedávala, hladila ji a velice o ní pečovala. Jejímu manželovi to připadalo divné, ale protože ji měl rád, nechal to tak._

Jednou o půl noci se probudil a velice se lekl. Jeho žena vedle něho ležela bez života. Byla studená, ztuhlá, nedýchala. Ale ráno vstala, jako by se nic nedělo. A to se opakovala každou noc.

_Muž šel za vědmou a vše ji řekl. Vědma mu vysvětlila, že život jeho ženy je spjat s životem břízy, která jim roste na zahradě. V noci opouští duch jeho ženy tělo a vstupuje do břízy. Nad ránem se do těla vrací. Zdůraznila mu, že bříze nesmí ublížit, jinak by ublížil své ženě._

_Muž tomu ale nechtěl uvěřit. Stále si myslel, že bříza očarovala jeho ženu a že mu ji bere. A tak vzal sekeru a šel břízu setnout. Sotva do ní zarazil svou sekeru, z břízy vytryskla krev a ozvalo se zasténání. Odhodil sekeru a běžel do domu za svou ženou. Tu našel ležet na zemi s velikou ránou v hrudi, odkud ji vytékala krev. Žena zemřela._

_A ten muž už nikdy nevztáhl ruku na žádný strom._

Se stromy a keři je také spojená rozšířená víra v převtělování a znovuzrození. Bengálská pohádka Sedm jasmínových bratrů _hovoří o králi, který měl sedm královen, avšak žádná z nich mu neporodila dítě. Nakonec si vzal ještě jednu ženu za manželku a tato osmá královna otěhotněla. Těch sedm královen ji závidělo a když mladá královna porodila sedm synů a jednu dceru, odnesly její děti a zabily je. Jejich tělíčky zahrabaly v královské zahradě pod jasmínové a růžové keře. Místo nich ji vložily do kolébky sedm myší a jednu žábu. Král se nahněval a nechal svou osmou královnu vyhnat do lesa._

_Jenže od té chvíle na královské zahradě vše uschlo. Mezi uschlými keři však vykvetlo sedm jasmínů a vedle nich jediná růže. Když je chtěl zahradník utrhnout pro krále, ozval se hlas: „Sedm jasmínových bratří, vstávejte! Přišel zahradník. Dáte mu své květy?“ „Nedáme, sestřičko růže, snad jen králi.“_

_Zahradník běžel za králem a vše mu řekl, Ten tomu nechtěl věřit a tak šel do zahrady. Vztáhl ruku po jasmínových květech a tu se ozval hlas:“Sedm jasmínových bratří, vstávejte. Přišel král. Dáte mu své květy?“ „Nedáme, sestřičko růže. Jen když přijde nejstarší královna.“ A tak se to opakovalo. Až přišlo do zahrady všech sedm královen._

_A nakonec hlas žádal, aby přišla nejmladší, osmá, královna. Král ji nechal přivést z lesa. Když vztáhla ruce po jasmínových květech, jasmíny se sklonily, aby je mohla utrhnout, a z nich vyskočilo sedm jasmínových princů a z růžového keře jejich sestřička. A tak král poznal pravdu._

_Zlé královny nechal uvrhnout do kamenné věže a se svou nejmladší ženou a dětmi se vrátil do paláce._

Jurakaréové (Bolívie) mají tento mýtus: _Kdysi zlý duch Sararuma spálil celou zem. Zachránil se jen jediný člověk. Sararumovi ho bylo líto a dal mu semena. Když je muž zasel, za dva dny kolem něho vyrostl les._

Ten muž si našel ženu (nikdo neví, kde a jak ji objevil) a měl s ní několik synů a jedinou dceru.

_Když dívka vyrostla, bylo ji smutno, protože se cítila osamocena. Jednou se zadívala na krásný strom a přála si, aby to byl muž. A k večeru se strom proměnil v muže a zůstal s dívkou celou noc. Nad ránem se proměnil ve strom. Takto to šlo po několik nocí. Dívka se do něj zamilovala a chtěla, aby s ní zůstal jako muž i přes den._

_Mladá žena se s tím svěřila matce a matka ji poradila, co má dělat, aby u ní ten muž zůstal jako její muž. Dívka ji poslechla, a když se příští noc mladík opět objevil a později usnul, připoutala ho pevně ke kůlu zaraženém do země. Celé čtyři dny ho tak nechala, dokud ji neslíbil, že u ní zůstane a ožení se s ní. Teprve potom ho uvolnila._

_Jednoho dne na lovu ho napadl jaguár a roztrhal ho. Mladá žena chtěla tělo svého muže řádně pochovat. V slzách sebrala kusy jeho těla a složila je k sobě. Dívala se na něj a plakala. Její slzy mu kanuly na tvář. Její velká láska způsobila zázrak – milovaný muž obživl._

_Když však uviděl svůj obraz ve vodě, lekl se. Chyběla mu půlka tváře. Takhle znetvořený s ní nechtěl zůstat. Rozloučil se s ní a uložil ji, aby se cestou domů nezastavovala a neohlížela. Slíbila mu to. Když však uslyšela za sebou, jak spadla větev, lekla se a ohlédla. Tím se tak zmátla, že v lese zabloudila._

V legendách o Šalamounovi se vypráví__, že když si pro něj přišel anděl smrti Samael s mečem, na jehož hrotu visela kapka žluči, ptal se ho Šalamoun, jak se dozvídá, kdo má zemřít. Samael mu odpovídá, že v ráji je strom života a smrti. Na tom stromě má každý člověk svůj list a na něm je napsáno jeho jméno. Narodí-li se dítě, list vypučí, spadne-li, je to znamení, že je jeho život u konce a tak Samael ví, pro duši koho si má jít.__

== Akácie (Acacia)

Akácie svou schopností růst v nepříznivých podmínkách symbolizuje nesmrtelnost, její bílé a červené květy symbolizují smrt a vzkříšení.

V mnoha kulturách byl nebožtík vypravován na svou poslední cestu v pohřební lodi. Usirova bárka byla vyrobena z akácie. Usir překonal smrt a dosáhl věčného života. Tím se stal symbolem příslibu vykoupení v životě po smrti. Akácie byla ručitelkou tohoto příslibu, protože chránila jeho mumii, zatímco se jeho duše rozprostírala vesmírem.

V Arábii akácii uctívají dodnes a říká se, že kdo ji ulomí větvičku, do roka zemře.

== Bez černý (Sambucus nigra)

{empty}J. K. Rowlingová ve své knize Bajky barda Beedleho uvádí Příběh tří bratří. _V něm Smrt slíbí každému z nich splnit jakékoli přání. Nejstarší chtěl nejmocnější kouzelnou hůlku. Smrt tu hůlku stvořila z černého bezu. Prostřední žádal schopnost přivolávat zemřelé z její moci zpět k životu. Dostal kámen vzkříšení. Nejmladší žádal, aby se v podstatě pro ni stal neviditelným. Neochotně mu darovala svůj plášť._

_První bratr se vychloubal svou hůlkou a v noci ho zloděj zabil a hůlku si vzal. Druhý bratr přivolal tu, kterou si chtěl vzít, a která už zemřela. Dívka ale byla smutná a chladná, nepatřila do světa smrtelníků a velice tím trpěla. Mladík si nakonec vzal život, aby s ní mohl být skutečně._

_A tak oba bratři už patřili Smrti._

_Po třetím bratrovi Smrt pátrala, ale nemohla ho najít. Až dosáhl úctyhodného věku, sňal z ramenou její plášť a tak ho uviděla. A on se k ní ochotně připojil jako rovnocenný poutník na onen svět._

Dříve kdo šel o kolo bezu, smekl a kdo ho porazil, propadl smrti. Bez je výrazně spjat s velmi silnou magií. Symbolizoval také smrt a umírání. Ve starém Římě se z něj vyráběly rakve. Křesťanské legendy hovoří o tom, že Kristův kříž byl ze dřeva černého bezu a že Jidáš si pro svou smrt vybral strom černého bezu. Ještě počátkem 20. století brali truhláři míru na rakev pomocí větve z černého bezu. U nás se na rakev kladl křížek z bezového dřeva.

Pokud bez, stojící u stavení, najednou vadl, znamenalo to, že v domě někdo vážně onemocní. Pokud bez uschl, znamenalo to, že někdo z domu do roka zemře.

Bez byl zasvěcen i severské bohyni podsvětí Hel. Ve středu říše Hel je studna (studny a jeskyně v lidové víře byly pokládány za brány do podsvětí), okolo které roste bez.

== Borovice (Pinus)

Borovice byla spojována s životní silou, životaschopností, smrtí a znovuzrozením, s energii ducha vegetace. Pokud byl mocnému vikingskému vůdci vypraven pohřeb na zemi, byl uložen do své dračí lodi vyrobené z borovice. Ve Skotsku se vůdcové rodů a bojovníci nechávali pohřbít přímo pod borovicí.

V kulturách Asie a Řecka symbolizuje nesmrtelnost. Při březnové rovnodennosti byl do Kybelina chrámu přinášen kmen borovice, zabalený jako mrtvola do pruhů plátna a ovinutý girlandami z fialek. Symbolizoval Kybelina druha Attida, jenž druhý den slavnosti „vstal z mrtvých“.

V Japonsku a Číně je stromem nesmrtelnosti a dlouhého života. Borovice se vysazovala i na hrobech, protože se věřilo, že posilňuje živé bytosti i duše zemřelých.

== Břečťan (Hedera)

Břečťan je znakem víry v život věčný a věrnosti. Jako plazivá rostlina obrůstá jiné stromy a proto se stal symbolem přátelství a lásky. Jako stále zelená rostlina symbolizuje nesmrtelnost a je také znamením stálosti, života, a doprovázení, protože se pevně přimkne ke svému nositeli.

Podle legendy Dionýsův syn Kissos (řecký název pro břečťan) při tanci zemřel. Bohyně Gaia ho přeměnila v břečťan. Břečťan je spojen s Dionýsem /Bakchus (bůh vegetace a vína) a je nejčastěji zobrazovanou rostlinou v římském umění. Dionýsos byl Titány roztrhán, bohyně Rhea ho však vzkřísila. Břečťan je proto často součástí dekorace sarkofágů a hrobek

V keltské symbolice znamenal symbol smrti, duchovního růstu a vyvolenosti. Křesťané uznávali břečťan jako symbol věrnosti a jeho listy vyobrazovali na svých sarkofázích jako symbol své víry a naděje na věčný život.

Pro první křesťany měl velký význam, protože na něj kladli tělo zesnulého. Břečťanové stále zelené listy vyjadřovaly víru, že ten, kdo zemřel ve víře v Krista, bude žít věčný život. Tím se snažili odlišit od pohanů, kteří bez naděje na věčný život své mrtvé zdobili cypřišem, který, když je jednou podťat, znovu již nevypučí.

Později v křesťanství břečťan znamenal zmrtvýchvstání a díky pnutí směrem vzhůru v něm věřící vidí duše zemřelých, které stoupají k Bohu a protože je stále zelený, je pro ně i symbolem dalšího života duše po smrti.

Břečťan je často využíván ve funerálních vazbách a výsadbách na hrobech i jako symbol plynoucího času.

Podle lidové víry spousta břečťanu na hrobě panny znamenalo, že nebožka odešla z tohoto světa kvůli své lásce k nevěrníkovi. Když ale na hrobě břečťan vůbec nerostl, znamenalo to, že duchové předků nespočívají v pokoji.

== Cedr (Cedrus) 

Cedr je symbolem ráje, nesmrtelnosti, pokory a pokání. Pro svoji krásu, mohutnost, stálou zeleň a dlouhověkost symbolizuje nesmrtelnost, neboť jeho dřevo bylo považováno za nezničitelné.

Ve starém Egyptě a Řecku byl považován za posvátný. Věřilo se, že cedr uchovává mrtvá těla. Chaldejci používali jeho větve k rituálům spojeným s životními silami a vzkříšením. Cedr se používal k hebrejskému rituálnímu obnovení čistoty po kontaktu se zemřelým. Údajně Kristus visel na kříži vyrobeného z cedru.

Jedna indiánská pověst vypráví _o náčelníkovi, kterému zemřela žena. Nemohl se s její smrtí smířit. Proto se rozhodl, že si nechá vyřezat její podobu ze dřeva. Starý řezbář z jeho kmene mu jeho přání splnil. Voda mu přinesla krásný kus dřeva a ten použil._

Náčelníkovo srdce se zaradovalo, protože opravdu tak jeho žena vypadala. Odnesl si ji do své chýše, posadil za stůl, oblékl ji šaty po nebožce. Každý den k ní mluvil, vyprávěl ji o všem, co dělal.

Stalo se, že jeho krásná žena ze dřeva začala dýchat, hýbat se. Ale nepromluvila. Náčelník byl přesto šťastný.

Jednou jeho žena těžce vzdychla, pak se ozval zvuk, jako když puká kmen. Jeho žena ze dřeva zemřela.

Když ji zvedl ze židle, spatřil tam malý stromek. Ten rostl z hliněné podlahy, prorazil strop chýše. Vyrostl z něj nádherný a veliký strom. Takový ještě nikdo z kmene neviděl. Dali mu jméno červený cedr.

A červený cedr roste všude tam, kde žijí Indiáni.

== Cesmína (Ilex)

Cesmína odpuzuje zlá kouzla a zlou energii Je symbolem hojnosti a života, který se jen uložil na přechodnou dobu zimního spánku, symbolem zimního slunovratu a věčného živote. Vyrábějí se z ní smuteční věnce a ozdoby na oltář.

Kelty byla přisuzována bohu Země a podsvětí.

Její pichlavé listy a červené plody symbolizují Kristovo utrpení a od dob Ukřižování se cesmína spojovala s odsouzeným člověkem, přesněji s jeho duchem.

== Cypřiš (Cupressus)

Cypřiš starými Řeky a Římany a také Egypťany byl považován za strom smrti a byl zasvěcen bohu podsvětí.

Legenda říká, že Cyparissus, Amykleův syn, jednoho dne při lovu zabil nešťastnou náhodou jelena uctívaného lesními nymfami, jehož měl v oblibě také Apollón, jeho přítel.

Cyparissus, který toho jelena považoval za svého miláčka, byl tak mučen výčitkami za svůj čin, že prosil Apollóna, aby mohl zemřít a přitom neustále mohl pro jelena truchlit a tím by jeho utrpení bylo věčné.

Apollón jej proměnil v cypřiš, který je znám svou dlouhověkostí, a ustanovil, aby byl vysazován na hrobech a tak mohl stále smutnit.

A tak se cypřiš stal v antické mytologii symbolem nesmrtelných duší, věčné smrti a truchlení.

Dle jiné řecké báje _dcery Eteoklesovy chtěly závodit s bohyněmi v tanci. Byly poraženy a kvůli této potupě se vrhly do močálu. Matka země je proměnila v cypřiše._

Tento strom blízké smrti byl přisuzován božstvu podsvětí, Moirám (jsou antickou obdobou sudiček) a Erýniím (bohyně pomsty). Pro významné osobnosti v antice se rakve zhotovovaly z cypřišového dřeva. Cypřišové háje byly také zasvěceny bohu lékařů – Asklepiovi.

Silueta cypřiše je nehybná a důstojná, což ulehčovala vnímat ho jako pohřební strom. Pro Háda a Pluta (bohové řeckého a římského podsvětí) byl posvátným stromem.

Cypřiš se začal uplatňovat v pohřebních obyčejích a jako hřbitovní strom také proto, že byl spojován s božským světlem a nebesy.

Podle pověsti _prorok Zarathustra si vysadil cypřiše ve své svatyni. Jejich semena si přinesl z ráje – vyrostly dva stromy, dvojčata (Sluneční a Lunární strom). S těmito stromy se údajně setkal Alexandr Veliký. Oba políbil, obětoval jim a zeptal se jich na svou budoucnost. Věštba stromů mu řekla, že dobude Indii, ale krátce po návratu do Babylonu zemře._

A tak se i stalo.

V Číně byl také vysazován často na hrobech, jednak proto, že dosahoval vysokého věku a symbolizoval pro ně nesmrtelnost, jednak proto, že hrob má mít stálý porost jako symbol dlouhého života.

U východních národů cypřišová větvička zavěšená na dveře hlásila okolí, že někdo z tohoto domu zemřel.

Cypřiš byl zvolen za strom pohřební také proto, že když je jednou podťat, nikdy už nevyrazí. Vysazoval se na hrobech. Když se ujal, znamenalo to, že nebožtík si užívá všech radostí, když uhynul, duše nebožtíkova je mučena na věčnosti, dokud modlitby pozůstalých a přímluva proroka Mohameda ho muk nezbaví.

Na západě patří bohům podsvětí a proto symbolizuje smrt a truchlení. Vysazoval se na hrobech také proto, že se věřilo, že chrání mrtvá těla. Tím se posiluje naděje na posmrtný život.

V křesťanské tradici symbolizuje žal. Byl uvažován i jako strom, ze kterého byl vyroben kříž pro Ježíše Krista.

V Severní Americe se dýmem z posvátného cypřiše přivolávali duchové.

== Dub (Quercus)

Dub je posvátným stromem v mnoha kulturách. Jeho listy a větve představují životní energii a sílu, dřevo trvanlivost a nesmrtelnost. Velmi oblíbené byly funerální dubové věnce ze zlatých lístků.

Posvátný dub také rostl v božím domě, kde Jákob vystavěl oltář a pochoval chůvu Deboru pod stromem, jenž pojmenoval Posvátný dub pláče.

Dub se pro křesťany stal nejen symbolem síly ale i nesmrtelnosti a vyřezávané věnce z dubu se pak kladly na hroby.

Staří Slované si svět představovali jako obrovský košatý dub, který se dělí na tři části: Prav (svět bohů, nachází se v košaté koruně), Jav (lidský hmotný svět, nachází se okolo kmene stromu) a Nav (podzemní svět mrtvých v kořenech dubu).

V lidových písních se zpívá, že na hrobě zavražděného mládence vyroste dub.

V pověsti o moudré keltské kněžce-drusadě Matře Navě se hovoří o tom, _že její duše se prolínala s duší mohutného dubu, který rostl u její chýše. Na něj se obracela, když potřebovala poradit a ze ševelu jeho listů si vyslechla odpověď._

_V době bójského vládce Luida se mezi jeho lidem objevil mor. Matře Navě její posvátný dub vyjevil, že lidé mají pojídat dužinu pupavy bílé a ta je vyléčí, což se i stalo._

== Fíkovník (Ficus sycomorus)

Fíkovník známý svým trvanlivým dřevem měl ve starém Egyptě velký význam. Když duše zemřelého vstoupila na svou pouť nebezpečnými sférami podsvětí, brzy dorazila k věčnému fikovníku sykomoře. Objevila se Hathor nebo Mut bez koruny na hlavě a nabídla zemřelému fíky z onoho světa a vodu života. Takto vybavily duši tím nejcennějším - věčným životem.

Stromy fikovníku sykomora mají v říši mrtvých nejvyšší význam. Sykomora byla zasvěcena Hathor (bohyně lásky a plodnosti, byla jedním z podsvětních božstev, nazývaná také paní západu - tedy říše mrtvých), Mut (bohyně oblohy) a Selket hetyt (znamená „ta, která přiměje hrdlo dýchat“), která byla spojována se vzkříšením a znovuzrozením, ochránkyně skříňky s kanopami (nádoby na orgány zemřelého).

„Usednou pod fíkovníkem“ znamenalo odpočinek po celodenní námaze či po nastalém utrpení.

== Granátovník (Punica Granatum)

Granátovník má širokou symboliku (od plodnosti, manželství, po posmrtný život). Řecký mýtus uvádí, že granátové jablko vzniklo z kapek Dionýsovi krve, když ho Titáni rozsápali na kusy.

Granátové jablko bylo spojováno s Hádem (řecký bůh podsvětí), který nabídl Persefoně granátové jablko a ona z něho pojedla několik zrníček.

V důsledku tohoto aktu musela zůstat v podsvětí jako jeho manželka.

Bylo dáváno do souvislosti s posmrtným životem a zmrtvýchvstání a proto byla častá jeho zobrazení jako součást výzdoby funerálních prostor.

Někteří věřící se domnívají, že ovoce, které v Rajské zahradě Adam a Eva pojedli, bylo granátové jablko.

== Hloh (Crataegus)

Hloh se pro své trny stal znakem trnové koruny. V Anglii věřili, že když přinesou do domu rozkvetlou hlohovou větvičku, zemře jejich matka.

== Hrušeň (Pyrus)

Hrušeň je symbolem pro dlouhověkost. Číňané si všimli, jak rychle její květy opadají a proto se jim hrušeň stala také symbolem vyjádření smutku a její plod symbolem odloučení.

== Jabloň (Malus)

Jabloň je symbolem života, nesmrtelnosti, věčného mládí a poznání. Kelty je nejčastěji spojována s jiným světem. Je úzce spjata s artušovskou legendou týkající se Artušové smrti. _Smrtelně zraněný Artuš se vybral v doprovodu tří dívek /kněžek na ostrov Avalon, ostrov Požehnaných (požehnaného mrtvého, brána do království ducha, keltský ráj), které se stalo místem jeho posledního odpočinku_.

Původ slova „avalon“ je jablko. V keltské mytologii je Avalon prastaré a posvátné místo údajně legendární Západní Ostrov Mrtvých, kam lidé přicházejí zemřít, transformovat se a znovu se narodit.

Jabloňová větvička byla propustkou do záhrobí. Byl jim Avalon, zázračná krajina s jabloněmi, cíl mořského putování mnoha galských hrdinů.

Jabloně na ostrově Avalon pěstovala čarodějnice Morgana. Rodily po celý rok a počet jablek nikdy neklesal.

Keltové považovali jablka za symbol nesmrtelnosti a věčného života. Měli zvyk jablka zahrabávat do země jako dar zemřelým, kteří čekají na znovuzrození. Věřili, že jablka jsou schopna přivést smrtelníky do říše nesmrtelných. Věřili také, že pokud na jabloni vykvetou v prosinci květy, znamenalo to, že v lednu někdo v domě zemře.

Jablka nikdy nesměla chybět v rohu hojnosti a později na vánočních stromcích. Odpradávna byla symbolem dokonalosti a naplnění, lásky a plodnosti, štěstí. Teprve církevní otcové změnili životodárné jablko v symbol hříchů a svodů. Údajně ho Eva přes zákaz utrhla ze stromu poznání a podala Adamovi. Tak se jablko stalo také symbolem pomíjivosti.

== Javor (Acer)

Javor symbolizuje živoucí přítomnost, která nedovoluje vidět, co bude po smrti. Symbolicky se javorovou větví zemřelý loučí s pozůstalými.

== Jeřáb (Sorbus)

Jeřáb střeží duši, když prochází branou smrti a proto se vysazuje na hřbitově s tisem, který má tutéž roli. Větev jeřábu se v Irsku věšela nad dveře domu proti ohnivým kouzlům a proto, aby do domu nemohli vstoupit duchové a aby mrtví nemohli vstát z hrobu. Věřili také, že duše zemřelého se dala uvěznit nebo připoutat v mrtvém těle, když se do jeho těla zarazil kolík vyrobený z jeřábu.

Křesťanští misionáři považovali jeřáb za kultovní strom pohanů a proto rozhlašovali, že je to prokletý strom, protože vyrostl z kosti Jidáše Iškariotského.

== Jilm (Ulmus)

Jilm údajně pocházel z podsvětí a proto ho staří Řekové vysazovali na hřbitovech jako symbol smrti a zármutku. _Když Orfeus (největší řecký hudebník a pěvec) oplakával smrt své manželky Eurydiky, z tónů jeho lyry vyrostl jilmový háj. Když se vrátil z podsvětí bez ní, nalezl útočiště právě pod jilmem._

Jilm také stával na rozcestích, odkud vedly cesty do pohádkového říše (elfí strom). V některých zemích byl jedním ze strážců dvora a nadpřirozenou branou mezi světem lidí a světem přírodních duchů.

V Anglii se tradičně používal na rakve.

== Jmelí (Viscum)

Jmelí je výrazně spojeno se severskou mytologií. _Bůh Balder (všemi milovaný bůh dobra a míru) měl zemřít ještě před příchodem Ragnaröku (soudný den). Na základě rozhodnutí bohů měla Frigg zařídit, aby k žádnému neštěstí nedošlo. Nechala všechny tvory a rostliny složit přísahu, že Baldrovi neublíží._

A tak se Balder stal terčem her bohů – stál uprostřed síně a bohové na něho vrhali kopí, kameny apod. Nic mu nemohlo ublížit.

_Bůh Loki Baldrovi záviděl nezranitelnost. Zjistil lstí, že Frigg opominula malou neškodnou rostlinu jmelí požádat o složení přísahy. Přemluvil Baldrova slepého bratra Höda, ať po bratrovi hodí jmelí. Ten tak učinil a Balder zemřel._

Větvičku jmelí používala řecká bohyně Persefona (manželka vládce podsvětí Háda), protože otevírala cestu do podsvětí.

Podle křesťanské legendy _bylo jmelí kdysi stromem. Z jeho větví prý Jozef vyřezal o Vánocích kolébku pro Ježíška. Po 33 letech porazili strom Římané a z jeho dřeva byl vytesán kříž, na němž Ježíš trpěl a skonal. Stromnemohl tuto hanbu unést, a proto seschnul do malých keříčků._

To, že přijímá živiny z jiného stromu symbolizuje obřad přijímání Kristova těla a krve (zdroj víry a síly).

== Lípa (Tilia)

Lípa se u nás často vysazovala v souvislosti s narozením potomka – ta ho pak provázela po celý život (kolébka - rakev). Byla považována za ochranný strom. Proto ji najdeme i na hřbitovech.

Věřilo se, že ten, který se po smrti stane upírem, škodí lidem. Aby se mu v tom zabránilo, musí být jeho mrtvola vyjmuta z rakve, musí se ji svázat ruce i nohy lipovým lýkem a srdce probodnout lipovým kůlem. Také vodníka bylo možné svázat jen provazem z lípového lýka.

V antice se vyprávěl příběh manželské lásky až za hrob, příběh Filomona a Baucis. _Jen tito dva chudí rolníci poskytli bohům (Jupiterovi a Merkurovi), převlečeným za poutníky, stravu a nocleh. Bohové potrestali vesnici nepohostinných obyvatel povodní, před kterou oba manželé varovali. Ti se zachránili na vysokém kopci._

_Bohové ale těm dvěma hodlali splnit přání. A oba si přáli, aby zemřeli ve stejnou chvíli, společně, aby je smrt nerozdělila. Bohové jim toto přání splnili. Proměnili je ve stejnou chvíli ve stromy - v dub a lípu._

== Mandloň (Amygdalus)

Mandloň má v rabínské legendě specifický význam. Do rajského města se dá totiž vstoupit otvorem v mandloňovém stromě. Na tomto místě nemá anděl smrti žádnou moc.

== Myrta (Myrtus)

Myrta je znakem nedotknutelnosti ve svatém Římě. Spojována s láskou (rostlina zasvěcená bohyni Afrodité/Venuši), svatbou i s pohřbíváním. Venuše/Afrodite, bohyně lásky a manželství, jíž byla myrta zasvěcená, byla pokládána současně za Venus Liblinu, bohyni smrti. Tedy svatba a smrt jsou v těsném spojení. Myrta se takto stává květinou svatební i pohřební.

S naším zvykem používat myrtu při svatbě se setkáváme již u Řeků – myrtový věneček měla na hlavě nevěsta i ženich.

Dle legendy Bakchus zachránil svou mrtvou matku z podsvětí a na důkaz díků zanechal za sebou větvičky myrty.

Staří Egypťané viděli ve stále se zelenající myrtě obraz nesmrtelnosti a proto její větve kladli na náhrobky. Listy používali při balzamování. Židé ji pokládali za symbol pokoje a proto zdobili své mrtvé myrtou.

Dle staré arabské pověsti si Adam vzal myrtovou větvičku, když musel opustit rajskou zahradu. Proto se stala symbolem naděje rajského života.

Díky její drobnosti a bílým kvítkům pro křesťany symbolizovala čistotu Panny Marie. Byla také symbolem posmrtného života a Boží přízně.

Dnes je myrtový věneček symbolem panenství. Věří se, že pokud myrta znenadání opadá, věští to blízkou smrt někoho z rodiny.

== Olivovník (Olea)

Olivovník skýtá plody, jež jsou součástí oleje k pomazání králů, kněží, posledního pomazání umírajícího. Je symbolem míru, duchovního vítězství, popřípadě vítězství nad smrtí.

Ve starém Řecku a Římě se olivové věnce a ratolesti staly všeobecným znakem svátku nebo obřadu, součástí pohřební výbavy. Olivové snítky na hrobech byly znamením pokoje, který měli bohové zajistit zemřelému.

V křesťanství je holubice s olivovou snítkou symbolem naděje a míru, naděje zemřelého na věčný život v Kristu. Proto se často nachází na náhrobcích či ve výzdobě katakomb, kde vyjadřuje naději na vzkříšení. Olivová ratolest byla znamením pokoje a usmíření.

== Osika (Populus tremula)

Osika je strážcem mytického znovuzrození Slunce. Proto roste na místě posledního odpočinku krétského slunečního boha. Na starých hrobech v Mezopotámii se nalezly zlaté věnce ve tvaru osikových listů.

V antice spolu s olší a cypřišem patřila mezi stromy vzkříšení. Údolí řeky Styx bylo zarostlé osikami. Řeka Styx teče v podsvětí a musí ji přejít každý zemřelý.

Křesťanská lidová legenda vypráví o tom, že _ze dřeva osiky byl vyroben kříž a od té doby se neustále třese. Jiná legenda říká, že _se na osice oběsil Jidáš. Listy osiky se neustále chvějí jako důsledek jehok podlé zrady._

== Palma (Palmae)

Palma jako stále zelená dřevina je v Egyptě symbolem slunce. Známe jsou posvátné palmové háje boha Re. Je vyobrazována na sarkofázích a obětních deskách a byla spojována také s posmrtným životem. Staří Egypťané v ní viděli strom života a palmové ratolesti pro ně byly symbolem dlouhého, nesmrtelného života. Nosívali je při pohřebních průvodech, nebo je pokládali na rakev, či hruď mumifikovaných mrtvol.

Palma je strom velmi odolný a její úžasná schopnost regenerace dala vzniknout myšlence palmy jako vítězného symbolu. V Římě se stala symbolem nesmrtelnosti a vítězství.

Palmovou ratolest nalezneme v rukou některých křesťanských světců jako symbol jejich mučednické smrti. Vyjadřuje vítězství nad pozemským životem plným utrpení a spásnou smrt, provázenou věčným mírem nebeského království. Jako obecný symbol vítězství zdobily palmové ratolesti často hroby prvních křesťanů.

== Platan (Platanus)

Platan byl v lidové tradici spojován se sluncem, lunou, podsvětím a nebesy – jako rovnováha protikladů. V mýtu o Héraklovi se hovoří o platanovém háji, ve kterém byly svatyně, jež ukazovaly, kde sestoupili do podsvětí Hádes, Persefona, Dionýsos. Pod platanem měla brloh obluda Hydra se sedmi hlavami.

== Tamaryšek (Tamarix)

Tamaryšek ve starověkém Egyptě zasvěcen Osiridově duši. Izraelský král Saul byl pohřben pod tamaryškem.

== Tis (Taxus)

Tis má všechny vlastnosti posvátného stromu (dlouhověkost, vždy zelený, tvrdé dřevo, rudé bobule, které se uplatňují jako jed i lék) a vzhledem k jeho spojení s Jiným světem se věřilo, že je obdařen silnými kouzelnými schopnostmi Jeho temně zelené jehličí mu dodává pochmurný vzhled. Jelikož je jedovatý, budil a budí vždy bázeň. Je spojený se smrtí i věčným životem.

V mytologii Keltů má nezastupitelné místo. Písmo Ogam, abeceda irských Keltů, se vyrývalo tisovými hůlkami. Ty se sbíraly o svátku Lugnasad, který prý založil bůh světla Lug, aby tak uctil svoji zemřelou manželku a chůvu Tailtu.

Tis je v keltské mytologii spojován se svátkem Samain, který se slaví z noci 31. října na 1. listopad. V té době se otevíraly brány mezi světem živých a mrtvých. Nejstarší severská runová abeceda má jako třináctou runu tzv. ihwaz nebo také eiwaz, což znamená tis. Tato runa symbolizuje smrt a znovu zrození.

Keltští válečníci o jejichž cti se pochybovalo, nebo kteří bránili své přesvědčení, se připravovali o život tak, že se nabodli na své meče zabodnuté do země pod posvátným tisem, zasvěceným království mrtvých. Neboť tis byl u Keltů symbolem nesmrtelnosti. Keltové měli za to, že kořeny tisu dokážou vysát ducha mrtvých a ze svých větví ho pak uvolnit do větru.

Ve Walesu se posvátnými tisy mínily stromy na hřbitově. Jejich poražení bylo trestáno vysokou pokutou. Welští duchovní stanovili délku života tisu na 19 683 let a přisoudili mu tak největší dlouhověkost ze všech živých bytostí na světě.

Není však jen stromem smrti, je i stromem života a hrál různé role v pohřebních rituálech jako protiváha k silám smrti. Ukazuje se, že severský Strom života, Yggdrasil (reprezentuje pilíř, základ a jednotu vesmíru, kořeny má ve vodě v podsvětí, kmen představuje pozemský svět a jeho větve sahají do nebe) není pravděpodobně jasan, ale tis.

Protože výpary tisu jsou jedovaté, mohou u člověka za velmi teplých dnů při těsném kontu vyvolat lehčí snění, kterému se přisuzovala funkce zprostředkování mezi zdejším a oním světem. Staří Řekové věřili, že usne-li někdo pod tisem, zemře.

V antické a řecké mytologii je tis považován za bránu do podsvětí, básníky nazýván stromem smrti. Proto býval zobrazován na starověkých mohylách a bývá vysazován i dnes na hřbitovech. Pro tmavou barvu svého jedovatého jehličí byl vysazován na místech spjatých se smrtí. Svou jedovatostí budil bázeň, svou pochmurnou barvou také.

Věřilo se, že svůj jed čerpá z podsvětí, kde žijí také hadi. Proto jej staří Řekové a Římané zasvětili bohům podsvětí. Furie (bohyně pomsty) držely v rukách pochodeň z tisového dřeva.

Na znamení smutku nosili staří Řekové na hlavách věnec z tisových snítek. Tis vždy symbolizoval vědomí věčnosti, byl chápán jako brána do podsvětí a tedy jako strážce duše.

Ve středověku byl symbolem zármutku a bolesti nad ztrátou blízkých. Proto se vysazoval na hřbitovech. Jeho pozlacené větvičky sloužily k zdobení hrobů. Ve starověku byl také symbolem nesmrtelnosti, protože se dožívá dlouhého věku a je stále zelený. Byl výrazem naděje v posmrtný život.

Tis vládl duším. Chránil člověka před temnými vlivy, ale vyvolával i vzpomínky na jeho minulou existenci. Osvobozoval od stínů minulosti. Staří Slované zasvětili tis bohu Dijovi (pán temnoty, tmy a noci).

== Topol bílý (Populus alba)

Topol bílý je spojován se smrtí. Říkalo se, že původně rostl v řeckém podsvětí na březích řeky Acherón. Háj topolů byl zasvěcen Persefoně ale i Hekaté. Obě jsou bohyně podsvětí. Topol černý prý rostl u vchodu do říše mrtvých (Hádes). Odtud sepětí topolu se hřbitovy.

Šajeni (severoameričtí indiáni) si vypráví o krásné dívce jménem _Duha. Měla hodně nápadníků, ale ona čekala na Mladého orla, do kterého byla zamilována. Byl však zabit v boji. Když se tu zprávu Duha dozvěděla, chtěla se oběsit. Chtěla jít tam, kam odešla jeho duše._

Šla k řece najít místo, kde se oběsí. Došla k topolu a ten na ni zavolal, aby vylezla na něho nahoru. Duha se polekala a utekla. Bála, že by si ji topol mohl vzít za manželku. A opravdu otěhotněla. Jedné noci vyrostl z jejího břicha mladý strom, zakořenil se a ona k němu přilnula a stala se jeho součástí. protože hodně zpívala, byl její zpěv slyšet i ve stromě.

Když se ostatní ženy dozvěděly tento příběh, už se nikdy na topolu neoběsily. A topoly se staly uctívanými stromy.

== Trnka (Prunus spinosa)

Trnka byla spojována s temnými stránkami života jako noc, smrt, podsvětí. Byla strážkyní rovnováhy protikladů (život a smrt, světlo a tma).

== Třešeň (Prunus avium)

Třešeň v Japonsku symbolizuje japonské hodnoty – prostota a cnost. Když opadají okvětní lístky aniž by uvadly, symbolizují dokonalost, která platí dokonce i pro smrt. Protože jen krátce kvete, byla v Japonsku symbolem samurajů, kteří měli být připraveni pro svého pána zemřít.

== Vavřín (Laurus nobilis)

Vavřín byl zasvěcen bohu Apollónovi a má zřetelnou vítěznou symboliku. Apollón byl patronem věštců, umělců a vůdcem múz. Básníci a pěvci proto přijali za svůj symbol vavřín – symbol úspěchu, vítězství zejména duchovního (často forma věnce, kterým se zdobila hlava vítěze).

V antice symbolizoval nesmrtelnost, vítězství a mír.

Křesťané převzali vavřín jako symbol vítězství, a proto se objevuje zejména na hrobech mučedníků a v katakombách. Zde symbolizuje vítězství ducha nad pozemskou existencí a naději na život věčný. V křesťanství symbolizuje Kristovo vítězství nad smrtí, všeobecně tedy nesmrtelnost.

== Vrba (Salix)

Vrba je strom trpělivosti, bolesti a smutku. Byla zasvěcena Měsíci. Slované věřili, že mrtví jsou na Měsíci. Na západě je stromem truchlení a Ďábla, je oblíbeným místem pobytu duchů a čarodějnic.

V řecké mytologii bylo podsvětí obklopeno vrbami. Vrbový háj byl zasvěcen bohyni Persefoně, manželce vládce podsvětí Háda.

Smuteční vrba se u Germánů kvůli větvím, které se sklání k zemi a připomínají řinoucí se proud slz, stala symbolem nářku nad smrtí. Byla spojována s podsvětím.

Věřilo se, že vrba nese vědomí o životě a smrti, jelikož i z dohola ořezaného a zdánlivě mrtvého starého těla vrby doslova překotně raší mladé výhonky a ztělesňují tak symbol věčného koloběhu bytí.

== Zimostráz (Buxus)

Zimostráz je symbolem vytrvalosti, statečnosti, života, nesmrtelnosti, víry v zmrtvýchvstání i ochranou proti zlým duchům.
