= Úvod, který je úvodem

[quote, Albert Einstein]
____
Chcete-li, aby byly vaše děti chytré,
čtěte jim pohádky.
Chcete-li, aby byly ještě chytřejší,
čtěte jim více pohádek.
____

*POHÁDKY A MÝTY* nás provázejí celý život. Jsou pro nás důležité jako kulturní dědictví (formují nás), jako prostředek komunikace (pomáhají nám porozumět různým kulturám a chování jejich členů), zdroj poznání sebe sama, symbolické ztvárnění životní cesty, nástroj individuace, obrazy archetypů (podle C. G. Junga jsou to zděděné vzorce emocionálního a duševního chování, tedy společné obsahy kolektivního nevědomí všech lidí). Nejčastějšími archetypy jsou zde archetyp hrdiny, cesty, dobra a zla.

Vyprávění mýtů a pohádek (jejich ústní předávání z generace na generaci) se kdysi dělo podle určitých zákonitostí. Indiánský vyprávěč říká, že vypráví jen to, co vyprávěl jeho pradědeček, který to zase slyšel od svých předků, a protože bude vyprávět tak, jak to má být, jak se takové příběhy mají vyprávět, nemůže ho postihnout žádná kletba.

Matky při zpívání ukolébavek kdysi zpívaly text přesně tak, jak ho zpívaly jejich matky a prabáby, protože věřily, že by jinak mohly své dítě uzpívat ne do spánku, ale do smrti.

*Pohádky* jsou základní motivy kultury. Jejich zdrojem jsou lidová vyprávění a snění. Nejsou definovány časově, místně. Nevážou se k historické události ani konkrétní osobě.

Příběhy pohádkových postav jsou prapůvodními vzory situací, které se opakují v praktickém i duchovním životě. Pohádky se dotýkají našich citů. V pohádce zakletý člověk má změněnou podobu, prokletý má změněnou duši. Hovoří o vnitřních a základních problémech člověka a o řešení jeho nesnází. Vystihují naše psychologické problémy a ukazují potřebné kroky ve vývoji od nezralosti ke zralosti a to vše pomocí jazyka symbolů. Proto mají pohádky na celém světě mnoho společných témat.

[quote, R. Steiner]
____
Pohádka tou nejjednodušší formou dokáže vyjádřit to nejhlubší z duchovního světa.
____

Svou pohádkovou řečí nás upozorňují na to, co je v životě skutečně důležité a správné a to na úrovni společenské, fyzické, duchovní (např. pomáhat i těm nejslabším, rozdělit se se strádajícím, nebát se požádat o radu a pomoc, přijmout dobrou radu a pomoc od všech bytostí, jít přes překážky za svým cílem, napravit své selhání, dostát svému slibu).

Každá pohádka je kouzelným zrcadlem, které odráží konflikty v našem vnitřním světe. A jelikož hrdina/ka pohádky tyto své problémy řeší, může přijít zasloužený šťastný konec a potrestání viníků. Potrestání toho, kdo činí zlo, je pro posluchače velice důležité.

{empty}J. Campbell upozorňuje, že i v té nejmenší dětské pohádce se skrývá schopnost dotknout se hlubinných tvořivých center jedince a probudit je. Pohádky jsou pro nás zdrojem zábavy i poučení. Poskytují nám nápady jak si uspořádat svůj vnitřní svět a na tom základě si pak vytvořit řád ve svém životě. Proto nás dokáží oslovit v každém věku.

*Mýty* jsou symbolická vyprávění velkolepého příběhu o původu světa, bohů a jejich činů (např. mýtus o vzniku světa, o potopě), o původu člověka a lidské společnosti. Jejich témata přesahují lidské i kulturní tradice. Jsou to posvátné příběhy, které nám mohou pomoci porozumět sobě, lépe pochopit, jaký smysl má svět okolo nás a jaký smysl se nachází za jeho samotnou existenci.

Podle J. Campbella jsou mýty archetypální sny celého světa, které se týkají velkých lidských problémů. Témata jsou nadčasové a každá kultura si je zpracovává jinak. Mýty přispívají k zapojení jednotlivce emocionálně i intelektuálně do místní organizace. Jsou však také prostředkem k vysvobození z pout ega (já), protože jsou jako tajný otvor, kterým se do projevů lidské kultury vlévá nevyčerpatelná energie kosmu.

Pomáhají nám hledat odpovědi na věčné otázky: Kdo jsme? Odkud a proč jsme sem přišli? Proč je svět takový jaký je? Co bude, až na něm nebudeme?

Pomáhají nám definovat lidskou existenci. Jsou pro nás zdrojem poznání světa a sebe sama, našeho místa a poslání, našeho vztahu k přírodě a vesmíru, smyslu lidského společenství.

Ukazují nám v podstatě cestu k duchovním možnostem našeho života.

Je to tak proto, že mýty nemají nic společného s rozumovou spekulací. Vznikají ze zážitku a citové sféry duševního života. Proto se vyjadřují v obrazech a imaginacích.

Mýtus představuje hledání smyslu života, případně je tím, co našemu životu smysl dává. C. G. Jung chápal mýty jako projev univerzálního kolektivního nevědomí, které obsahuje negativní i pozitivní zkušenosti lidských i zvířecích předků. Jeho součástí jsou archetypy.

V mytologii se odrážejí vzpomínky a představy nashromážděné v celé historii lidstva. Hlavní postavy mýtu, bohové a bohyně, ztělesňují původní archetypy (např. Moudrý stařec, Božské dítě, Velká matka, Stín, Hrdina).

Pohádky a mýty jsou významným zdrojem symbolů. Např. král v pohádce je symbolem moci, otcovské autority, královna matka je symbolem mateřské lásky. Lékař, který přináší radu, jak nemocného uzdravit, děd Vševěd, který zná odpověď na všechny otázky, jsou symbolem Moudrého starce. Mýtický hrdina Oidipus se stal symbolem závislého vztahu syna na matce (Oidipovský komplex). Někteří vidí v pohádkových hrdinech symbol duše a jejího vývoje.

Každý vnímá pohádku a mýtus svým originálním způsobem, který je utvářen jeho individuální životní historii. Proto skutečné pohádky a mýty neobsahují formulované morální poučení. V pohádkách je zlo potrestáno a končí šťastně.

**LEGENDA** je původní literární příběh o údajně historické postavě či události (např. legenda o Artušovi; o konkrétním svatém mučedníkovi), která obsahuje náměty dřívějších vyprávění předávaných ústně. Patří sem i vyprávění o vysvětlení vzniku některých rostlin (např. legenda o tom, jak se objevila červená růže; jak získaly květiny svou barvu), přírodních útvarů, pojmenování (místa, hradu, rodu atd.).

Pohádky, mýty a legendy se často překrývají a doplňují. Jsou to příběhy, pomocí kterých poznáváme, že i katastrofy mají svůj důvod, že naděje vždy existuje, a konec života může být i vysvobozením.

Náš skutečný svět sestává z kolektivních příběhů a náš individuální svět z našich osobních příběhů. Oba se prolínají a ovlivňují. Chceme-li lépe porozumět sobě, ostatním a tomu, co se kolem nás děje, čtěme a vyprávějme příběhy (ne drby), naslouchejme příběhům (ne pomluvám). Všechno se už jednou stalo.

**SYMBOLY** jsou součástí každé kulturní identity. Provází člověka i lidstvo od samého počátku. Může to být termín, slovo, obraz, který je v běžném životě dobře známý, ale který má vedle svého konvenčního a zjevného významu ještě specifické konotace (přiřazené významy). Mají tedy širší stránku, která není nikdy přesně definovaná. Představují vizuální podobu myšlenky. Jsou vyjádřeny něčím konkrétním, co slouží jako konvenční znak pro něco abstraktního (např. spirála, kříž, duha).

Symboly jsou používány v náboženských systémech, sociálních strukturách, politických seskupení, ve vědě, v obchodě, v osobním životě apod.

_Loga_ nejsou symboly. Jsou to vymyšlené značky (např. logo firmy).

_Brand_ je obchodní značka, která má na trhu jméno a u zákazníků váhu (např. pokud kupuji auto, kupuji produkt, pokud kupuji Mercedes, Škodu, adidas apod. kupuji brand).

Symboly mohou mít význam individuální (např. strom, u kterého si oba poprvé vyznali lásku) nebo univerzální (např. bílá holubice jako symbol míru; kruh jako symbol koloběhu života a znovuzrození, kola osudu, střídání ročních období, zvěrokruhu).

Pomocí symbolů lze komunikovat univerzálně a také lze vyvolávat určité emoce. Symboly jsou nositeli emočního náboje (např. symboly snů, archetypální symboly, náboženské symboly, státní symboly) a mají hluboký a široký význam (např. postava čarodějnice symbolizuje ženskou sílu, a to v její dobré i zlé podobě; jarní květiny symbolizují znovuzrození a nový život). Obohacují náš život (strom je zdrojem dřeva pro výrobu různých předmětů, ale současně v něm můžeme vidět symbol nás samých, našeho osobního růstu a našich vlastností, např. dub jako symbol síly).

Nalézáním symbolické hodnoty různých věcí, zvířat, rostlinstva apod. si uvědomujeme význam každodennosti existence a spolu s ní i její univerzálnosti a propojenosti.

Symboly vždy byly významným nástrojem manipulace a reklamy. Ovšem jsou také účinným nástrojem porozumění si mezi lidmi a pochopení sebe sama.

Ztráta mytologie, její komerční zneužívání, zejména v západní společnosti, vedla jedince k duchovnímu odloučení od sebe samého, k příklonu k hmotnému, k přetrhání kořenů s naší nejhlubší podstatou. Mýty v dnešní době nahradilo aktuální zpravodajství. Výsledkem je, že člověk ani společenství neví, kam kráčí a k čemu směřuje. Obklopeni vědeckými výdobytky a preferováním racionálního, vysvětlujícího a vědeckého pohledu na vše i na sebe, postrádáme duchovní rozměr své existence. Ani velká světová náboženství tuto propast nedokáží naplnit.

Na druhé straně hluboká náboženská víra spolu s touhou po západním životním stylu je velice zneužitelnou kombinací pro osobní sobecké vůdcovské cíle.

Silná komunita se vyznačuje sdílením tradice, víry, příběhů. Kultury bez "živých" mýtů se rozpadají a zanikají. Prostřednictvím mýtů k nám promlouvají hlasy našich předků. Tyto velkolepé příběhy nám umožňují přesah sebe sama. Pokud jim nenasloucháme, nejsme s nimi ve spojení, důsledkem toho je, že nejsme ve spojení se sebou samým a jsme frustrováni, oslabeni, dokonce nemocní a vyhýbáme se tématům, které v nás vyvolávají strach. A tím klíčovým tématem je umírání a smrt.

Pohádky a mýty dnes velice, převelice potřebujeme, protože nám pomáhají přiblížit se ke své duši, prociťovat své emoce, pochopit svou životní cestu a hodnoty a tím se ukotvit ve vlastním životě a ve své existenci a najít správný vztah ke světu. Podle J. Cambella dnešní společnost potřebuje mýty, které by jednotlivci pomohly ztotožnit se nikoli s jeho vlastním společenstvím, ve kterém žije, ale s celou planetou.

Proto narůstá potřeba nových pohádek a nových mýtů, které nás osloví, které nám mají co říci. Nelze se divit, že narůstá obliba fantasy literatury a filmů. Její autoři vytváří novodobé mýty (J. R. R. Tolkien – Pán prstenů, Piers Anthony – Inkarnace nesmrtelnosti, J. K. Rowlingová – Harry Potter, G. Lucas – Star Wars atd.), kdy zpracovávají klasická, základní a nesmrtelná mytologická témata (boj dobra a zla, smrt, znovuzrození, hledání smyslu života, proměna, hrdinství, individuální zodpovědnost, oběť…).

Jsme zaplavování novodobými autorskými pohádkami. Ne každý autor ale dokáže vytvořit opravdový pohádkový příběh – takový, co osloví naše nevědomí, naše emoce, duši. Mezi autory, kteří do dokážou, patří např. P, Hromádka. Ve své pohádce Vladař a Smrt_ vypráví o Smrti, která navštívila spravedlivého vladaře s tím, že by chtěla více poznat lidi. Oba se spřátelili a oba si tohoto přátelství velice vážili. Když ale Smrt musela odvést jeho jedinou dceru i vnučku, vladař odvrhl toto přátelství. Když se blíží konec jeho života, stále více se obává msty ze strany Smrti. Ale Smrt mu dává najevo, že ho chápe, že byl jen lidský. A plní mu jeho poslední přání._

V dnešní době je pro mnohé zpochybněna jednoznačná náboženská víra ve
vztahu ke smrti. Zejména rodiče hledají, jak o ni hovořit s dětmi. Je to téma klíčové, přitom dospělí se mu často vyhýbají, jakoby si nechtěli připustit existenční limit svého života. **Neexistuje** žádný věk, kdy nelze s potomkem na toto téma hovořit. Jen obsah hovoru je potřeba přizpůsobit věku a osobnosti dítěte. Nejen u přátel, ale i na knižním trhu najdou inspiraci. Knížky by si však měli přečíst dříve, než je budou společně číst se svými dětmi. Rodiče by měli rozhodnout, kterou knihu budou se svým potomkem číst. Dospívajícím lze nabídnout k individuálnímu přečtení i knihy, určené pro mladší kategorie. Vždy však být připraven s nimi o smrti hovořit a říci svůj názor.

Pro inspiraci: M. Zinnerová Princezna z třešňového království – lze ji číst s dětmi předškolního věku. Pro mladší školní věk lze sáhnout po knížce/komiksu L. K. Brown a M. Brown: Když dinosaurům někdo umře. Pro mladší a starší školní věk se hodí Návštěva malé smrti od K. Crowther. Dospívajícím lze nabídnout komiks Strážní andělé života a smrti od N. Špatenkové a J. Králové.

Půvabná knížka Je smrt jako duha? od J. B. L. Knox je vhodná pro každý věk.

Dospělým (zejména rodičům, prarodičům, zdravotníkům, psychologům) lze doporučit útlou knížku Oskar a růžová paní od E. E. Schmitt, ve které se velmi citlivě a krásně píše o chlapci, který pomalu umírá a jak se okolí, zejména rodiče, s ním bojí o tom mluvit a pro svůj strach ho vlastně v těch nejdůležitějších dnech jeho života nechávají osamělého. Ale naštěstí potkává růžovou paní.

Uvedené publikace téma smrti zpracovávají různě, ale vždy s laskavým pohledem.