= Závěr, který je novým začátkem

Jeden kupec poslal svého sluhu nakupovat na bagdádský bazar. Sluha se vrátil vystrašený. „Pane, na tržišti jsem narazil na Smrt. Pohrozila mi a šla dál. Mám strach. Prosím tě, půjč mi koně, pojedu do Samary, abych před ní utekl.“ Kupec mu vyhověl.

_Odpoledne šel kupec na tržiště a potkal tam Smrt. Přišel k ní a zeptal se: „Ráno jsi pohrozila mému sluhovi. Proč?“ „Já jsem mu nehrozila, jen jsem v překvapení rozhodila ruce nad tím, že ho vidím zde v Bagdádu. Mám si totiž pro něho dnes večer přijít do Samary.“_

Smrt je jistota. Nikdo před ní neuteče. Je nevyhnutelná. Je velkým tajemstvím. Lidé se ji často obávají a přejí si žít věčně. Zajímavým podnětem k zamyšlení nad tímto přáním je pohádka O moudrém Sulejmanovi.

_Když moudrý vládce Sulejman zestárnul, objevil se démon a řekl mu: „Moudrý a mocný Sulejmane, přijmi ode mne tuto nádobku s živou vodou. Když vodu vypiješ, budeš nesmrtelný."_

_Sulejman byl moudrý a proto rozkázal, aby mu přivedli tři náhodné chodce. Za chvíli mu přivedli chrabrého vojevůdce, bohatého kupce a prostého rolníka. Sulejman jim položil otázku: „Budu šťastný, když vypiji pohár živé vody a stanu se nesmrtelným?"_

_Válečník: „Ano, Budeš! Prožiješ tisíce let a za tu dobu si podmaníš všechny země. Není to štěstí, vidět porobené národy a svou říši bez hranic?"_

_Kupec: „Ano, budeš! Prožiješ tisíce let a nashromáždíš nedozírné poklady. Není to štěstí vidět kolem sebe tolik bohatství?"_

_Rolník: „Ó, můj vládče. Kupec i vojevůdce řekli jen polovinu pravdy. Řekli ti, proč budeš šťastný, ale neřekli ti, proč budeš nešťastný. Když totiž vypiješ živou vodu, získáš věčný život. Avšak přijde den, kdy zemře tvoje milovaná žena. Ty budeš žít a tvé bohatství bude narůstat. Tvoje děti, které tak miluješ, také zemřou. A ty budeš žít, tvoje moc bude stále větší a ty se z ní budeš radovat. Děti tvých dětí sejdou z tohoto světa. Ty budeš žít a počítat své bohatství. Všichni tvoji přátelé a věrní sluhové ti umřou před očima. Ty však budeš žít. Jednou přijde den, kdy se ohlédneš a neuvidíš ani ženu, ani děti, ani vnuky, ani přátelé. Takové na tebe čeká štěstí, můj vládče."_

_Sulejman: „Ach! K čemu je mi takový život, když nebudu mít kolem sebe děti? Nač je mi bohatství, když nebudu obklopen svými milujícími vnuky? Jak se mohu radovat z moci, když moje žena a mí přátelé budou mrtví?"_

_A uchopil nádobu se živou vodou a rozbil ji o zem._

[quote, D. Chopra]
Život je vzácný a pomíjivý okamžik, malý interval věčnosti. Sdílíme-li jej s láskou a péči, pak měl smysl.

Myšlenku, že příliš dlouhý život není pro člověka požehnáním, najdeme v pohádce A. Kutinové Pohádka ze sna. _Bůh si přál, aby Smrt chodila po světě a kosila toho, koho ji určil. Anděl Smrti kráčel před ní a tam, kde na dveře nakreslil bílý kříž, tam ona vešla a plnila vůli Boží._

_Smrt takto dlouho chodila po světě a byla unavená. Usedla pod rozkvetlou jabloň u vesnice, kde před ní kráčel Anděl Smrti. Přemýšlela o tom, že ona vidí jen pláč a zoufalství a přitom svět je tak krásný. Mládež se veselí, oráči pracují v polích._

_A tak Smrt prosí Boha, aby i ona mohla zakusit radosti i žal lidí. Aby vůbec něco cítila, protože se nedokáže radovat ani plakat._

_Bůh Otec byl z jejího přání smuten. Ale protože chtěl odměnit její práci, dovolil ji, aby šla na zem ale ve své podobě, jenom bez kosy. Na cestu ji dal rozum a schopnost práce. Jenom srdce ne, protože to by ji zradilo._

_Smrt přišla do vesnice. Zpočátku se ji všichni báli, když ale viděli, že je pracovitá a chytrá, oblíbili si ji. Všichni ji říkali "Kmotřička" a měli ji rádi, protože každému dobře poradila a všem pomáhala. I Jankovi, který ze všech mladých s ní nejvíce hovořil. Povídal ji, že má krásnou chůzi, že ji podle ní pozná už z dálky a kdyby byla dívka, miloval by ji._

_Když skončily práce na poli, byla v hospodě veselice. Smrt by si také ráda zatancovala, ale nikdo pro ni nešel, ani Janek. "To proto", myslela si, "že nemám srdce." A tak prosila Pána Boha, aby ji jen jedinkrát dal dívčí podobu a srdce, aby si mohla s Jankem zatancovat._

_Bůh Otec ji nakonec slíbil její přání splnit, ale varoval ji, aby neztratila své srdce, protože skončí její "pohádka"._

_Ze Smrti je najednou krásná dívka a Janek netančí se žádnou, jenom s ní. Dokonce ji vyprovází. Když se s ním Smrt loučí, Janek ji obejme, ona jej políbí a Janek padá mrtev k zemi._

_Smrt hořce zaplakala a prosila Boha, že již nechce být člověkem, nechce cítit ani radost ani žal._

_Pán Bůh ji utěšoval, že Janek bude vrácen k životu a zda ona chce jít za ním jako dívka. Smrt odmítla, protože věděla, že kdykoli by ho objala a políbila, zemřel by. Jen Pána Boha prosila, aby byl Janek i jeho rod dlouho živ a také celá jeho vesnice, protože všichni ji přijali mezi sebe a chovali se k ni přátelsky._

_Pán Bůh splnil Smrti i toto přání. Sdělil Andělu Smrti svou vůli, že této vesnici žehná a všichni v ní budou žít dvě stě let._

_Klidná, usmířená, bez lidského srdce se Smrt vrátila plnit svůj úkol. Když uplynulo dvě stě let, vydala se s Andělem Smrti ke své vesničce. A vidí, jak jim z vesnice jdou naproti mechem porostlé "špalky" a k tomu jim vesele vyhrává hudba. Smrt v těch "špalcích" poznala bývalé kamarády, jen Janek mezi nimi nebyl. Všichni vítají kmotřičku Smrt, že jsou už velice unaveni, a proto chtějí, aby si je už odvedla._

_"Myslela jsem si, kdovíjak svým vesničanům posloužím, když jim vyprosím dvě stě let života. A oni už na mne čekali s muzikou!" myslí si Smrt a hledá Janka. Vchází do jeho stavení a vidí, jak Janek sedí shrbený u pece, hlavu šedivou a nahlas si povídá: "Ona přijde. Celý život na ni čekám. Ani jsem se neoženil. Jsem tak sám!" Smrt neví, že ji Pán Bůh na tuto chvíli propůjčil vzhled dívky, do které se Janek zamiloval. A Janek ji vidí, napřahuje k ní ruce a volá: "Konečně jsi tady! Stále máš takovou krásnou a tichou chůzi." A Smrt k němu přistupuje a láskyplně ho obejme._

To, co neznáme, vzbuzuje v nás strach. Lidé se proto snaží odkrýt tajemství nejen zrození, ale i smrti. Vědomí nevyhnutelnosti smrti však ovlivňuje náš pohled na vlastní život, na jeho smysl.

Stará česká pohádka vypráví o tom, že _kdysi lidé věděli, kdy zemřou. Jednou se Pánbůh vydal na zem podívat se, jak lidé žijí. Potkal sedláka, který ležel v posteli a jeho pole bylo neobdělané, dobytek byl hladový. Ptal se ho, proč se nestará o své pole a dobytek. Sedlák mu odpověděl, že má za tři dny zemřít a proto nemá důvodu už něco dělat, když si on už z toho nic neužije. Pánbůh se rozhněval a lidem odebral toto vědění._

[verse, mongolské přísloví]
Neumírej dřív, než přijde smrt,
a nezoufej dřív, než tě stihne neštěstí.

Máme tendenci si myslet, že čas nám běží neúprosně dopředu. Podle starých Řeků náš čas odměřují Kronos a Kairos.

_Kronos_ je čas, který nám běží přímo, lineárně. Rosteme, chodíme do školy, pak do zaměstnání… Sledujeme ho na hodinkách, v kalendáři, měříme na sekundy, hodiny, dny měsíce, roky. Tento čas je významným zdrojem našeho časového stresu.

_Kairos_ je čas neurčitého časového období, kdy musíme udělat rozhodnutí. Ptáme se např: Je už čas na houby? Je čas na osamostatnění se? Je vhodný čas na změnu zaměstnání? Přišel čas založit si rodinu?

Jedná se o rozhodování „v pravou chvíli". Pohádky nás na tento čas upozorňují, zdůrazňují jeho význam – hrdina/ka musí své rozhodnutí udělat v pravou chvíli, jinak je vše zmařeno, protože může propást ten pravý čas, např. potkat pomocníky, získat moudrou radu, získat kouzelné předměty. Často se jedná o rozhodnutí vydat se neprodleně na cestu (získat zkušenosti, osvobodit zakletou princeznu/prince, získat nevěstu, donést živou vodu atd.), i když ho ostatní přemlouvají, aby zůstal doma.

Je důležité věnovat pozornost času, který měří Kairos. Je to čas přinášející klíčová a plodná rozhodnutí v osobním životě.

Ve slovanském mýtu Krcho a Smrt se Krcho ptá Smrti, co je to vlastně smrt. A Smrt mu odpovídá:
[verse]
____
Všechno plyne stále dokola.
Člověk dozraje jako zrno a pak padá k zemi.
A stejně i on jako zrno znovu vyklíčí.
____

To jsou slova naděje a pronáší je sama Smrt.

Odborná literatura poskytuje potravu rozumu (informace), pohádky a mýty poskytují potravu srdci a duši (symboly, metafory, podobenství, obrazy).

Pohádky, mýty, víra nám pomáhají zmírnit úzkost a strach ze smrti, obracejí náš zájem a pozornost na hlubší otázky života, jeho smyslu a hodnoty, a poskytují nám naději, že vše, co se nám děje, má smysl, i když jeho význam nám zůstává někdy skrytý.

[quote, C. G. Jung]
Je ve vážném zájmu stárnoucího člověka přijat možnosti smrti, protože ji nelze odmítnout, neboť rozum mu neukazuje nic než temný hrob.

Život každé živého tvora je ohraničen narozením a smrtí. Strach ze smrti doprovází lidstvo od té chvíle, co si člověk uvědomil, že je smrtelný. Lidé hledali a stále hledají odpovědi na otázky: 

.Co je to duše? Je duše nesmrtelná?
[quote, W. Wordsworth]
____
Naše duše je hvězda,
jež náš život nese,
je poslem dálek,
jichž nám nelze dohlédnout.
____

.Kde sídlí duše?
[quote, Novalis]
____
Duše sídlí tam,
kde se vnější svět
setkává
se světem vnitřním.
____

.Co je to vlastně smrt? Co se děje po smrti? Kam odchází duše?
[verse, G. Looser]
____
Kam odchází duše?
Duše se vrací sama k sobě
a poznává hlubiny své pravé podstaty.
____

Naše představy o smrti nám odhalují náš postoj k životu a k sobě samým.

.Následující otázky byly kladeny ve starém Egyptě na onom světě duším mrtvých.
[quote]
____
Našel jsi v životě radost?

Přinesl tvůj život radost ostatním?
____


Smrt se nám jeví takovou, jakou si ji sami představujeme.

V knížce Je smrt jako duha? autorka J. B. L. Knox vypráví o _malé Emilce, které se nelíbí Smrt v černém plášti s kosou, přicházející odvést si její babičku. A Smrt se na lidi zlobí, že s ní nechtějí jít. Když je pak zavede do své nádherné a voňavé zahrady mrtvých, tak jsou potěšeni._

_Emily Smrti navrhuje, aby zaměnila svůj černý plášť za barevný a přinášela s sebou vůni ze své zahrady. A Smrt se před jejíma očima úplně proměňuje a stává se „krásnější, než třpytivé hvězdy na temném nebi."_

Máme jen dvě možnosti – budeme se ji bát, nebo ji přijmeme ne jako protiklad život, ale jako jeho součást.

[quote]
____
Existuje ohromné množství zdrojů pro inspiraci našeho postoje ke smrti: pohádky, mýty, legendy, víry. 
Jsou to představy, prožitky, zkušenosti našich předků. Nejsme osamoceni.

Stačí jen naslouchat.
____

Smrt je samozřejmou součástí našeho života. Neutečeme před ní ani před svým životem. Všichni svým životem zanecháváme jedinečnou stopu.

Máme velký dar - možnost volby, jak prožít svůj život.

Pokud ho prožijeme tak, že se za něj nemusíme stydět sami před sebou, tedy ani za stopu, která po nás zůstane, smrti se nemusíme obávat.

[quote, Vilém z Pernštejna]
____
Neboj se té,
která jest poslední hranicí života.
Kdo se bojí smrti,
utíká od radosti života.
____
